// Code generated by `cargo soothfast bind gen`. DO NOT EDIT.
// A handle class with no methods never reads the value it holds.
#![allow(dead_code)]

/// Helpers the shims call. A module rather than bare functions: a parameter
/// named `text` would otherwise shadow the one that reads it.
mod ffi {
pub unsafe fn slice<'a, T>(data: *const T, len: usize) -> &'a [T] {
    match len {
        0 => &[],
        _ => unsafe { ::std::slice::from_raw_parts(data, len) },
    }
}

pub unsafe fn slice_mut<'a, T>(data: *mut T, len: usize) -> &'a mut [T] {
    match len {
        0 => &mut [],
        _ => unsafe { ::std::slice::from_raw_parts_mut(data, len) },
    }
}

pub unsafe fn text<'a>(data: *const ::std::os::raw::c_char) -> &'a str {
    if data.is_null() {
        return "";
    }
    unsafe { ::std::ffi::CStr::from_ptr(data) }.to_str().unwrap_or("")
}

/// Invalid UTF-8 on a non-null pointer yields `Some("")`, matching `text`'s
/// own fallback: only a null pointer means absent.
pub unsafe fn text_opt<'a>(data: *const ::std::os::raw::c_char) -> Option<&'a str> {
    if data.is_null() {
        return None;
    }
    Some(unsafe { ::std::ffi::CStr::from_ptr(data) }.to_str().unwrap_or(""))
}

/// A present string never crosses as NULL: an interior NUL byte, which C
/// can't represent, is replaced with U+FFFD first.
pub fn into_text(value: String) -> *mut ::std::os::raw::c_char {
    let value = value.replace('\0', "\u{fffd}");
    match ::std::ffi::CString::new(value) {
        Ok(text) => text.into_raw(),
        Err(_) => ::std::ffi::CString::default().into_raw(),
    }
}

pub unsafe fn clear(error: *mut *mut ::std::os::raw::c_char) {
    if !error.is_null() {
        unsafe { *error = ::std::ptr::null_mut() };
    }
}

pub unsafe fn report<E: ::std::fmt::Display>(error: *mut *mut ::std::os::raw::c_char, reason: &E) {
    if !error.is_null() {
        unsafe { *error = into_text(reason.to_string()) };
    }
}
}

/// An owned `bool` sequence. Release it with `core_bool_array_free`.
#[repr(C)]
pub struct CoreBoolArray {
    data: *mut bool,
    len: usize,
}

impl CoreBoolArray {
    fn empty() -> Self {
        CoreBoolArray { data: ::std::ptr::null_mut(), len: 0 }
    }

    fn new(values: Vec<bool>) -> Self {
        let mut boxed = values.into_boxed_slice();
        let out = CoreBoolArray { data: boxed.as_mut_ptr(), len: boxed.len() };
        ::std::mem::forget(boxed);
        out
    }
}

/// Release a sequence this library returned. Releasing one twice, or one it
/// did not return, is undefined.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn core_bool_array_free(array: CoreBoolArray) {
    if array.data.is_null() {
        return;
    }
    drop(unsafe {
        Box::from_raw(::std::ptr::slice_from_raw_parts_mut(array.data, array.len))
    });
}

/// An owned `f64` sequence. Release it with `core_f64_array_free`.
#[repr(C)]
pub struct CoreF64Array {
    data: *mut f64,
    len: usize,
}

impl CoreF64Array {
    fn empty() -> Self {
        CoreF64Array { data: ::std::ptr::null_mut(), len: 0 }
    }

    fn new(values: Vec<f64>) -> Self {
        let mut boxed = values.into_boxed_slice();
        let out = CoreF64Array { data: boxed.as_mut_ptr(), len: boxed.len() };
        ::std::mem::forget(boxed);
        out
    }
}

/// Release a sequence this library returned. Releasing one twice, or one it
/// did not return, is undefined.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn core_f64_array_free(array: CoreF64Array) {
    if array.data.is_null() {
        return;
    }
    drop(unsafe {
        Box::from_raw(::std::ptr::slice_from_raw_parts_mut(array.data, array.len))
    });
}

/// An owned `u8` sequence. Release it with `core_u8_array_free`.
#[repr(C)]
pub struct CoreU8Array {
    data: *mut u8,
    len: usize,
}

impl CoreU8Array {
    fn empty() -> Self {
        CoreU8Array { data: ::std::ptr::null_mut(), len: 0 }
    }

    fn new(values: Vec<u8>) -> Self {
        let mut boxed = values.into_boxed_slice();
        let out = CoreU8Array { data: boxed.as_mut_ptr(), len: boxed.len() };
        ::std::mem::forget(boxed);
        out
    }
}

/// Release a sequence this library returned. Releasing one twice, or one it
/// did not return, is undefined.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn core_u8_array_free(array: CoreU8Array) {
    if array.data.is_null() {
        return;
    }
    drop(unsafe {
        Box::from_raw(::std::ptr::slice_from_raw_parts_mut(array.data, array.len))
    });
}

/// An owned `usize` sequence. Release it with `core_usize_array_free`.
#[repr(C)]
pub struct CoreUsizeArray {
    data: *mut usize,
    len: usize,
}

impl CoreUsizeArray {
    fn empty() -> Self {
        CoreUsizeArray { data: ::std::ptr::null_mut(), len: 0 }
    }

    fn new(values: Vec<usize>) -> Self {
        let mut boxed = values.into_boxed_slice();
        let out = CoreUsizeArray { data: boxed.as_mut_ptr(), len: boxed.len() };
        ::std::mem::forget(boxed);
        out
    }
}

/// Release a sequence this library returned. Releasing one twice, or one it
/// did not return, is undefined.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn core_usize_array_free(array: CoreUsizeArray) {
    if array.data.is_null() {
        return;
    }
    drop(unsafe {
        Box::from_raw(::std::ptr::slice_from_raw_parts_mut(array.data, array.len))
    });
}

/// Release a string this library returned. Releasing one twice, or one it
/// did not return, is undefined.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn core_string_free(text: *mut ::std::os::raw::c_char) {
    if text.is_null() {
        return;
    }
    drop(unsafe { ::std::ffi::CString::from_raw(text) });
}

/// Opaque handle to `Counter`.
pub struct CoreCounter(::acme::Counter);

/// Release a `Counter`. Releasing one twice, or one this library did not return,
/// is undefined.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn core_counter_free(handle: *mut CoreCounter) {
    if handle.is_null() {
        return;
    }
    drop(unsafe { Box::from_raw(handle) });
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn core_counter_new(start: i64) -> *mut CoreCounter {
    Box::into_raw(Box::new(CoreCounter(::acme::Counter::new(start))))
}

/// Read `value` off a `Counter`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn core_counter_value(handle: *const CoreCounter) -> i64 {
    (unsafe { &*handle }).0.value.clone()
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn core_counter_absorb(handle: *mut CoreCounter, other: *const CoreCounter) {
    (unsafe { &mut *handle }).0.absorb(&(unsafe { &*other }).0)
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn core_counter_at(handle: *const CoreCounter, level: CoreLevel) -> i64 {
    (unsafe { &*handle }).0.at(level.into())
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn core_counter_bump(handle: *const CoreCounter, by: i64, error: *mut *mut ::std::os::raw::c_char) -> i64 {
    match (unsafe { &*handle }).0.bump(by) {
        Ok(value) => {
            unsafe { ffi::clear(error) };
            value
        }
        Err(reason) => {
            unsafe { ffi::report(error, &reason) };
            0
        }
    }
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn core_counter_bump_all(handle: *const CoreCounter, by: *const i64, by_len: usize) -> i64 {
    (unsafe { &*handle }).0.bump_all(unsafe { ffi::slice(by, by_len) }.to_vec())
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn core_counter_scale(handle: *mut CoreCounter, factor: i64) -> i64 {
    (unsafe { &mut *handle }).0.scale(factor)
}

/// `Level`, mirrored as a C enumeration.
#[repr(C)]
#[derive(Clone, Copy, Default, PartialEq, Eq)]
pub enum CoreLevel {
    #[default]
    Low,
    High,
}

impl ::std::convert::From<::acme::Level> for CoreLevel {
    fn from(value: ::acme::Level) -> Self {
        match value {
            ::acme::Level::Low => CoreLevel::Low,
            ::acme::Level::High => CoreLevel::High,
        }
    }
}

// A mirrored enum has no derived `Clone`; a field getter converts through
// this one instead of cloning an owned copy just to consume it.
impl ::std::convert::From<&::acme::Level> for CoreLevel {
    fn from(value: &::acme::Level) -> Self {
        match value {
            ::acme::Level::Low => CoreLevel::Low,
            ::acme::Level::High => CoreLevel::High,
        }
    }
}

impl ::std::convert::From<CoreLevel> for ::acme::Level {
    fn from(value: CoreLevel) -> Self {
        match value {
            CoreLevel::Low => ::acme::Level::Low,
            CoreLevel::High => ::acme::Level::High,
        }
    }
}

/// Opaque handle to `Mode`.
pub struct CoreMode(::acme::Mode);

/// Release a `Mode`. Releasing one twice, or one this library did not return,
/// is undefined.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn core_mode_free(handle: *mut CoreMode) {
    if handle.is_null() {
        return;
    }
    drop(unsafe { Box::from_raw(handle) });
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn core_describe(label: *const ::std::os::raw::c_char) -> *mut ::std::os::raw::c_char {
    match ::acme::describe(unsafe { ffi::text_opt(label) }) { Some(v) => ffi::into_text(v), None => ::std::ptr::null_mut() }
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn core_describe_owned(label: *const ::std::os::raw::c_char) -> *mut ::std::os::raw::c_char {
    match ::acme::describe_owned(unsafe { ffi::text_opt(label) }.map(String::from)) { Some(v) => ffi::into_text(v), None => ::std::ptr::null_mut() }
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn core_digest(data: *const u8, data_len: usize) -> CoreU8Array {
    CoreU8Array::new(::acme::digest(unsafe { ffi::slice(data, data_len) }))
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn core_fail(message: *const ::std::os::raw::c_char, error: *mut *mut ::std::os::raw::c_char) -> i64 {
    match ::acme::fail(unsafe { ffi::text(message) }) {
        Ok(value) => {
            unsafe { ffi::clear(error) };
            value
        }
        Err(reason) => {
            unsafe { ffi::report(error, &reason) };
            0
        }
    }
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn core_find_counter(start: i64) -> *mut CoreCounter {
    match ::acme::find_counter(start) { Some(v) => Box::into_raw(Box::new(CoreCounter(v))), None => ::std::ptr::null_mut() }
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn core_flags(values: *const bool, values_len: usize) -> CoreBoolArray {
    CoreBoolArray::new(::acme::flags(unsafe { ffi::slice(values, values_len) }.to_vec()))
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn core_greet(name: *const ::std::os::raw::c_char) -> *mut ::std::os::raw::c_char {
    ffi::into_text(::acme::greet(unsafe { ffi::text(name) }))
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn core_invert_bits(buf: *mut u8, buf_len: usize) {
    ::acme::invert_bits(unsafe { ffi::slice_mut(buf, buf_len) })
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn core_is_high(level: CoreLevel) -> bool {
    ::acme::is_high(&level.into())
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn core_mutate_counter(counter: *mut CoreCounter) -> i64 {
    ::acme::mutate_counter(&mut (unsafe { &mut *counter }).0)
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn core_normalize(input: *const f64, input_len: usize, factor: f64) -> CoreF64Array {
    CoreF64Array::new(::acme::normalize(unsafe { ffi::slice(input, input_len) }.to_vec(), factor))
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn core_peak_level(values: *const f64, values_len: usize) -> CoreLevel {
    ::acme::peak_level(unsafe { ffi::slice(values, values_len) }).into()
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn core_sample_ids(ids: *const usize, ids_len: usize) -> CoreUsizeArray {
    CoreUsizeArray::new(::acme::sample_ids(unsafe { ffi::slice(ids, ids_len) }.to_vec()))
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn core_scale_into(values: *const f64, values_len: usize, factor: f64, out: *mut f64, out_len: usize) {
    ::acme::scale_into(unsafe { ffi::slice(values, values_len) }, factor, unsafe { ffi::slice_mut(out, out_len) })
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn core_split(src: *const f64, src_len: usize, lo: *mut f64, lo_len: usize, hi: *mut f64, hi_len: usize) {
    ::acme::split(unsafe { ffi::slice(src, src_len) }, unsafe { ffi::slice_mut(lo, lo_len) }, unsafe { ffi::slice_mut(hi, hi_len) })
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn core_stamp(handle_: i64, error_: f64, register_: *const u8, register_len: usize) -> u64 {
    ::acme::stamp(handle_, error_, unsafe { ffi::slice(register_, register_len) })
}
