// Code generated by `cargo soothfast bind gen`. DO NOT EDIT.

using System;
using System.Runtime.InteropServices;

namespace Soothfast.Stats;

public static class Stats
{

    /// FNV-1a fingerprint of some bytes.
    public static ulong Fingerprint(ReadOnlySpan<byte> bytes)
    {
        unsafe
        {
            fixed (byte* bytesPtr = bytes)
            {
                ulong result = Native.soothfast_stats_fingerprint(bytesPtr, (nuint)bytes.Length);
                return result;
            }
        }
    }
}
