// Code generated by `cargo soothfast bind gen`. DO NOT EDIT.

using System;
using System.Runtime.InteropServices;
using Microsoft.Win32.SafeHandles;

namespace Soothfast.Stats;

/// A robust summary of one sample set.
public sealed class Summary : IDisposable
{
    private sealed class Handle : SafeHandleZeroOrMinusOneIsInvalid
    {
        internal Handle(IntPtr ptr) : base(true)
        {
            SetHandle(ptr);
        }

        protected override bool ReleaseHandle()
        {
            Native.soothfast_stats_summary_free(handle);
            return true;
        }
    }

    private readonly Handle _handle;

    internal IntPtr NativeHandle => _handle.DangerousGetHandle();

    /// Summarize a sample set. Fails on an empty one, which has no median.
    public Summary(ReadOnlySpan<double> samples)
    {
        unsafe
        {
            fixed (double* samplesPtr = samples)
            {
                IntPtr result = Native.soothfast_stats_summary_new(samplesPtr, (nuint)samples.Length, out IntPtr error);
                if (error != IntPtr.Zero)
                {
                    throw StatsException.FromNative(error);
                }
                _handle = new Handle(result);
            }
        }
    }

    internal Summary(IntPtr ptr)
    {
        _handle = new Handle(ptr);
    }

    public double Median
    {
        get
        {
            double result = Native.soothfast_stats_summary_median(NativeHandle);
            return result;
        }
    }

    /// Median absolute deviation, unscaled.
    public double Mad
    {
        get
        {
            double result = Native.soothfast_stats_summary_mad(NativeHandle);
            return result;
        }
    }

    public double Min
    {
        get
        {
            double result = Native.soothfast_stats_summary_min(NativeHandle);
            return result;
        }
    }

    public double Max
    {
        get
        {
            double result = Native.soothfast_stats_summary_max(NativeHandle);
            return result;
        }
    }

    /// How far `value` sits from the median, in MAD units.
    public double Deviations(double value)
    {
        double result = Native.soothfast_stats_summary_deviations(NativeHandle, value);
        return result;
    }

    /// How far each of `values` sits from the median, in MAD units.
    public double[] DeviationsAll(ReadOnlySpan<double> values)
    {
        unsafe
        {
            fixed (double* valuesPtr = values)
            {
                SoothfastStatsF64Array result = Native.soothfast_stats_summary_deviations_all(NativeHandle, valuesPtr, (nuint)values.Length);
                double[] value = new double[result.Len];
                if (result.Len > 0)
                {
                    Marshal.Copy(result.Data, value, 0, (int)result.Len);
                }
                Native.soothfast_stats_f64_array_free(result);
                return value;
            }
        }
    }

    /// [`Summary::deviations_all`], writing into a caller-owned buffer.
    public void DeviationsInto(ReadOnlySpan<double> values, Span<double> out_)
    {
        unsafe
        {
            fixed (double* valuesPtr = values)
            fixed (double* out_Ptr = out_)
            {
                Native.soothfast_stats_summary_deviations_into(NativeHandle, valuesPtr, (nuint)values.Length, out_Ptr, (nuint)out_.Length);
            }
        }
    }

    /// Read one statistic by name.
    public double Get(Metric metric)
    {
        double result = Native.soothfast_stats_summary_get(NativeHandle, (int)metric);
        return result;
    }

    /// A one-line rendering of the whole summary.
    public string Label()
    {
        IntPtr result = Native.soothfast_stats_summary_label(NativeHandle);
        string value = Marshal.PtrToStringUTF8(result) ?? string.Empty;
        Native.soothfast_stats_string_free(result);
        return value;
    }

    /// Scale every statistic by `factor`.
    public void Rescale(double factor)
    {
        Native.soothfast_stats_summary_rescale(NativeHandle, factor);
    }

    /// Parse a comma-separated sample set.
    public static Summary Parse(string text)
    {
        byte[] textBytes = System.Text.Encoding.UTF8.GetBytes(text + "\0");
        unsafe
        {
            fixed (byte* textPtr = textBytes)
            {
                IntPtr result = Native.soothfast_stats_summary_parse(textPtr, out IntPtr error);
                if (error != IntPtr.Zero)
                {
                    throw StatsException.FromNative(error);
                }
                return result == IntPtr.Zero ? null : new Summary(result);
            }
        }
    }

    public void Dispose()
    {
        _handle.Dispose();
    }
}
