// Code generated by `cargo soothfast sdk gen`. DO NOT EDIT.
/** Wire models for acme-items. */

export interface ApiResponse_Item {
  data?: Item | string;
  meta?: unknown;
  status: "ok" | "error";
}

/** One item. */
export interface Item {
  from?: string;
  id: number;
  logoUrl?: string;
  logo_url?: string;
  note?: string;
}

export interface NewItem {
  name: string;
}
