// Code generated by `cargo soothfast bind gen`. DO NOT EDIT.
// A handle class with no methods never reads the value it holds.
#![allow(dead_code)]

/// Helpers the shims call. A module rather than bare functions: a parameter
/// named `text` would otherwise shadow the one that reads it.
mod ffi {
pub unsafe fn slice<'a, T>(data: *const T, len: usize) -> &'a [T] {
    match len {
        0 => &[],
        _ => unsafe { ::std::slice::from_raw_parts(data, len) },
    }
}

pub unsafe fn slice_mut<'a, T>(data: *mut T, len: usize) -> &'a mut [T] {
    match len {
        0 => &mut [],
        _ => unsafe { ::std::slice::from_raw_parts_mut(data, len) },
    }
}

pub unsafe fn text<'a>(data: *const ::std::os::raw::c_char) -> &'a str {
    if data.is_null() {
        return "";
    }
    unsafe { ::std::ffi::CStr::from_ptr(data) }.to_str().unwrap_or("")
}

pub fn into_text(value: String) -> *mut ::std::os::raw::c_char {
    match ::std::ffi::CString::new(value) {
        Ok(text) => text.into_raw(),
        Err(_) => ::std::ptr::null_mut(),
    }
}

pub unsafe fn clear(error: *mut *mut ::std::os::raw::c_char) {
    if !error.is_null() {
        unsafe { *error = ::std::ptr::null_mut() };
    }
}

pub unsafe fn report<E: ::std::fmt::Display>(error: *mut *mut ::std::os::raw::c_char, reason: &E) {
    if !error.is_null() {
        unsafe { *error = into_text(reason.to_string()) };
    }
}
}

/// An owned `f64` sequence. Release it with `acme_core_f64_array_free`.
#[repr(C)]
pub struct AcmeCoreF64Array {
    data: *mut f64,
    len: usize,
}

impl AcmeCoreF64Array {
    fn empty() -> Self {
        AcmeCoreF64Array { data: ::std::ptr::null_mut(), len: 0 }
    }

    fn new(values: Vec<f64>) -> Self {
        let mut boxed = values.into_boxed_slice();
        let out = AcmeCoreF64Array { data: boxed.as_mut_ptr(), len: boxed.len() };
        ::std::mem::forget(boxed);
        out
    }
}

/// Release a sequence this library returned. Releasing one twice, or one it
/// did not return, is undefined.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn acme_core_f64_array_free(array: AcmeCoreF64Array) {
    if array.data.is_null() {
        return;
    }
    drop(unsafe {
        Box::from_raw(::std::ptr::slice_from_raw_parts_mut(array.data, array.len))
    });
}

/// An owned `u8` sequence. Release it with `acme_core_u8_array_free`.
#[repr(C)]
pub struct AcmeCoreU8Array {
    data: *mut u8,
    len: usize,
}

impl AcmeCoreU8Array {
    fn empty() -> Self {
        AcmeCoreU8Array { data: ::std::ptr::null_mut(), len: 0 }
    }

    fn new(values: Vec<u8>) -> Self {
        let mut boxed = values.into_boxed_slice();
        let out = AcmeCoreU8Array { data: boxed.as_mut_ptr(), len: boxed.len() };
        ::std::mem::forget(boxed);
        out
    }
}

/// Release a sequence this library returned. Releasing one twice, or one it
/// did not return, is undefined.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn acme_core_u8_array_free(array: AcmeCoreU8Array) {
    if array.data.is_null() {
        return;
    }
    drop(unsafe {
        Box::from_raw(::std::ptr::slice_from_raw_parts_mut(array.data, array.len))
    });
}

/// Release a string this library returned. Releasing one twice, or one it
/// did not return, is undefined.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn acme_core_string_free(text: *mut ::std::os::raw::c_char) {
    if text.is_null() {
        return;
    }
    drop(unsafe { ::std::ffi::CString::from_raw(text) });
}

/// Opaque handle to `Counter`.
pub struct AcmeCoreCounter(::acme::Counter);

/// Release a `Counter`. Releasing one twice, or one this library did not return,
/// is undefined.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn acme_core_counter_free(handle: *mut AcmeCoreCounter) {
    if handle.is_null() {
        return;
    }
    drop(unsafe { Box::from_raw(handle) });
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn acme_core_counter_new(start: i64) -> *mut AcmeCoreCounter {
    Box::into_raw(Box::new(AcmeCoreCounter(::acme::Counter::new(start))))
}

/// Read `value` off a `Counter`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn acme_core_counter_value(handle: *const AcmeCoreCounter) -> i64 {
    (unsafe { &*handle }).0.value.clone()
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn acme_core_counter_at(handle: *const AcmeCoreCounter, level: AcmeCoreLevel) -> i64 {
    (unsafe { &*handle }).0.at(level.into())
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn acme_core_counter_bump(handle: *const AcmeCoreCounter, by: i64, error: *mut *mut ::std::os::raw::c_char) -> i64 {
    match (unsafe { &*handle }).0.bump(by) {
        Ok(value) => {
            unsafe { ffi::clear(error) };
            value
        }
        Err(reason) => {
            unsafe { ffi::report(error, &reason) };
            0
        }
    }
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn acme_core_counter_bump_all(handle: *const AcmeCoreCounter, by: *const i64, by_len: usize) -> i64 {
    (unsafe { &*handle }).0.bump_all(unsafe { ffi::slice(by, by_len) }.to_vec())
}

/// `Level`, mirrored as a C enumeration.
#[repr(C)]
#[derive(Clone, Copy, Default, PartialEq, Eq)]
pub enum AcmeCoreLevel {
    #[default]
    Low,
    High,
}

impl ::std::convert::From<::acme::Level> for AcmeCoreLevel {
    fn from(value: ::acme::Level) -> Self {
        match value {
            ::acme::Level::Low => AcmeCoreLevel::Low,
            ::acme::Level::High => AcmeCoreLevel::High,
        }
    }
}

impl ::std::convert::From<AcmeCoreLevel> for ::acme::Level {
    fn from(value: AcmeCoreLevel) -> Self {
        match value {
            AcmeCoreLevel::Low => ::acme::Level::Low,
            AcmeCoreLevel::High => ::acme::Level::High,
        }
    }
}

/// Opaque handle to `Mode`.
pub struct AcmeCoreMode(::acme::Mode);

/// Release a `Mode`. Releasing one twice, or one this library did not return,
/// is undefined.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn acme_core_mode_free(handle: *mut AcmeCoreMode) {
    if handle.is_null() {
        return;
    }
    drop(unsafe { Box::from_raw(handle) });
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn acme_core_digest(data: *const u8, data_len: usize) -> AcmeCoreU8Array {
    AcmeCoreU8Array::new(::acme::digest(unsafe { ffi::slice(data, data_len) }))
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn acme_core_normalize(input: *const f64, input_len: usize, factor: f64) -> AcmeCoreF64Array {
    AcmeCoreF64Array::new(::acme::normalize(unsafe { ffi::slice(input, input_len) }.to_vec(), factor))
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn acme_core_stamp(handle_: i64, error_: f64, register_: *const u8, register__len: usize) -> u64 {
    ::acme::stamp(handle_, error_, unsafe { ffi::slice(register_, register__len) })
}
