// Code generated by `cargo soothfast bind gen`. DO NOT EDIT.
// A handle class with no methods never reads the value it holds.
#![allow(dead_code)]

use extendr_api::prelude::*;

fn __checked_int<T: ::std::convert::TryFrom<i128>>(
    value: f64,
    name: &str,
) -> ::std::result::Result<T, String> {
    if !value.is_finite() || value.fract() != 0.0 {
        return Err(format!("`{name}` is not a whole number"));
    }
    T::try_from(value as i128).map_err(|_| format!("`{name}` is out of range"))
}

#[extendr]
struct Counter(::acme::Counter);

#[extendr]
impl Counter {
    fn new(start: f64) -> ::std::result::Result<Counter, String> {
        let start = __checked_int::<i64>(start, "start")?;
        let __out = ::acme::Counter::new(start);
        Ok(Counter(__out))
    }

    fn value(&self) -> f64 {
        self.0.value.clone() as f64
    }

    fn at(&self, level: &str) -> ::std::result::Result<f64, String> {
        let level = {
            type Inner = ::acme::Level;
            match level {
                "Low" => Inner::Low,
                "High" => Inner::High,
                other => return Err(format!("unknown Level variant: {other}", other = other)),
            }
        };
        let __out = self.0.at(level);
        Ok(__out as f64)
    }

    fn bump(&self, by: f64) -> ::std::result::Result<f64, String> {
        let by = __checked_int::<i64>(by, "by")?;
        match self.0.bump(by) {
            Ok(value) => Ok(value as f64),
            Err(reason) => Err(::std::string::ToString::to_string(&reason)),
        }
    }

    fn bump_all(&self, by: &[f64]) -> ::std::result::Result<f64, String> {
        let by: Vec<i64> = by
            .iter()
            .map(|v| __checked_int::<i64>(*v, "by"))
            .collect::<::std::result::Result<_, _>>()?;
        let __out = self.0.bump_all(by);
        Ok(__out as f64)
    }
}

#[extendr]
struct Mode(::acme::Mode);

#[extendr]
impl Mode {
}

#[extendr]
fn describe(label: ) -> Option<String> {
    let __out = ::acme::describe(label);
    __out
}

#[extendr]
fn digest(data: &[u8]) -> Vec<u8> {
    let __out = ::acme::digest(data);
    __out
}

#[extendr]
fn find_counter(start: f64) -> ::std::result::Result<Robj, String> {
    let start = __checked_int::<i64>(start, "start")?;
    let __out = ::acme::find_counter(start);
    Ok(match __out { Some(v) => Robj::from(Counter(v)), None => ().into() })
}

#[extendr]
fn greet(name: &str) -> String {
    let __out = ::acme::greet(name);
    __out
}

#[extendr]
fn normalize(input: &[f64], factor: f64) -> Vec<f64> {
    let input = input.to_vec();
    let __out = ::acme::normalize(input, factor);
    __out
}

#[extendr]
fn peak_level(values: &[f64]) -> String {
    let __out = ::acme::peak_level(values);
    match __out {
        ::acme::Level::Low => "Low".to_string(),
        ::acme::Level::High => "High".to_string(),
    }
}

#[extendr]
fn stamp(handle: f64, error: f64, register: &[u8]) -> ::std::result::Result<f64, String> {
    let handle = __checked_int::<i64>(handle, "handle")?;
    let __out = ::acme::stamp(handle, error, register);
    Ok(__out as f64)
}

#[extendr]
fn trim(input: &[f64]) -> Robj {
    let __out = ::acme::trim(input);
    match __out { Some(v) => Robj::from(v), None => ().into() }
}

extendr_module! {
    mod acme_core;
    impl Counter;
    impl Mode;
    fn describe;
    fn digest;
    fn find_counter;
    fn greet;
    fn normalize;
    fn peak_level;
    fn stamp;
    fn trim;
}
