//! Soothfast binding engine: the exported Rust surface, bound natively.
//!
//! Where the SDK engine emits a client that talks to a server, this one
//! emits a glue crate that calls the code in-process. `#[soothfast::export]`
//! names what crosses over; rustdoc JSON says what shape it has; [`plan`]
//! turns the two into one language-neutral wrapper model that every backend
//! renders. Emission is deterministic, so `bind gen --check` can gate
//! staleness the way `sdk gen --check` does.

mod adt;
mod cabi;
mod cgo;
pub mod compat;
mod extendr;
mod fn_sig;
pub mod foreign;
pub mod gap;
mod jni;
mod magnus;
pub mod model;
mod naming;
mod napi;
pub mod plan;
mod pyo3;
mod resolve;
pub mod walk;
mod wasm;

use std::collections::BTreeMap;

/// Do-not-edit banner for generated Rust, in its comment syntax.
pub(crate) const GENERATED_RS: &str =
    "// Code generated by `cargo soothfast bind gen`. DO NOT EDIT.\n";

/// Lint allowance every glue crate needs: a handle class with no methods
/// never reads the value it holds.
pub(crate) const GLUE_ALLOW: &str =
    "// A handle class with no methods never reads the value it holds.\n#![allow(dead_code)]\n";

/// The same banner for generated TOML.
pub(crate) const GENERATED_TOML: &str =
    "# Code generated by `cargo soothfast bind gen`. DO NOT EDIT.\n";

/// The same banner, in Go's comment syntax.
pub(crate) const GENERATED_GO: &str =
    "// Code generated by `cargo soothfast bind gen`. DO NOT EDIT.\n";

/// The same banner for generated Java, which takes `//` just as well.
pub(crate) const GENERATED_JAVA: &str =
    "// Code generated by `cargo soothfast bind gen`. DO NOT EDIT.\n";

/// The same banner, in R's comment syntax.
pub(crate) const GENERATED_R: &str =
    "# Code generated by `cargo soothfast bind gen`. DO NOT EDIT.\n";

/// The same banner, in Ruby's comment syntax.
pub(crate) const GENERATED_RUBY: &str =
    "# Code generated by `cargo soothfast bind gen`. DO NOT EDIT.\n";

/// A language the binding engine can emit.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BindKind {
    Python,
    Wasm,
    /// Node.js, over a napi-rs native addon.
    Node,
    /// A `cdylib` behind a C header: the substrate every other language's
    /// foreign function interface can already read.
    CAbi,
    /// A cgo package generated over the C backend's own header and library.
    Go,
    /// A `cdylib` behind JNI, plus the Java sources that call it. The first
    /// garbage-collected target: a borrowed buffer reaches it pinned.
    Java,
    /// The same JNI glue as [`BindKind::Java`], with Kotlin sources in place
    /// of Java: a `@JvmStatic external fun` in a companion object compiles
    /// to the same static native method a Java class declares, so one glue
    /// crate serves both.
    Kotlin,
    /// An R package over extendr. R's collector does not move objects, so a
    /// borrowed numeric or raw vector reaches it zero-copy, same as Python.
    R,
    /// A gem wrapping a magnus glue crate. A Ruby `Array` boxes every
    /// element and a `String`'s bytes may move under a compacting
    /// collector, so unlike Python or Node every buffer is copied.
    Ruby,
}

impl BindKind {
    /// Every kind, for listings and error messages.
    pub const ALL: &'static [BindKind] = &[
        BindKind::Python,
        BindKind::Wasm,
        BindKind::Node,
        BindKind::CAbi,
        BindKind::Go,
        BindKind::Java,
        BindKind::Kotlin,
        BindKind::R,
        BindKind::Ruby,
    ];

    /// Canonical name, as `[[bind]]` config spells it and as
    /// `#[soothfast::export(skip(..))]` names it.
    pub fn name(self) -> &'static str {
        match self {
            BindKind::Python => "python",
            BindKind::Wasm => "wasm",
            BindKind::Node => "node",
            BindKind::CAbi => "c",
            BindKind::Go => "go",
            BindKind::Java => "java",
            BindKind::Kotlin => "kotlin",
            BindKind::R => "r",
            BindKind::Ruby => "ruby",
        }
    }

    /// Parse a config name, accepting the common short forms.
    pub fn parse_name(s: &str) -> Option<BindKind> {
        match s {
            "python" | "py" => Some(BindKind::Python),
            "wasm" | "js" | "javascript" => Some(BindKind::Wasm),
            "node" | "napi" => Some(BindKind::Node),
            "c" | "cabi" | "c-abi" => Some(BindKind::CAbi),
            "go" | "golang" => Some(BindKind::Go),
            "java" | "jni" => Some(BindKind::Java),
            "kotlin" | "kt" => Some(BindKind::Kotlin),
            "r" | "extendr" => Some(BindKind::R),
            "ruby" | "rb" => Some(BindKind::Ruby),
            _ => None,
        }
    }

    /// What this language can do with a borrowed contiguous buffer.
    ///
    /// Python reaches one through the buffer protocol, so a borrowed slice
    /// arrives as a pointer, a C caller hands over a pointer to begin with,
    /// and a napi typed array is a view into V8's own memory for the
    /// duration of the call. cgo may pass the backing array of a Go slice of
    /// primitives to C for the duration of one call, since it holds no Go
    /// pointers of its own. wasm has a separate address space, so every
    /// buffer is copied into linear memory whatever the signature says. Java
    /// reaches one pinned: no copy, but the collector cannot run for the
    /// call, which is a third answer of its own. R's own numeric and raw
    /// vectors are contiguous and its collector does not move objects, so a
    /// borrowed one reaches it the same way C's does. Ruby has no pointer to
    /// hand over either: an `Array` boxes each element and a `String`'s
    /// bytes may move under a compacting collector, so it copies like wasm.
    pub fn buffer_support(self) -> plan::BufferSupport {
        match self {
            BindKind::Python | BindKind::CAbi | BindKind::Node | BindKind::Go | BindKind::R => {
                plan::BufferSupport::ZeroCopy
            }
            BindKind::Wasm | BindKind::Ruby => plan::BufferSupport::AlwaysCopies,
            BindKind::Java | BindKind::Kotlin => plan::BufferSupport::Pinned,
        }
    }

    /// Emit a complete binding package for this exported surface.
    pub fn emit(
        self,
        surface: &model::Surface,
        gaps: Vec<gap::Gap>,
        opts: &BindOptions,
    ) -> Result<BindFileSet, String> {
        // Every C symbol is derived from `opts.package` during lowering, so
        // Go's C-facing identity (package/library naming, symbol prefixes)
        // has to replace the Go module path there with the module name
        // before the plan exists, not only when rendering around it.
        let go_lower_opts;
        let lower_opts = match self {
            BindKind::Go => {
                go_lower_opts = cgo::c_opts(opts);
                &go_lower_opts
            }
            _ => opts,
        };
        let plan = plan::lower(surface, gaps, lower_opts, self)?;
        let mut out = match self {
            BindKind::Python => pyo3::emit(&plan, opts)?,
            BindKind::Wasm => wasm::emit(&plan, opts)?,
            BindKind::Node => napi::emit(&plan, opts)?,
            BindKind::CAbi => cabi::emit(&plan, opts)?,
            BindKind::Go => cgo::emit(&plan, opts)?,
            BindKind::Java => jni::emit(&plan, opts)?,
            BindKind::Kotlin => jni::emit_kotlin(&plan, opts)?,
            BindKind::R => extendr::emit(&plan, opts)?,
            BindKind::Ruby => magnus::emit(&plan, opts)?,
        };
        // A repository that trims file endings would otherwise rewrite what
        // was just emitted, and `gen --check` would call it stale forever.
        for text in out.files.values_mut() {
            while text.ends_with('\n') {
                text.pop();
            }
            text.push('\n');
        }
        out.gaps = plan.gaps.iter().map(gap::Gap::explain).collect();
        Ok(out)
    }
}

/// Everything an emitter needs that the exported surface does not carry.
#[derive(Debug, Clone)]
pub struct BindOptions {
    /// Distribution name, e.g. `acme-core`.
    pub package: String,
    /// Import name, e.g. `acme_core`.
    pub module: String,
    pub version: String,
    /// The crate the glue calls into, as Rust paths spell it.
    pub crate_name: String,
    /// The same crate as cargo names it, which keeps its hyphens.
    pub crate_package: String,
    /// Path to that crate, relative to the glue crate.
    pub crate_path: String,
    pub description: Option<String>,
    pub repository: Option<String>,
    /// Target triples the package is built for. Empty means the language's
    /// own default.
    pub targets: Vec<String>,
    /// The binding library release the generated glue builds against. `None`
    /// takes the backend's own default.
    pub backend_version: Option<String>,
}

impl Default for BindOptions {
    fn default() -> Self {
        BindOptions {
            package: String::new(),
            module: String::new(),
            version: String::new(),
            crate_name: String::new(),
            crate_package: String::new(),
            crate_path: "..".into(),
            description: None,
            repository: None,
            targets: Vec::new(),
            backend_version: None,
        }
    }
}

/// The `<os>-<arch>` a Java native library is staged and looked up under,
/// for a Rust target triple. Shared by `cargo soothfast bind build`'s jar
/// packaging and the `jni` backend's own `Natives.java` runtime lookup, so
/// the two can't drift apart.
pub fn java_native_dir(triple: &str) -> String {
    jni::native_dir_for_triple(triple)
}

/// Rendered glue and package files, keyed by path relative to the output
/// directory.
#[derive(Debug, Clone, Default)]
pub struct BindFileSet {
    pub files: BTreeMap<String, String>,
    /// Shapes the target language cannot express precisely.
    pub notes: Vec<String>,
    /// What the surface declared but the binding could not carry, already
    /// explained. A different shortfall from a note, and reported apart from
    /// one so the remedy is not confused.
    pub gaps: Vec<String>,
}
