//! Soothfast binding engine: the exported Rust surface, bound natively.
//!
//! Where the SDK engine emits a client that talks to a server, this one
//! emits a glue crate that calls the code in-process. `#[soothfast::export]`
//! names what crosses over; rustdoc JSON says what shape it has; [`plan`]
//! turns the two into one language-neutral wrapper model that every backend
//! renders. Emission is deterministic, so `bind gen --check` can gate
//! staleness the way `sdk gen --check` does.

mod adt;
mod cabi;
pub mod compat;
mod fn_sig;
pub mod foreign;
pub mod gap;
pub mod model;
mod naming;
pub mod plan;
mod pyo3;
mod resolve;
pub mod walk;
mod wasm;

use std::collections::BTreeMap;

/// Do-not-edit banner for generated Rust, in its comment syntax.
pub(crate) const GENERATED_RS: &str =
    "// Code generated by `cargo soothfast bind gen`. DO NOT EDIT.\n";

/// Lint allowance every glue crate needs: a handle class with no methods
/// never reads the value it holds.
pub(crate) const GLUE_ALLOW: &str =
    "// A handle class with no methods never reads the value it holds.\n#![allow(dead_code)]\n";

/// The same banner for generated TOML.
pub(crate) const GENERATED_TOML: &str =
    "# Code generated by `cargo soothfast bind gen`. DO NOT EDIT.\n";

/// A language the binding engine can emit.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BindKind {
    Python,
    Wasm,
    /// A `cdylib` behind a C header: the substrate every other language's
    /// foreign function interface can already read.
    CAbi,
}

impl BindKind {
    /// Every kind, for listings and error messages.
    pub const ALL: &'static [BindKind] = &[BindKind::Python, BindKind::Wasm, BindKind::CAbi];

    /// Canonical name, as `[[bind]]` config spells it and as
    /// `#[soothfast::export(skip(..))]` names it.
    pub fn name(self) -> &'static str {
        match self {
            BindKind::Python => "python",
            BindKind::Wasm => "wasm",
            BindKind::CAbi => "c",
        }
    }

    /// Parse a config name, accepting the common short forms.
    pub fn parse_name(s: &str) -> Option<BindKind> {
        match s {
            "python" | "py" => Some(BindKind::Python),
            "wasm" | "js" | "javascript" => Some(BindKind::Wasm),
            "c" | "cabi" | "c-abi" => Some(BindKind::CAbi),
            _ => None,
        }
    }

    /// What this language can do with a borrowed contiguous buffer.
    ///
    /// Python reaches one through the buffer protocol, so a borrowed slice
    /// arrives as a pointer, and a C caller hands over a pointer to begin
    /// with. JavaScript and wasm have separate address spaces, so every
    /// buffer is copied into linear memory whatever the signature says.
    pub fn buffer_support(self) -> plan::BufferSupport {
        match self {
            BindKind::Python | BindKind::CAbi => plan::BufferSupport::ZeroCopy,
            BindKind::Wasm => plan::BufferSupport::AlwaysCopies,
        }
    }

    /// Emit a complete binding package for this exported surface.
    pub fn emit(
        self,
        surface: &model::Surface,
        gaps: Vec<gap::Gap>,
        opts: &BindOptions,
    ) -> Result<BindFileSet, String> {
        let plan = plan::lower(surface, gaps, opts, self)?;
        let mut out = match self {
            BindKind::Python => pyo3::emit(&plan, opts)?,
            BindKind::Wasm => wasm::emit(&plan, opts)?,
            BindKind::CAbi => cabi::emit(&plan, opts)?,
        };
        out.gaps = plan.gaps.iter().map(gap::Gap::explain).collect();
        Ok(out)
    }
}

/// Everything an emitter needs that the exported surface does not carry.
#[derive(Debug, Clone)]
pub struct BindOptions {
    /// Distribution name, e.g. `acme-core`.
    pub package: String,
    /// Import name, e.g. `acme_core`.
    pub module: String,
    pub version: String,
    /// The crate the glue calls into, as Rust paths spell it.
    pub crate_name: String,
    /// The same crate as cargo names it, which keeps its hyphens.
    pub crate_package: String,
    /// Path to that crate, relative to the glue crate.
    pub crate_path: String,
    pub description: Option<String>,
    pub repository: Option<String>,
    /// Target triples the package is built for. Empty means the language's
    /// own default.
    pub targets: Vec<String>,
    /// The binding library release the generated glue builds against. `None`
    /// takes the backend's own default.
    pub backend_version: Option<String>,
}

impl Default for BindOptions {
    fn default() -> Self {
        BindOptions {
            package: String::new(),
            module: String::new(),
            version: String::new(),
            crate_name: String::new(),
            crate_package: String::new(),
            crate_path: "..".into(),
            description: None,
            repository: None,
            targets: Vec::new(),
            backend_version: None,
        }
    }
}

/// Rendered glue and package files, keyed by path relative to the output
/// directory.
#[derive(Debug, Clone, Default)]
pub struct BindFileSet {
    pub files: BTreeMap<String, String>,
    /// Shapes the target language cannot express precisely.
    pub notes: Vec<String>,
    /// What the surface declared but the binding could not carry, already
    /// explained. A different shortfall from a note, and reported apart from
    /// one so the remedy is not confused.
    pub gaps: Vec<String>,
}
