// Code generated by `cargo soothfast bind gen`. DO NOT EDIT.

using System;
using System.Runtime.InteropServices;

namespace Acme.Core;

/// Thrown for every call this package's native library reports as failed.
public sealed class CoreException : Exception
{
    internal CoreException(string message) : base(message)
    {
    }

    internal static CoreException FromNative(IntPtr error)
    {
        string message = Marshal.PtrToStringUTF8(error) ?? string.Empty;
        Native.acme_core_string_free(error);
        return new CoreException(message);
    }
}
