// Code generated by `cargo soothfast bind gen`. DO NOT EDIT.

using System;
using System.Runtime.InteropServices;
using Microsoft.Win32.SafeHandles;

namespace Acme.Core;

public sealed class Mode : IDisposable
{
    private sealed class Handle : SafeHandleZeroOrMinusOneIsInvalid
    {
        internal Handle(IntPtr ptr) : base(true)
        {
            SetHandle(ptr);
        }

        protected override bool ReleaseHandle()
        {
            Native.acme_core_mode_free(handle);
            return true;
        }
    }

    private readonly Handle _handle;

    internal IntPtr NativeHandle
    {
        get
        {
            if (_handle.IsClosed)
            {
                throw new ObjectDisposedException(nameof(Mode));
            }
            return _handle.DangerousGetHandle();
        }
    }

    internal Mode(IntPtr ptr)
    {
        _handle = new Handle(ptr);
    }

    public void Dispose()
    {
        _handle.Dispose();
    }
}
