// Code generated by `cargo soothfast bind gen`. DO NOT EDIT.

#pragma once

#include "stats.h"

#include <cstdint>
#include <memory>
#include <optional>
#include <span>
#include <stdexcept>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

namespace soothfast::stats {

class Error : public std::runtime_error {
public:
    explicit Error(const std::string &message) : std::runtime_error(message) {}
};

inline std::string take_string(char *raw) {
    std::string value(raw);
    stats_string_free(raw);
    return value;
}

inline std::vector<double> to_vector_f64(stats_f64_array arr) {
    std::vector<double> out(arr.data, arr.data + arr.len);
    stats_f64_array_free(arr);
    return out;
}

// Which statistic a comparison reads.
enum class Metric {
    Median,
    Mad,
    Min,
    Max,
};

// A robust summary of one sample set.
class Summary {
public:
    // Summarize a sample set. Fails on an empty one, which has no median.
    explicit Summary(std::span<const double> samples) : handle_(construct(samples)) {}

    static stats_summary *construct(std::span<const double> samples) {
        char *error = nullptr;
        auto *raw = stats_summary_new(samples.data(), samples.size(), &error);
        if (error != nullptr) {
            std::string message(error);
            stats_string_free(error);
            throw Error(message);
        }
        return raw;
    }

    // Adopts a pointer another bound call already returned; C++ has no package-private tier to hide this behind.
    explicit Summary(stats_summary *raw) : handle_(raw) {}

    stats_summary *get() const noexcept { return handle_.get(); }

    double median() const {
        auto raw_result = stats_summary_median(handle_.get());
        return raw_result;
    }

    // Median absolute deviation, unscaled.
    double mad() const {
        auto raw_result = stats_summary_mad(handle_.get());
        return raw_result;
    }

    double min() const {
        auto raw_result = stats_summary_min(handle_.get());
        return raw_result;
    }

    double max() const {
        auto raw_result = stats_summary_max(handle_.get());
        return raw_result;
    }

    // How far `value` sits from the median, in MAD units.
    double deviations(double value) const {
        auto raw_result = stats_summary_deviations(handle_.get(), value);
        return raw_result;
    }

    // How far each of `values` sits from the median, in MAD units.
    std::vector<double> deviations_all(std::span<const double> values) const {
        auto raw_result = stats_summary_deviations_all(handle_.get(), values.data(), values.size());
        return to_vector_f64(raw_result);
    }

    // [`Summary::deviations_all`], writing into a caller-owned buffer.
    void deviations_into(std::span<const double> values, std::span<double> out) const {
        stats_summary_deviations_into(handle_.get(), values.data(), values.size(), out.data(), out.size());
    }

    // Read one statistic by name.
    double get(Metric metric) const {
        auto raw_result = stats_summary_get(handle_.get(), static_cast<stats_metric>(metric));
        return raw_result;
    }

    // A one-line rendering of the whole summary.
    std::string label() const {
        auto raw_result = stats_summary_label(handle_.get());
        return take_string(raw_result);
    }

    // Scale every statistic by `factor`.
    void rescale(double factor) {
        stats_summary_rescale(handle_.get(), factor);
    }

    // Parse a comma-separated sample set.
    static Summary parse(std::string_view text) {
        std::string text_owned(text);
        char *error = nullptr;
        auto raw_result = stats_summary_parse(text_owned.c_str(), &error);
        if (error != nullptr) {
            std::string message(error);
            stats_string_free(error);
            throw Error(message);
        }
        return Summary(raw_result);
    }

private:
    struct Deleter {
        void operator()(stats_summary *p) const noexcept { stats_summary_free(p); }
    };

    std::unique_ptr<stats_summary, Deleter> handle_;
};

// FNV-1a fingerprint of some bytes.
inline uint64_t fingerprint(std::span<const uint8_t> bytes) {
    auto raw_result = stats_fingerprint(bytes.data(), bytes.size());
    return raw_result;
}

} // namespace soothfast::stats
