// @generated by `cargo soothfast docs gen-tests`
// source: docs/bindings.md
#![allow(unused)]

// line 43
#[rustfmt::skip]
#[test]
fn doc_block_line_43() {
    use soothfast_demo::{Metric, Summary, fingerprint};

    let summary = Summary::new(vec![3.0, 1.0, 5.0, 4.0]).expect("summarizes");
    assert_eq!(summary.median, 3.5);
    assert_eq!(summary.get(Metric::Min), 1.0);
    assert!(Summary::new(Vec::new()).is_err());

    // The frozen FNV-1a soothfast records in baselines and lockfiles.
    assert_eq!(fingerprint(b"foobar".to_vec()), 0x8594_4171_f739_67e8);
}
