// @generated by `cargo soothfast docs gen-tests`
// source: README.md
#![allow(unused)]

// line 83: compile-only (no_run)
#[cfg(feature = "runner")]
#[rustfmt::skip]
#[allow(dead_code)]
fn doc_block_line_83() {
    // benches/soothfast.rs
    soothfast::bench_main!();

    mod mylib {
        pub fn sorted(input: &[f64]) -> Vec<f64> {
            let mut v = input.to_vec();
            v.sort_by(|a, b| a.partial_cmp(b).unwrap());
            v
        }
    }

    #[soothfast::fixture]
    fn values_n(n: usize) -> Vec<f64> {
        (0..n).map(|i| (n - i) as f64).collect()
    }

    // Checked claims: complexity verified by size sweep, alloc count exact.
    #[soothfast::bench(group = "sort", setup_sized = values_n, sizes(1024, 4096, 16384),
                     complexity = "n log n", alloc = 2, covers = "mylib::sorted")]
    fn bench_sorted(input: &[f64]) { soothfast::keep(mylib::sorted(soothfast::keep(input))); }
    // Route constant inputs through soothfast::keep or LLVM const-folds them away.
}
