# Code generated by `cargo soothfast bind gen`. DO NOT EDIT.
describe <- function(label) .Call(wrap__describe, label)
describe_owned <- function(label) .Call(wrap__describe_owned, label)
digest <- function(data) .Call(wrap__digest, data)
fail <- function(message) .Call(wrap__fail, message)
find_counter <- function(start) .Call(wrap__find_counter, start)
greet <- function(name) .Call(wrap__greet, name)
is_high <- function(level) .Call(wrap__is_high, level)
maybe_ratio <- function(value) .Call(wrap__maybe_ratio, value)
mutate_counter <- function(counter) .Call(wrap__mutate_counter, counter)
normalize <- function(input, factor) .Call(wrap__normalize, input, factor)
peak_level <- function(values) .Call(wrap__peak_level, values)
sample_ids <- function(ids) .Call(wrap__sample_ids, ids)
scale_optional <- function(factor) .Call(wrap__scale_optional, factor)
set_level <- function(level) .Call(wrap__set_level, level)
stamp <- function(handle, error, register) .Call(wrap__stamp, handle, error, register)
sum_optional <- function(values) .Call(wrap__sum_optional, values)
trim <- function(input) .Call(wrap__trim, input)
Counter <- function(start) .Call(wrap__Counter__new, start)
Counter__value <- function(self) .Call(wrap__Counter__value, self)
Counter__set_value <- function(self, value) .Call(wrap__Counter__set_value, self, value)
`value<-` <- function(x, value) UseMethod("value<-")
`value<-.Counter` <- function(x, value) {
  Counter__set_value(x, value)
  x
}
Counter__absorb <- function(self, other) .Call(wrap__Counter__absorb, self, other)
Counter__at <- function(self, level) .Call(wrap__Counter__at, self, level)
Counter__bump <- function(self, by) .Call(wrap__Counter__bump, self, by)
Counter__bump_all <- function(self, by) .Call(wrap__Counter__bump_all, self, by)
Counter__scale <- function(self, factor) .Call(wrap__Counter__scale, self, factor)

"$.Counter" <- function(x, name) {
  switch(name,
    value = function() Counter__value(x),
    absorb = function(other) Counter__absorb(x, other),
    at = function(level) Counter__at(x, level),
    bump = function(by) Counter__bump(x, by),
    bump_all = function(by) Counter__bump_all(x, by),
    scale = function(factor) Counter__scale(x, factor),
    stop("unknown method ", name)
  )
}
