# Code generated by `cargo soothfast bind gen`. DO NOT EDIT.
describe <- function(label) .Call(wrap__describe, label)
describe_owned <- function(label) .Call(wrap__describe_owned, label)
digest <- function(data) .Call(wrap__digest, data)
fail <- function(message) .Call(wrap__fail, message)
find_counter <- function(start) .Call(wrap__find_counter, start)
greet <- function(name) .Call(wrap__greet, name)
maybe_ratio <- function(value) .Call(wrap__maybe_ratio, value)
normalize <- function(input, factor) .Call(wrap__normalize, input, factor)
peak_level <- function(values) .Call(wrap__peak_level, values)
stamp <- function(handle, error, register) .Call(wrap__stamp, handle, error, register)
trim <- function(input) .Call(wrap__trim, input)
Counter <- function(start) .Call(wrap__Counter__new, start)
Counter__value <- function(self) .Call(wrap__Counter__value, self)
Counter__at <- function(self, level) .Call(wrap__Counter__at, self, level)
Counter__bump <- function(self, by) .Call(wrap__Counter__bump, self, by)
Counter__bump_all <- function(self, by) .Call(wrap__Counter__bump_all, self, by)

"$.Counter" <- function(x, name) {
  switch(name,
    value = function() Counter__value(x),
    at = function(level) Counter__at(x, level),
    bump = function(by) Counter__bump(x, by),
    bump_all = function(by) Counter__bump_all(x, by),
    stop("unknown method ", name)
  )
}
