# Code generated by `cargo soothfast bind gen`. DO NOT EDIT.
digest <- function(data) .Call(wrap__digest, data)
greet <- function(name) .Call(wrap__greet, name)
normalize <- function(input, factor) .Call(wrap__normalize, input, factor)
stamp <- function(handle, error, register) .Call(wrap__stamp, handle, error, register)
trim <- function(input) .Call(wrap__trim, input)
Counter <- function(start) .Call(wrap__Counter__new, start)
Counter__value <- function(self) .Call(wrap__Counter__value, self)
Counter__at <- function(self, level) .Call(wrap__Counter__at, self, level)
Counter__bump <- function(self, by) .Call(wrap__Counter__bump, self, by)
Counter__bump_all <- function(self, by) .Call(wrap__Counter__bump_all, self, by)

"$.Counter" <- function(x, name) {
  switch(name,
    value = function() Counter__value(x),
    at = function(level) Counter__at(x, level),
    bump = function(by) Counter__bump(x, by),
    bump_all = function(by) Counter__bump_all(x, by),
    stop("unknown method ", name)
  )
}
