/* Code generated by `cargo soothfast bind gen`. DO NOT EDIT. */

#ifndef GOSTATS_H
#define GOSTATS_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Which statistic a comparison reads. */
typedef enum gostats_metric {
    GOSTATS_METRIC_MEDIAN = 0,
    GOSTATS_METRIC_MAD = 1,
    GOSTATS_METRIC_MIN = 2,
    GOSTATS_METRIC_MAX = 3,
} gostats_metric;

/* A robust summary of one sample set. */
typedef struct gostats_summary gostats_summary;

/* An owned `f64` sequence. Release it with gostats_f64_array_free. */
typedef struct gostats_f64_array {
    double *data;
    size_t len;
} gostats_f64_array;

void gostats_f64_array_free(gostats_f64_array array);

/* Release a string this library returned. */
void gostats_string_free(char *text);

/* Release a Summary this library returned. */
void gostats_summary_free(gostats_summary *handle);
/* Summarize a sample set. Fails on an empty one, which has no median. */
gostats_summary * gostats_summary_new(const double *samples, size_t samples_len, char **error);
double gostats_summary_median(const gostats_summary *handle);
/* Median absolute deviation, unscaled. */
double gostats_summary_mad(const gostats_summary *handle);
double gostats_summary_min(const gostats_summary *handle);
double gostats_summary_max(const gostats_summary *handle);
/* How far `value` sits from the median, in MAD units. */
double gostats_summary_deviations(const gostats_summary *handle, double value);
/* How far each of `values` sits from the median, in MAD units. */
gostats_f64_array gostats_summary_deviations_all(const gostats_summary *handle, const double *values, size_t values_len);
/* [`Summary::deviations_all`], writing into a caller-owned buffer. */
void gostats_summary_deviations_into(const gostats_summary *handle, const double *values, size_t values_len, double *out, size_t out_len);
/* Read one statistic by name. */
double gostats_summary_get(const gostats_summary *handle, gostats_metric metric);
/* A one-line rendering of the whole summary. */
char * gostats_summary_label(const gostats_summary *handle);
/* Scale every statistic by `factor`. */
void gostats_summary_rescale(gostats_summary *handle, double factor);
/* Parse a comma-separated sample set. */
gostats_summary * gostats_summary_parse(const char *text, char **error);

/* FNV-1a fingerprint of some bytes. */
uint64_t gostats_fingerprint(const uint8_t *bytes, size_t bytes_len);

#ifdef __cplusplus
}
#endif

#endif /* GOSTATS_H */
