// Code generated by `cargo soothfast bind gen`. DO NOT EDIT.

package gostats

/*
#cgo CFLAGS: -I${SRCDIR}
#cgo LDFLAGS: -L${SRCDIR}/target/release -lgostats -Wl,-rpath,${SRCDIR}/target/release
#include "gostats.h"
#include <stdlib.h>
*/
import "C"

import (
	"errors"
	"runtime"
	"unsafe"
)

// goString copies a string this library returned and releases it.
func goString(s *C.char) string {
	defer C.gostats_string_free(s)
	return C.GoString(s)
}

// bufPtr returns a pointer to a slice's backing array, or nil for an empty
// one: taking the address of an empty slice's element panics.
func bufPtr[T any](s []T) *T {
	if len(s) == 0 {
		return nil
	}
	return &s[0]
}

// float64Slice copies a `f64` sequence this library returned and
// releases it.
func float64Slice(arr C.gostats_f64_array) []float64 {
	defer C.gostats_f64_array_free(arr)
	if arr.len == 0 {
		return nil
	}
	out := make([]float64, arr.len)
	copy(out, unsafe.Slice((*float64)(unsafe.Pointer(arr.data)), arr.len))
	return out
}

// Which statistic a comparison reads.
type Metric int32

const (
	MetricMedian Metric = 0
	MetricMad    Metric = 1
	MetricMin    Metric = 2
	MetricMax    Metric = 3
)

// c converts a Metric to the native gostats_metric it mirrors.
func (recv Metric) c() C.gostats_metric {
	return C.gostats_metric(recv)
}

// A robust summary of one sample set.
// Summary wraps a native gostats_summary.
type Summary struct {
	ptr *C.gostats_summary
}

func wrapSummary(ptr *C.gostats_summary) *Summary {
	h := &Summary{ptr: ptr}
	runtime.SetFinalizer(h, (*Summary).Close)
	return h
}

// Close releases the native handle. Calling it twice, or on a
// Summary that was never open, is a no-op.
func (recv *Summary) Close() error {
	if recv.ptr == nil {
		return nil
	}
	C.gostats_summary_free(recv.ptr)
	recv.ptr = nil
	runtime.SetFinalizer(recv, nil)
	return nil
}

// Summarize a sample set. Fails on an empty one, which has no median.
func NewSummary(samples []float64) (*Summary, error) {
	var errPtr *C.char
	ret := C.gostats_summary_new((*C.double)(unsafe.Pointer(bufPtr(samples))), C.size_t(len(samples)), &errPtr)
	if errPtr != nil {
		err := errors.New(goString(errPtr))
		return nil, err
	}
	return wrapSummary(ret), nil
}

func (recv *Summary) Median() float64 {
	return float64(C.gostats_summary_median(recv.ptr))
}

// Median absolute deviation, unscaled.
func (recv *Summary) Mad() float64 {
	return float64(C.gostats_summary_mad(recv.ptr))
}

func (recv *Summary) Min() float64 {
	return float64(C.gostats_summary_min(recv.ptr))
}

func (recv *Summary) Max() float64 {
	return float64(C.gostats_summary_max(recv.ptr))
}

// How far `value` sits from the median, in MAD units.
func (recv *Summary) Deviations(value float64) float64 {
	return float64(C.gostats_summary_deviations(recv.ptr, C.double(value)))
}

// How far each of `values` sits from the median, in MAD units.
func (recv *Summary) DeviationsAll(values []float64) []float64 {
	return float64Slice(C.gostats_summary_deviations_all(recv.ptr, (*C.double)(unsafe.Pointer(bufPtr(values))), C.size_t(len(values))))
}

// [`Summary::deviations_all`], writing into a caller-owned buffer.
func (recv *Summary) DeviationsInto(values []float64, out []float64) {
	C.gostats_summary_deviations_into(recv.ptr, (*C.double)(unsafe.Pointer(bufPtr(values))), C.size_t(len(values)), (*C.double)(unsafe.Pointer(bufPtr(out))), C.size_t(len(out)))
}

// Read one statistic by name.
func (recv *Summary) Get(metric Metric) float64 {
	return float64(C.gostats_summary_get(recv.ptr, metric.c()))
}

// A one-line rendering of the whole summary.
func (recv *Summary) Label() string {
	return goString(C.gostats_summary_label(recv.ptr))
}

// Scale every statistic by `factor`.
func (recv *Summary) Rescale(factor float64) {
	C.gostats_summary_rescale(recv.ptr, C.double(factor))
}

// Parse a comma-separated sample set.
func SummaryParse(text string) (*Summary, error) {
	cText := C.CString(text)
	defer C.free(unsafe.Pointer(cText))
	var errPtr *C.char
	ret := C.gostats_summary_parse(cText, &errPtr)
	if errPtr != nil {
		err := errors.New(goString(errPtr))
		return nil, err
	}
	return wrapSummary(ret), nil
}

// FNV-1a fingerprint of some bytes.
func Fingerprint(bytes []byte) uint64 {
	return uint64(C.gostats_fingerprint((*C.uint8_t)(unsafe.Pointer(bufPtr(bytes))), C.size_t(len(bytes))))
}
