//! The `.csproj` a C# consumer builds against, and the README section
//! describing it.

use std::fmt::Write;

use crate::BindOptions;
use crate::plan::{BindingPlan, Transfer};

use super::types;

/// The generated class library's project file.
///
/// `AllowUnsafeBlocks` is set only when a buffer or a string parameter
/// needs `fixed` to pin it for the call; a surface with neither builds
/// without it. No package references: the transport is `[DllImport]`
/// against the platform's own P/Invoke marshaller.
pub(crate) fn csproj(plan: &BindingPlan, opts: &BindOptions) -> String {
    let mut out = String::from(
        "<!-- Code generated by `cargo soothfast bind gen`. DO NOT EDIT. -->\n\n\
         <Project Sdk=\"Microsoft.NET.Sdk\">\n\n  <PropertyGroup>\n\
         \x20   <TargetFramework>net8.0</TargetFramework>\n",
    );
    let _ = writeln!(out, "    <RootNamespace>{}</RootNamespace>", opts.package);
    let _ = writeln!(out, "    <AssemblyName>{}</AssemblyName>", opts.package);
    let _ = writeln!(out, "    <Version>{}</Version>", opts.version);
    if needs_unsafe(plan) {
        out.push_str("    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>\n");
    }
    if let Some(description) = &opts.description {
        let _ = writeln!(
            out,
            "    <Description>{}</Description>",
            xml_escape(description)
        );
    }
    out.push_str(
        "  </PropertyGroup>\n\n\
         \x20 <ItemGroup>\n\
         \x20   <None Include=\"runtimes/**\" CopyToOutputDirectory=\"PreserveNewest\" \
         Link=\"runtimes/%(RecursiveDir)%(Filename)%(Extension)\" />\n\
         \x20 </ItemGroup>\n\n\
         </Project>\n",
    );
    out
}

/// Whether any call takes a buffer or a string, the only parameters a
/// generated method pins with `fixed`.
fn needs_unsafe(plan: &BindingPlan) -> bool {
    plan.functions().any(|f| {
        f.params.iter().any(|p| {
            matches!(
                Transfer::of(p, plan),
                Transfer::Buffer { .. } | Transfer::Text { .. }
            )
        })
    })
}

fn xml_escape(text: &str) -> String {
    text.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}

pub(crate) fn readme_section(plan: &BindingPlan, opts: &BindOptions) -> String {
    let module_class = types::module_class(&opts.package);
    let mut out = format!(
        "\n## C#\n\n\
         This package also ships a .NET class library (`{}.csproj`, `Native.cs`, plus one \
         `.cs` file per exported type) generated over the same header and library via \
         P/Invoke. Build the native library first, then `dotnet build -c Release`.\n\n\
         A borrowed buffer parameter (`ReadOnlySpan<double>`, `Span<byte>`, ...) is pinned \
         with `fixed` for the call: no copy, but the garbage collector cannot run for its \
         length.\n",
        opts.package,
    );
    if plan.functions().any(|f| f.throws.is_some()) {
        let _ = write!(
            out,
            "\nA failing call throws `{}`.\n",
            types::exception_class(&module_class)
        );
    }
    out
}
