// Code generated by `cargo soothfast bind gen`. DO NOT EDIT.
package io.soothfast.stats;

import java.io.IOException;
import java.io.InputStream;
import java.lang.ref.Cleaner;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;

final class Natives {
    static final Cleaner CLEANER = Cleaner.create();

    static {
        String libName = System.mapLibraryName("io_soothfast_stats");
        String resource = "/natives/" + nativeDir() + "/" + libName;
        try (InputStream in = Natives.class.getResourceAsStream(resource)) {
            if (in == null) {
                System.loadLibrary("io_soothfast_stats");
            } else {
                String suffix = libName.contains(".")
                        ? libName.substring(libName.lastIndexOf('.'))
                        : "";
                Path temp = Files.createTempFile("io_soothfast_stats", suffix);
                temp.toFile().deleteOnExit();
                Files.copy(in, temp, StandardCopyOption.REPLACE_EXISTING);
                System.load(temp.toAbsolutePath().toString());
            }
        } catch (IOException e) {
            throw new RuntimeException("failed to load io_soothfast_stats", e);
        }
    }

    /** Touching this forces the block above to run. */
    static void load() {
    }

    private static String nativeDir() {
        String osName = System.getProperty("os.name").toLowerCase();
        String os;
        if (osName.contains("mac")) {
            os = "macos";
        } else if (osName.contains("win")) {
            os = "windows";
        } else {
            os = "linux";
        }
        String archName = System.getProperty("os.arch").toLowerCase();
        String arch = archName.equals("amd64") ? "x86_64" : archName;
        return os + "-" + arch;
    }

    private Natives() {
    }
}
