// Code generated by `cargo soothfast bind gen`. DO NOT EDIT.
package io.soothfast.stats;

/** Thrown for every Stats call that returns an error. */
public final class StatsException extends RuntimeException {
    public StatsException(String message) {
        super(message);
    }
}
