// Code generated by `cargo soothfast bind gen`. DO NOT EDIT.
package io.soothfast.stats;

public final class Stats {
    static {
        Natives.load();
    }

    private Stats() {
    }

    /** FNV-1a fingerprint of some bytes. */
    public static long fingerprint(byte[] bytes) {
        return nativeFingerprint(bytes);
    }

    private static native long nativeFingerprint(byte[] bytes);
}
