// Code generated by `cargo soothfast bind gen`. DO NOT EDIT.
package io.soothfast.stats;

import java.lang.ref.Cleaner;

/** A robust summary of one sample set. */
public final class Summary implements AutoCloseable {
    static {
        Natives.load();
    }

    private final long ptr;
    private final Cleaner.Cleanable cleanable;
    private boolean closed;

    static final class Raw {
        private Raw() {
        }

        static final Raw INSTANCE = new Raw();
    }

    private static final class State implements Runnable {
        private final long ptr;

        State(long ptr) {
            this.ptr = ptr;
        }

        @Override
        public void run() {
            nativeFree(ptr);
        }
    }

    Summary(long ptr, Raw marker) {
        this.ptr = ptr;
        this.cleanable = Natives.CLEANER.register(this, new State(ptr));
    }

    /** The raw handle, readable only from generated code in this package. */
    long nativePtr() {
        if (closed) {
            throw new IllegalStateException("Summary is closed");
        }
        return ptr;
    }

    /** Summarize a sample set. Fails on an empty one, which has no median. */
    public Summary(double[] samples) {
        this(nativeNew(samples), Raw.INSTANCE);
    }

    public double median() {
        return nativeMedian(nativePtr());
    }

    /** Median absolute deviation, unscaled. */
    public double mad() {
        return nativeMad(nativePtr());
    }

    public double min() {
        return nativeMin(nativePtr());
    }

    public double max() {
        return nativeMax(nativePtr());
    }

    /** How far `value` sits from the median, in MAD units. */
    public double deviations(double value) {
        return nativeDeviations(nativePtr(), value);
    }

    /** How far each of `values` sits from the median, in MAD units. */
    public double[] deviationsAll(double[] values) {
        return nativeDeviationsAll(nativePtr(), values);
    }

    /** [`Summary::deviations_all`], writing into a caller-owned buffer. */
    public void deviationsInto(double[] values, double[] out) {
        nativeDeviationsInto(nativePtr(), values, out);
    }

    /** Read one statistic by name. */
    public double get(Metric metric) {
        return nativeGet(nativePtr(), metric.ordinal());
    }

    /** A one-line rendering of the whole summary. */
    public String label() {
        return nativeLabel(nativePtr());
    }

    /** Scale every statistic by `factor`. */
    public void rescale(double factor) {
        nativeRescale(nativePtr(), factor);
    }

    /** Parse a comma-separated sample set. */
    public static Summary parse(String text) {
        return new Summary(nativeParse(text), Summary.Raw.INSTANCE);
    }

    @Override
    public void close() {
        closed = true;
        cleanable.clean();
    }

    private static native long nativeNew(double[] samples);
    private static native double nativeMedian(long ptr);
    private static native double nativeMad(long ptr);
    private static native double nativeMin(long ptr);
    private static native double nativeMax(long ptr);
    private static native double nativeDeviations(long ptr, double value);
    private static native double[] nativeDeviationsAll(long ptr, double[] values);
    private static native void nativeDeviationsInto(long ptr, double[] values, double[] out);
    private static native double nativeGet(long ptr, int metric);
    private static native String nativeLabel(long ptr);
    private static native void nativeRescale(long ptr, double factor);
    private static native long nativeParse(String text);
    private static native void nativeFree(long ptr);
}
