// Code generated by `cargo soothfast bind gen`. DO NOT EDIT.
package acme.core;

public final class Core {
    static {
        Natives.load();
    }

    private Core() {
    }

    public static String describe(String label) {
        return nativeDescribe(label);
    }

    public static String describeOwned(String label) {
        return nativeDescribeOwned(label);
    }

    public static byte[] digest(byte[] data) {
        return nativeDigest(data);
    }

    public static long fail(String message) {
        return nativeFail(message);
    }

    public static Counter findCounter(long start) {
        long ptr_ = nativeFindCounter(start);
        return ptr_ == 0 ? null : new Counter(ptr_, Counter.Raw.INSTANCE);
    }

    public static boolean[] flags(boolean[] values) {
        return nativeFlags(values);
    }

    public static String greet(String name) {
        return nativeGreet(name);
    }

    public static void invertBits(byte[] buf) {
        nativeInvertBits(buf);
    }

    public static boolean isHigh(Level level) {
        return nativeIsHigh(level.ordinal());
    }

    public static long mutateCounter(Counter counter) {
        return nativeMutateCounter(counter.nativePtr());
    }

    public static double[] normalize(double[] input, double factor) {
        return nativeNormalize(input, factor);
    }

    public static Level peakLevel(double[] values) {
        return Level.values()[nativePeakLevel(values)];
    }

    public static long[] sampleIds(long[] ids) {
        return nativeSampleIds(ids);
    }

    public static void scaleInto(double[] values, double factor, double[] out) {
        nativeScaleInto(values, factor, out);
    }

    public static void split(double[] src, double[] lo, double[] hi) {
        nativeSplit(src, lo, hi);
    }

    public static long stamp(long handle, double error, byte[] register) {
        return nativeStamp(handle, error, register);
    }

    public static String version() {
        return nativeVersion();
    }

    private static native String nativeDescribe(String label);
    private static native String nativeDescribeOwned(String label);
    private static native byte[] nativeDigest(byte[] data);
    private static native long nativeFail(String message);
    private static native long nativeFindCounter(long start);
    private static native boolean[] nativeFlags(boolean[] values);
    private static native String nativeGreet(String name);
    private static native void nativeInvertBits(byte[] buf);
    private static native boolean nativeIsHigh(int level);
    private static native long nativeMutateCounter(long counter);
    private static native double[] nativeNormalize(double[] input, double factor);
    private static native int nativePeakLevel(double[] values);
    private static native long[] nativeSampleIds(long[] ids);
    private static native void nativeScaleInto(double[] values, double factor, double[] out);
    private static native void nativeSplit(double[] src, double[] lo, double[] hi);
    private static native long nativeStamp(long handle, double error, byte[] register);
    private static native String nativeVersion();
}
