// Code generated by `cargo soothfast bind gen`. DO NOT EDIT.
package acme.core;

public final class Core {
    static {
        Natives.load();
    }

    private Core() {
    }

    public static byte[] digest(byte[] data) {
        return nativeDigest(data);
    }

    public static String greet(String name) {
        return nativeGreet(name);
    }

    public static double[] normalize(double[] input, double factor) {
        return nativeNormalize(input, factor);
    }

    public static void scaleInto(double[] values, double factor, double[] out) {
        nativeScaleInto(values, factor, out);
    }

    public static long stamp(long handle, double error, byte[] register) {
        return nativeStamp(handle, error, register);
    }

    private static native byte[] nativeDigest(byte[] data);
    private static native String nativeGreet(String name);
    private static native double[] nativeNormalize(double[] input, double factor);
    private static native void nativeScaleInto(double[] values, double factor, double[] out);
    private static native long nativeStamp(long handle, double error, byte[] register);
}
