// Code generated by `cargo soothfast bind gen`. DO NOT EDIT.
package acme.core;

import java.lang.ref.Cleaner;

public final class Mode implements AutoCloseable {
    static {
        Natives.load();
    }

    private final long ptr;
    private final Cleaner.Cleanable cleanable;

    private static final class State implements Runnable {
        private final long ptr;

        State(long ptr) {
            this.ptr = ptr;
        }

        @Override
        public void run() {
            nativeFree(ptr);
        }
    }

    Mode(long ptr) {
        this.ptr = ptr;
        this.cleanable = Natives.CLEANER.register(this, new State(ptr));
    }

    /** The raw handle, readable only from generated code in this package. */
    long nativePtr() {
        return ptr;
    }

    @Override
    public void close() {
        cleanable.clean();
    }

    private static native void nativeFree(long ptr);
}
