//! The glue crate's manifest and the files a Java consumer builds against.

use std::fmt::Write;

use crate::plan::BindingPlan;
use crate::{BindOptions, GENERATED_TOML};

use super::{DEFAULT_VERSION, types};

/// The glue crate's `Cargo.toml`.
///
/// `panic = "abort"` for the same reason the C backend picks it: unwinding
/// past an `extern "system"` boundary is undefined, and a JNI call has no
/// `catch_unwind` translating a panic into a Java exception for it.
pub(crate) fn cargo_toml(opts: &BindOptions) -> String {
    let version = opts.backend_version.as_deref().unwrap_or(DEFAULT_VERSION);
    let lib = types::native_lib_name(&opts.package);
    format!(
        "{GENERATED_TOML}
[package]
name = \"{lib}-jni\"
version = \"{}\"
edition = \"2024\"
publish = false

# Built on its own by the packaging tool, never as a member of whatever
# workspace it is generated inside.
[workspace]

[lib]
name = \"{lib}\"
crate-type = [\"cdylib\"]

[dependencies]
{} = {{ path = \"{}\" }}
jni = \"{version}\"

# Built once and shipped, so build time is worth trading for speed.
# Unwinding past an `extern \"system\"` boundary is undefined, so a panic
# aborts instead.
[profile.release]
lto = true
codegen-units = 1
panic = \"abort\"
",
        opts.version, opts.crate_package, opts.crate_path,
    )
}

pub(crate) fn readme(plan: &BindingPlan, opts: &BindOptions) -> String {
    let lib = types::native_lib_name(&opts.package);
    let module = types::module_class(&opts.package);
    let mut out = format!("# {}\n\n", opts.package);
    if let Some(description) = &opts.description {
        let _ = writeln!(out, "{description}\n");
    }
    let import = format!("{}.{module}", opts.package);
    let _ = write!(
        out,
        "Java bindings for the `{}` crate, generated by \
         [soothfast](https://github.com/Verdenroz/soothfast). Do not edit by hand: \
         run `cargo soothfast bind gen` instead.\n\n\
         ## Build\n\n\
         ```bash\ncargo build --release\n```\n\n\
         That writes `target/release/lib{lib}.so` (`.dylib` on macOS, `{lib}.dll` on \
         Windows). Compile the Java sources against it and put the library on the \
         loader's path:\n\n\
         ```bash\njavac -d out $(find src/main/java -name '*.java')\njar --create --file {lib}.jar -C out .\njava -Djava.library.path=target/release -cp {lib}.jar YourMain\n```\n\n\
         ## Use\n\n\
         ```java\nimport {import};\n```\n\n\
         Every handle class implements `AutoCloseable`; call `close()` (or use \
         try-with-resources) to free it deterministically. A `java.lang.ref.Cleaner` \
         frees one you forgot, but not on any schedule you should rely on.\n\n\
         A borrowed buffer parameter (`double[]`, `byte[]`, ...) is read through \
         `GetPrimitiveArrayCritical`: it crosses without a copy, but the garbage \
         collector cannot run for the length of that one call.\n",
        opts.crate_name,
    );

    if !plan.classes.is_empty() {
        out.push_str("\n## Types\n\n");
        for class in &plan.classes {
            let _ = writeln!(out, "### `{}`\n", class.name);
            if let Some(doc) = &class.doc {
                let _ = writeln!(out, "{doc}\n");
            }
        }
    }
    if !plan.functions.is_empty() {
        let _ = writeln!(out, "## `{module}`\n");
        for function in &plan.functions {
            let _ = writeln!(out, "- `{}`", super::java_ident(&function.name));
        }
        out.push('\n');
    }
    if !plan.gaps.is_empty() {
        out.push_str("## Not bound\n\n");
        for gap in &plan.gaps {
            let _ = writeln!(out, "- {}", gap.explain());
        }
    }
    out
}
