//! The gem layout: the manifest, the `Rakefile`, and the files rb_sys needs
//! to build the extension.

use std::fmt::Write;

use crate::plan::{BindingPlan, Class};
use crate::{BindOptions, GENERATED_RUBY, GENERATED_TOML};

use super::types;
use super::{DEFAULT_VERSION, RB_SYS_VERSION, rb_ident};

/// `spec.summary` is required, so it always gets something; `spec.description`
/// is not, so it only appears when `[[bind]] description` was actually set,
/// the same as every other backend's optional description field.
pub(crate) fn gemspec(opts: &BindOptions) -> String {
    let summary = opts
        .description
        .clone()
        .unwrap_or_else(|| format!("Ruby bindings for the `{}` crate", opts.crate_name));
    let mut out = format!(
        "{GENERATED_RUBY}\nGem::Specification.new do |spec|\n  \
         spec.name = {}\n  spec.version = {}\n  spec.summary = {}\n",
        quote(&opts.package),
        quote(&opts.version),
        quote(&summary),
    );
    if let Some(description) = &opts.description {
        let _ = writeln!(out, "  spec.description = {}", quote(description));
    }
    if let Some(repository) = &opts.repository {
        let _ = writeln!(out, "  spec.homepage = {}", quote(repository));
    }
    let _ = write!(
        out,
        "  spec.authors = []\n  \
         spec.required_ruby_version = \">= 3.1\"\n  \
         spec.files = Dir[\"lib/**/*.rb\", \"ext/**/*.{{rs,toml,rb}}\"]\n  \
         spec.require_paths = [\"lib\"]\n  \
         spec.extensions = [{}]\n  \
         spec.add_dependency \"rb_sys\", \"~> {RB_SYS_VERSION}\"\nend\n",
        quote(&format!("ext/{}/extconf.rb", opts.module)),
    );
    out
}

pub(crate) fn gemfile() -> String {
    format!("{GENERATED_RUBY}\nsource \"https://rubygems.org\"\n\ngemspec\n")
}

/// `RbSys::ExtensionTask` stages the built cdylib at `lib_dir`, the same
/// place [`lib_entry`] requires it from.
pub(crate) fn rakefile(module: &str) -> String {
    format!(
        "{GENERATED_RUBY}\nrequire \"rb_sys/extensiontask\"\n\n\
         task build: :compile\n\n\
         RbSys::ExtensionTask.new(\"{module}\") do |ext|\n  \
         ext.lib_dir = \"lib/{module}\"\nend\n\n\
         task default: :compile\n"
    )
}

pub(crate) fn extconf(module: &str) -> String {
    format!(
        "{GENERATED_RUBY}\nrequire \"rb_sys/mkmf\"\n\n\
         create_rust_makefile(\"{module}/{module}\")\n"
    )
}

pub(crate) fn lib_entry(module: &str) -> String {
    format!("{GENERATED_RUBY}\nrequire_relative \"{module}/{module}\"\n")
}

/// The glue crate's `Cargo.toml`.
///
/// magnus catches a panic at every call it dispatches to Rust, turning it
/// into a fatal Ruby error rather than unwinding past the boundary, so
/// `panic = "abort"` (JNI's and C's choice) would only turn a caught error
/// into a crash instead.
pub(crate) fn cargo_toml(opts: &BindOptions) -> String {
    let version = opts.backend_version.as_deref().unwrap_or(DEFAULT_VERSION);
    format!(
        "{GENERATED_TOML}
[package]
name = \"{}-glue\"
version = \"{}\"
edition = \"2024\"
publish = false

# Built on its own by the packaging tool, never as a member of whatever
# workspace it is generated inside.
[workspace]

[lib]
name = \"{}\"
crate-type = [\"cdylib\"]

[dependencies]
{} = {{ path = \"{}\" }}
magnus = \"{version}\"
rb-sys = \"{RB_SYS_VERSION}\"

[profile.release]
lto = true
codegen-units = 1
",
        opts.module, opts.version, opts.module, opts.crate_package, opts.crate_path,
    )
}

pub(crate) fn readme(plan: &BindingPlan, opts: &BindOptions, module: &str) -> String {
    let mut out = format!("# {}\n\n", opts.package);
    if let Some(description) = &opts.description {
        let _ = writeln!(out, "{description}\n");
    }
    let _ = write!(
        out,
        "Ruby bindings for the `{}` crate, generated by \
         [soothfast](https://github.com/Verdenroz/soothfast). Do not edit by hand: \
         run `cargo soothfast bind gen` instead.\n\n\
         ## Install\n\n```ruby\ngem \"{}\"\n```\n\n\
         ## Use\n\n```ruby\nrequire \"{}\"\n```\n",
        opts.crate_name, opts.package, opts.module,
    );

    let classes: Vec<&Class> = plan.classes.iter().filter(|c| !c.is_plain_enum()).collect();
    if !classes.is_empty() {
        out.push_str("\n## Classes\n\n");
        for class in classes {
            let _ = writeln!(out, "### `{module}::{}`\n", class.name);
            if let Some(doc) = &class.doc {
                let _ = writeln!(out, "{doc}\n");
            }
            for method in class.methods.iter().chain(class.statics.iter()) {
                let _ = writeln!(out, "- `{}`", rb_ident(&method.name));
            }
            out.push('\n');
        }
    }
    // A plain enum crosses as a validated Symbol, not a class of its own, so
    // it gets no entry above; list its valid values here instead.
    let symbols: Vec<&Class> = plan.classes.iter().filter(|c| c.is_plain_enum()).collect();
    if !symbols.is_empty() {
        out.push_str("## Symbols\n\n");
        for class in symbols {
            let names: Vec<String> = class
                .variants
                .iter()
                .flatten()
                .map(|v| format!(":{}", types::snake(&v.name)))
                .collect();
            let _ = writeln!(out, "- `{}`: one of {}", class.name, names.join(", "));
        }
        out.push('\n');
    }
    if !plan.functions.is_empty() {
        let _ = writeln!(out, "## `{module}`\n");
        for function in &plan.functions {
            let _ = writeln!(out, "- `{}`", rb_ident(&function.name));
        }
        out.push('\n');
    }
    if !plan.gaps.is_empty() {
        out.push_str("## Not bound\n\n");
        for gap in &plan.gaps {
            let _ = writeln!(out, "- {}", gap.explain());
        }
    }
    out
}

/// A double-quoted Ruby string literal. JSON string escaping is a subset of
/// Ruby's, so serde_json renders one directly, same as the TOML strings the
/// other backends quote this way.
fn quote(value: &str) -> String {
    serde_json::Value::String(value.to_string()).to_string()
}
