//! Render the package scaffolding: `pyproject.toml`, `README.md`,
//! `__init__.py`.

use std::fmt::Write;

use soothfast_spec::dialect::Info;

use crate::SdkOptions;
use crate::model::Sdk;
use crate::python::HEADER;

pub(crate) fn pyproject(info: &Info, opts: &SdkOptions) -> String {
    let description = opts
        .description
        .clone()
        .or_else(|| info.description.clone())
        .unwrap_or_else(|| format!("Generated client for {}", info.title));
    let mut out = String::new();
    let _ = writeln!(out, "{HEADER}");
    let _ = writeln!(out, "[build-system]");
    let _ = writeln!(out, "requires = [\"hatchling\"]");
    let _ = writeln!(out, "build-backend = \"hatchling.build\"");
    let _ = writeln!(out);
    let _ = writeln!(out, "[project]");
    let _ = writeln!(out, "name = {:?}", opts.package);
    let _ = writeln!(out, "version = {:?}", opts.version);
    let _ = writeln!(out, "description = {description:?}");
    let _ = writeln!(out, "readme = \"README.md\"");
    let _ = writeln!(out, "requires-python = \">=3.10\"");
    let _ = writeln!(out, "dependencies = [\"httpx>=0.27\"]");
    if let Some(repo) = &opts.repository {
        let _ = writeln!(out);
        let _ = writeln!(out, "[project.urls]");
        let _ = writeln!(out, "Repository = {repo:?}");
    }
    let _ = writeln!(out);
    let _ = writeln!(out, "[tool.hatch.build.targets.wheel]");
    let _ = writeln!(out, "packages = [\"src/{}\"]", opts.module);
    out
}

pub(crate) fn readme(info: &Info, sdk: &Sdk, opts: &SdkOptions, base_url: &str) -> String {
    let mut out = String::new();
    let _ = writeln!(
        out,
        "<!-- Code generated by `cargo soothfast sdk gen`. DO NOT EDIT. -->"
    );
    let _ = writeln!(out, "# {}", opts.package);
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "Generated Python client for **{}** ({}), talking to `{base_url}`.",
        info.title, info.version
    );
    let _ = writeln!(out);
    let _ = writeln!(out, "```bash");
    let _ = writeln!(out, "pip install {}", opts.package);
    let _ = writeln!(out, "```");
    let _ = writeln!(out);
    let _ = writeln!(out, "```python");
    let _ = writeln!(out, "from {} import Client", opts.module);
    let _ = writeln!(out);
    let _ = writeln!(out, "with Client() as client:");
    match sdk.methods.first() {
        Some(m) => {
            let _ = writeln!(out, "    result = client.{}(...)", m.name);
        }
        None => {
            let _ = writeln!(out, "    ...");
        }
    }
    let _ = writeln!(out, "```");
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "An `AsyncClient` with the same methods is importable alongside \
         `Client`. Errors raise subclasses of `ApiError`; rate limits retry \
         automatically, honoring `Retry-After`."
    );
    let _ = writeln!(out);
    let _ = writeln!(out, "## Methods");
    let _ = writeln!(out);
    for m in &sdk.methods {
        let doc = m.doc.as_deref().unwrap_or("");
        let _ = writeln!(
            out,
            "- `{}` — `{} {}`{}{}",
            m.name,
            m.http_method,
            m.path,
            if doc.is_empty() { "" } else { ": " },
            doc,
        );
    }
    out
}

pub(crate) fn init(info: &Info, sdk: &Sdk, opts: &SdkOptions) -> String {
    let mut exports: Vec<String> = vec![
        "ApiError".into(),
        "AsyncClient".into(),
        "BadRequestError".into(),
        "Client".into(),
        "NotFoundError".into(),
        "Page".into(),
        "PageInfo".into(),
        "RateLimitError".into(),
        "ServerError".into(),
        "ServiceUnavailableError".into(),
    ];
    let mut model_names: Vec<&str> = sdk.models.iter().map(|m| m.name.as_str()).collect();
    model_names.extend(sdk.aliases.iter().map(|(n, _)| n.as_str()));
    model_names.sort_unstable();
    exports.extend(model_names.iter().map(|n| n.to_string()));
    exports.sort_unstable();

    let mut out = String::new();
    let _ = writeln!(out, "{HEADER}");
    let _ = writeln!(
        out,
        "\"\"\"{} — generated client for {}.\"\"\"",
        opts.package, info.title
    );
    let _ = writeln!(out, "from __future__ import annotations");
    let _ = writeln!(out);
    let _ = writeln!(out, "from ._runtime import (");
    for name in [
        "ApiError",
        "BadRequestError",
        "NotFoundError",
        "Page",
        "PageInfo",
        "RateLimitError",
        "ServerError",
        "ServiceUnavailableError",
    ] {
        let _ = writeln!(out, "    {name},");
    }
    let _ = writeln!(out, ")");
    let _ = writeln!(out, "from .client import AsyncClient, Client");
    if !model_names.is_empty() {
        let _ = writeln!(out, "from .models import (");
        for name in &model_names {
            let _ = writeln!(out, "    {name},");
        }
        let _ = writeln!(out, ")");
    }
    let _ = writeln!(out);
    let _ = writeln!(out, "__version__ = {:?}", opts.version);
    let _ = writeln!(out);
    let _ = writeln!(out, "__all__ = [");
    for name in &exports {
        let _ = writeln!(out, "    {name:?},");
    }
    let _ = writeln!(out, "]");
    out
}
