// Code generated by `cargo soothfast bind gen`. DO NOT EDIT.
// A handle class with no methods never reads the value it holds.
#![allow(dead_code)]

use wasm_bindgen::prelude::*;

struct BindErrorString(::std::string::String);

impl ::std::convert::From<BindErrorString> for ::wasm_bindgen::JsValue {
    fn from(err: BindErrorString) -> ::wasm_bindgen::JsValue {
        ::wasm_bindgen::JsValue::from_str(&::std::string::ToString::to_string(&err.0))
    }
}

#[wasm_bindgen]
pub struct Counter(::acme::Counter);

#[wasm_bindgen]
impl Counter {
    #[wasm_bindgen(constructor)]
    pub fn new(start: i64) -> Self {
        Counter(::acme::Counter::new(start))
    }

    #[wasm_bindgen(getter)]
    pub fn value(&self) -> i64 {
        self.0.value.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_value(&mut self, value: i64) {
        self.0.value = value;
    }

    pub fn at(&self, level: Level) -> i64 {
        self.0.at(level.into())
    }

    pub fn bump(&self, by: i64) -> Result<i64, JsValue> {
        Ok(self.0.bump(by).map_err(BindErrorString)?)
    }

    #[wasm_bindgen(js_name = bumpAll)]
    pub fn bump_all(&self, by: Vec<i64>) -> i64 {
        self.0.bump_all(by)
    }

    pub async fn refresh(&self) -> u32 {
        self.0.refresh().await
    }
}

#[wasm_bindgen]
#[derive(Clone, Copy, PartialEq, Eq)]
pub enum Level {
    Low,
    High,
}

impl ::std::convert::From<::acme::Level> for Level {
    fn from(value: ::acme::Level) -> Self {
        match value {
            ::acme::Level::Low => Level::Low,
            ::acme::Level::High => Level::High,
        }
    }
}

impl ::std::convert::From<Level> for ::acme::Level {
    fn from(value: Level) -> Self {
        match value {
            Level::Low => ::acme::Level::Low,
            Level::High => ::acme::Level::High,
        }
    }
}

#[wasm_bindgen]
pub struct Mode(::acme::Mode);

#[wasm_bindgen]
pub fn digest(data: &[u8]) -> Vec<u8> {
    ::acme::digest(data)
}

#[wasm_bindgen]
pub fn normalize(input: Vec<f64>, factor: f64) -> Vec<f64> {
    ::acme::normalize(input, factor)
}

#[wasm_bindgen]
pub fn stamp(handle: i64, error: f64, register: &[u8]) -> u64 {
    ::acme::stamp(handle, error, register)
}

#[wasm_bindgen]
pub fn trim(input: &[f64]) -> Option<Vec<f64>> {
    ::acme::trim(input)
}
