// Code generated by `cargo soothfast bind gen`. DO NOT EDIT.
// A handle class with no methods never reads the value it holds.
#![allow(dead_code)]

use extendr_api::prelude::*;

#[extendr]
struct Summary(::soothfast_demo::Summary);

#[extendr]
impl Summary {
    fn new(samples: &[f64]) -> ::std::result::Result<Summary, String> {
        let samples = samples.to_vec();
        match ::soothfast_demo::Summary::new(samples) {
            Ok(value) => Ok(Summary(value)),
            Err(reason) => Err(::std::string::ToString::to_string(&reason)),
        }
    }

    fn median(&self) -> f64 {
        self.0.median.clone()
    }

    fn mad(&self) -> f64 {
        self.0.mad.clone()
    }

    fn min(&self) -> f64 {
        self.0.min.clone()
    }

    fn max(&self) -> f64 {
        self.0.max.clone()
    }

    fn deviations(&self, value: f64) -> f64 {
        let __out = self.0.deviations(value);
        __out
    }

    fn deviations_all(&self, values: &[f64]) -> Vec<f64> {
        let __out = self.0.deviations_all(values);
        __out
    }

    fn get(&self, metric: &str) -> ::std::result::Result<f64, String> {
        let metric = {
            type Inner = ::soothfast_demo::Metric;
            match metric {
                "Median" => Inner::Median,
                "Mad" => Inner::Mad,
                "Min" => Inner::Min,
                "Max" => Inner::Max,
                other => return Err(format!("unknown Metric variant: {other}", other = other)),
            }
        };
        let __out = self.0.get(metric);
        Ok(__out)
    }

    fn label(&self) -> String {
        let __out = self.0.label();
        __out
    }

    fn rescale(&mut self, factor: f64) {
        self.0.rescale(factor);
    }

    fn parse(text: &str) -> ::std::result::Result<Summary, String> {
        match ::soothfast_demo::Summary::parse(text) {
            Ok(value) => Ok(Summary(value)),
            Err(reason) => Err(::std::string::ToString::to_string(&reason)),
        }
    }
}

#[extendr]
fn fingerprint(bytes: &[u8]) -> f64 {
    let bytes = bytes.to_vec();
    let __out = ::soothfast_demo::fingerprint(bytes);
    __out as f64
}

extendr_module! {
    mod soothfast_stats;
    impl Summary;
    fn fingerprint;
}
