// Code generated by `cargo soothfast bind gen`. DO NOT EDIT.
// A handle class with no methods never reads the value it holds.
#![allow(dead_code)]

use ::magnus::prelude::*;

static ERROR: ::magnus::value::Lazy<::magnus::ExceptionClass> = ::magnus::value::Lazy::new(|ruby| {
    ruby.define_module("SoothfastStats")
        .and_then(|m| m.define_error("Error", ruby.exception_standard_error()))
        .expect("defines SoothfastStats::Error")
});

fn metric_from_symbol(
    ruby: &::magnus::Ruby,
    value: ::magnus::Symbol,
) -> Result<::soothfast_demo::Metric, ::magnus::Error> {
    match value.name()?.as_ref() {
        "median" => Ok(::soothfast_demo::Metric::Median),
        "mad" => Ok(::soothfast_demo::Metric::Mad),
        "min" => Ok(::soothfast_demo::Metric::Min),
        "max" => Ok(::soothfast_demo::Metric::Max),
        other => Err(::magnus::Error::new(
            ruby.exception_arg_error(),
            format!("invalid Metric: :{other}"),
        )),
    }
}

fn metric_to_symbol(ruby: &::magnus::Ruby, value: ::soothfast_demo::Metric) -> ::magnus::Symbol {
    match value {
        ::soothfast_demo::Metric::Median => ruby.to_symbol("median"),
        ::soothfast_demo::Metric::Mad => ruby.to_symbol("mad"),
        ::soothfast_demo::Metric::Min => ruby.to_symbol("min"),
        ::soothfast_demo::Metric::Max => ruby.to_symbol("max"),
    }
}

/// A robust summary of one sample set.
#[::magnus::wrap(class = "SoothfastStats::Summary", free_immediately)]
pub struct Summary(::std::cell::RefCell<::soothfast_demo::Summary>);

impl Summary {
    /// Summarize a sample set. Fails on an empty one, which has no median.
    fn new(ruby: &::magnus::Ruby, samples: Vec<f64>) -> Result<Self, ::magnus::Error> {
        Ok(Summary(::std::cell::RefCell::new(::soothfast_demo::Summary::new(samples).map_err(|reason| ::magnus::Error::new(ruby.get_inner(&ERROR), ::std::string::ToString::to_string(&reason)))?)))
    }

    fn median(&self) -> f64 {
        self.0.borrow().median.clone()
    }

    fn set_median(&self, value: f64) {
        self.0.borrow_mut().median = value;
    }

    /// Median absolute deviation, unscaled.
    fn mad(&self) -> f64 {
        self.0.borrow().mad.clone()
    }

    fn set_mad(&self, value: f64) {
        self.0.borrow_mut().mad = value;
    }

    fn min(&self) -> f64 {
        self.0.borrow().min.clone()
    }

    fn set_min(&self, value: f64) {
        self.0.borrow_mut().min = value;
    }

    fn max(&self) -> f64 {
        self.0.borrow().max.clone()
    }

    fn set_max(&self, value: f64) {
        self.0.borrow_mut().max = value;
    }

    /// How far `value` sits from the median, in MAD units.
    fn deviations(&self, value: f64) -> f64 {
        self.0.borrow().deviations(value)
    }

    /// How far each of `values` sits from the median, in MAD units.
    fn deviations_all(&self, values: Vec<f64>) -> Vec<f64> {
        self.0.borrow().deviations_all(&values)
    }

    /// [`Summary::deviations_all`], writing into a caller-owned buffer.
    fn deviations_into(&self, values: Vec<f64>, out: ::magnus::RArray) -> Result<(), ::magnus::Error> {
        let mut out_vec = out.to_vec::<f64>()?;
        let __out = self.0.borrow().deviations_into(&values, &mut out_vec);
        out_vec.iter().enumerate().try_for_each(|(i, value)| out.store(i as isize, *value))?;
        Ok(__out)
    }

    /// Read one statistic by name.
    fn get(ruby: &::magnus::Ruby, rb_self: &Self, metric: ::magnus::Symbol) -> Result<f64, ::magnus::Error> {
        let metric = metric_from_symbol(ruby, metric)?;
        Ok(rb_self.0.borrow().get(metric))
    }

    /// A one-line rendering of the whole summary.
    fn label(&self) -> String {
        self.0.borrow().label()
    }

    /// Scale every statistic by `factor`.
    fn rescale(&mut self, factor: f64) -> () {
        self.0.borrow_mut().rescale(factor)
    }

    /// Parse a comma-separated sample set.
    fn parse(ruby: &::magnus::Ruby, text: String) -> Result<Summary, ::magnus::Error> {
        Ok(Summary(::std::cell::RefCell::new(::soothfast_demo::Summary::parse(&text).map_err(|reason| ::magnus::Error::new(ruby.get_inner(&ERROR), ::std::string::ToString::to_string(&reason)))?)))
    }
}

/// FNV-1a fingerprint of some bytes.
fn fingerprint(bytes: ::magnus::RString) -> u64 {
    let bytes = unsafe { bytes.as_slice() }.to_vec();
    ::soothfast_demo::fingerprint(bytes)
}

#[::magnus::init]
fn init(ruby: &::magnus::Ruby) -> Result<(), ::magnus::Error> {
    let module = ruby.define_module("SoothfastStats")?;
    ::magnus::value::Lazy::force(&ERROR, ruby);
    let class = module.define_class("Summary", ruby.class_object())?;
    class.define_singleton_method("new", ::magnus::function!(Summary::new, 1))?;
    class.define_method("median", ::magnus::method!(Summary::median, 0))?;
    class.define_method("median=", ::magnus::method!(Summary::set_median, 1))?;
    class.define_method("mad", ::magnus::method!(Summary::mad, 0))?;
    class.define_method("mad=", ::magnus::method!(Summary::set_mad, 1))?;
    class.define_method("min", ::magnus::method!(Summary::min, 0))?;
    class.define_method("min=", ::magnus::method!(Summary::set_min, 1))?;
    class.define_method("max", ::magnus::method!(Summary::max, 0))?;
    class.define_method("max=", ::magnus::method!(Summary::set_max, 1))?;
    class.define_method("deviations", ::magnus::method!(Summary::deviations, 1))?;
    class.define_method("deviations_all", ::magnus::method!(Summary::deviations_all, 1))?;
    class.define_method("deviations_into", ::magnus::method!(Summary::deviations_into, 2))?;
    class.define_method("get", ::magnus::method!(Summary::get, 1))?;
    class.define_method("label", ::magnus::method!(Summary::label, 0))?;
    class.define_method("rescale", ::magnus::method!(Summary::rescale, 1))?;
    class.define_singleton_method("parse", ::magnus::function!(Summary::parse, 1))?;
    module.define_module_function("fingerprint", ::magnus::function!(fingerprint, 1))?;
    Ok(())
}
