// Code generated by `cargo soothfast bind gen`. DO NOT EDIT.
// A handle class with no methods never reads the value it holds.
#![allow(dead_code)]

/// Helpers the shims call. A module rather than bare functions: a parameter
/// named `text` would otherwise shadow the one that reads it.
mod ffi {
pub unsafe fn slice<'a, T>(data: *const T, len: usize) -> &'a [T] {
    match len {
        0 => &[],
        _ => unsafe { ::std::slice::from_raw_parts(data, len) },
    }
}

pub unsafe fn slice_mut<'a, T>(data: *mut T, len: usize) -> &'a mut [T] {
    match len {
        0 => &mut [],
        _ => unsafe { ::std::slice::from_raw_parts_mut(data, len) },
    }
}

pub unsafe fn text<'a>(data: *const ::std::os::raw::c_char) -> &'a str {
    if data.is_null() {
        return "";
    }
    unsafe { ::std::ffi::CStr::from_ptr(data) }.to_str().unwrap_or("")
}

/// Invalid UTF-8 on a non-null pointer yields `Some("")`, matching `text`'s
/// own fallback: only a null pointer means absent.
pub unsafe fn text_opt<'a>(data: *const ::std::os::raw::c_char) -> Option<&'a str> {
    if data.is_null() {
        return None;
    }
    Some(unsafe { ::std::ffi::CStr::from_ptr(data) }.to_str().unwrap_or(""))
}

pub fn into_text(value: String) -> *mut ::std::os::raw::c_char {
    match ::std::ffi::CString::new(value) {
        Ok(text) => text.into_raw(),
        Err(_) => ::std::ptr::null_mut(),
    }
}

pub unsafe fn clear(error: *mut *mut ::std::os::raw::c_char) {
    if !error.is_null() {
        unsafe { *error = ::std::ptr::null_mut() };
    }
}

pub unsafe fn report<E: ::std::fmt::Display>(error: *mut *mut ::std::os::raw::c_char, reason: &E) {
    if !error.is_null() {
        unsafe { *error = into_text(reason.to_string()) };
    }
}
}

/// An owned `f64` sequence. Release it with `soothfast_stats_f64_array_free`.
#[repr(C)]
pub struct SoothfastStatsF64Array {
    data: *mut f64,
    len: usize,
}

impl SoothfastStatsF64Array {
    fn empty() -> Self {
        SoothfastStatsF64Array { data: ::std::ptr::null_mut(), len: 0 }
    }

    fn new(values: Vec<f64>) -> Self {
        let mut boxed = values.into_boxed_slice();
        let out = SoothfastStatsF64Array { data: boxed.as_mut_ptr(), len: boxed.len() };
        ::std::mem::forget(boxed);
        out
    }
}

/// Release a sequence this library returned. Releasing one twice, or one it
/// did not return, is undefined.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn soothfast_stats_f64_array_free(array: SoothfastStatsF64Array) {
    if array.data.is_null() {
        return;
    }
    drop(unsafe {
        Box::from_raw(::std::ptr::slice_from_raw_parts_mut(array.data, array.len))
    });
}

/// Release a string this library returned. Releasing one twice, or one it
/// did not return, is undefined.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn soothfast_stats_string_free(text: *mut ::std::os::raw::c_char) {
    if text.is_null() {
        return;
    }
    drop(unsafe { ::std::ffi::CString::from_raw(text) });
}

/// `Metric`, mirrored as a C enumeration.
#[repr(C)]
#[derive(Clone, Copy, Default, PartialEq, Eq)]
pub enum SoothfastStatsMetric {
    #[default]
    Median,
    Mad,
    Min,
    Max,
}

impl ::std::convert::From<::soothfast_demo::Metric> for SoothfastStatsMetric {
    fn from(value: ::soothfast_demo::Metric) -> Self {
        match value {
            ::soothfast_demo::Metric::Median => SoothfastStatsMetric::Median,
            ::soothfast_demo::Metric::Mad => SoothfastStatsMetric::Mad,
            ::soothfast_demo::Metric::Min => SoothfastStatsMetric::Min,
            ::soothfast_demo::Metric::Max => SoothfastStatsMetric::Max,
        }
    }
}

impl ::std::convert::From<SoothfastStatsMetric> for ::soothfast_demo::Metric {
    fn from(value: SoothfastStatsMetric) -> Self {
        match value {
            SoothfastStatsMetric::Median => ::soothfast_demo::Metric::Median,
            SoothfastStatsMetric::Mad => ::soothfast_demo::Metric::Mad,
            SoothfastStatsMetric::Min => ::soothfast_demo::Metric::Min,
            SoothfastStatsMetric::Max => ::soothfast_demo::Metric::Max,
        }
    }
}

/// Opaque handle to `Summary`.
pub struct SoothfastStatsSummary(::soothfast_demo::Summary);

/// Release a `Summary`. Releasing one twice, or one this library did not return,
/// is undefined.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn soothfast_stats_summary_free(handle: *mut SoothfastStatsSummary) {
    if handle.is_null() {
        return;
    }
    drop(unsafe { Box::from_raw(handle) });
}

/// Summarize a sample set. Fails on an empty one, which has no median.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn soothfast_stats_summary_new(samples: *const f64, samples_len: usize, error: *mut *mut ::std::os::raw::c_char) -> *mut SoothfastStatsSummary {
    match ::soothfast_demo::Summary::new(unsafe { ffi::slice(samples, samples_len) }.to_vec()) {
        Ok(value) => {
            unsafe { ffi::clear(error) };
            Box::into_raw(Box::new(SoothfastStatsSummary(value)))
        }
        Err(reason) => {
            unsafe { ffi::report(error, &reason) };
            ::std::ptr::null_mut()
        }
    }
}

/// Read `median` off a `Summary`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn soothfast_stats_summary_median(handle: *const SoothfastStatsSummary) -> f64 {
    (unsafe { &*handle }).0.median.clone()
}

/// Read `mad` off a `Summary`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn soothfast_stats_summary_mad(handle: *const SoothfastStatsSummary) -> f64 {
    (unsafe { &*handle }).0.mad.clone()
}

/// Read `min` off a `Summary`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn soothfast_stats_summary_min(handle: *const SoothfastStatsSummary) -> f64 {
    (unsafe { &*handle }).0.min.clone()
}

/// Read `max` off a `Summary`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn soothfast_stats_summary_max(handle: *const SoothfastStatsSummary) -> f64 {
    (unsafe { &*handle }).0.max.clone()
}

/// How far `value` sits from the median, in MAD units.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn soothfast_stats_summary_deviations(handle: *const SoothfastStatsSummary, value: f64) -> f64 {
    (unsafe { &*handle }).0.deviations(value)
}

/// How far each of `values` sits from the median, in MAD units.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn soothfast_stats_summary_deviations_all(handle: *const SoothfastStatsSummary, values: *const f64, values_len: usize) -> SoothfastStatsF64Array {
    SoothfastStatsF64Array::new((unsafe { &*handle }).0.deviations_all(unsafe { ffi::slice(values, values_len) }))
}

/// [`Summary::deviations_all`], writing into a caller-owned buffer.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn soothfast_stats_summary_deviations_into(handle: *const SoothfastStatsSummary, values: *const f64, values_len: usize, out: *mut f64, out_len: usize) {
    (unsafe { &*handle }).0.deviations_into(unsafe { ffi::slice(values, values_len) }, unsafe { ffi::slice_mut(out, out_len) })
}

/// Read one statistic by name.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn soothfast_stats_summary_get(handle: *const SoothfastStatsSummary, metric: SoothfastStatsMetric) -> f64 {
    (unsafe { &*handle }).0.get(metric.into())
}

/// A one-line rendering of the whole summary.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn soothfast_stats_summary_label(handle: *const SoothfastStatsSummary) -> *mut ::std::os::raw::c_char {
    ffi::into_text((unsafe { &*handle }).0.label())
}

/// Scale every statistic by `factor`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn soothfast_stats_summary_rescale(handle: *mut SoothfastStatsSummary, factor: f64) {
    (unsafe { &mut *handle }).0.rescale(factor)
}

/// Parse a comma-separated sample set.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn soothfast_stats_summary_parse(text: *const ::std::os::raw::c_char, error: *mut *mut ::std::os::raw::c_char) -> *mut SoothfastStatsSummary {
    match ::soothfast_demo::Summary::parse(unsafe { ffi::text(text) }) {
        Ok(value) => {
            unsafe { ffi::clear(error) };
            Box::into_raw(Box::new(SoothfastStatsSummary(value)))
        }
        Err(reason) => {
            unsafe { ffi::report(error, &reason) };
            ::std::ptr::null_mut()
        }
    }
}

/// FNV-1a fingerprint of some bytes.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn soothfast_stats_fingerprint(bytes: *const u8, bytes_len: usize) -> u64 {
    ::soothfast_demo::fingerprint(unsafe { ffi::slice(bytes, bytes_len) }.to_vec())
}
