# Code generated by `cargo soothfast bind gen`. DO NOT EDIT.

Gem::Specification.new do |spec|
  spec.name = "acme-core"
  spec.version = "0.1.0"
  spec.summary = "Ruby bindings for the `acme` crate"
  spec.authors = []
  spec.required_ruby_version = ">= 3.1"
  spec.files = Dir["lib/**/*.rb", "ext/**/*.{rs,toml,rb}"]
  spec.require_paths = ["lib"]
  spec.extensions = ["ext/acme_core/extconf.rb"]
  spec.add_dependency "rb_sys", "~> 0.9"
end
