// Code generated by `cargo soothfast bind gen`. DO NOT EDIT.
// A handle class with no methods never reads the value it holds.
#![allow(dead_code)]

use napi::bindgen_prelude::*;
use napi_derive::napi;

fn bigint_to_i64(value: ::napi::bindgen_prelude::BigInt, name: &'static str) -> ::napi::Result<i64> {
    let (value, lossless) = value.get_i64();
    match lossless {
        true => Ok(value),
        false => Err(::napi::Error::from_reason(format!("`{name}` does not fit in a 64-bit signed integer"))),
    }
}

fn bigint_to_u64(value: ::napi::bindgen_prelude::BigInt, name: &'static str) -> ::napi::Result<u64> {
    let (negative, value, lossless) = value.get_u64();
    match negative || !lossless {
        true => Err(::napi::Error::from_reason(format!("`{name}` does not fit in a 64-bit unsigned integer"))),
        false => Ok(value),
    }
}

struct BindErrorString(::std::string::String);

impl ::std::convert::From<BindErrorString> for ::napi::Error {
    fn from(err: BindErrorString) -> ::napi::Error {
        ::napi::Error::from_reason(::std::string::ToString::to_string(&err.0))
    }
}

#[napi]
pub struct Counter(::acme::Counter);

#[napi]
impl Counter {
    #[napi(constructor)]
    pub fn new(start: BigInt) -> Result<Self> {
        let start = bigint_to_i64(start, "start")?;
        Ok(Counter(::acme::Counter::new(start)))
    }

    #[napi(getter)]
    pub fn value(&self) -> BigInt {
        BigInt::from(self.0.value.clone())
    }

    #[napi(setter)]
    pub fn set_value(&mut self, value: BigInt) -> Result<()> {
        let value = bigint_to_i64(value, "value")?;
        self.0.value = value;
        Ok(())
    }

    #[napi]
    pub fn absorb(&mut self, other: ClassInstance<'_, Counter>) -> () {
        self.0.absorb(&other.0)
    }

    #[napi]
    pub fn at(&self, level: Level) -> BigInt {
        BigInt::from(self.0.at(level.into()))
    }

    #[napi]
    pub fn bump(&self, by: BigInt) -> Result<BigInt> {
        let by = bigint_to_i64(by, "by")?;
        Ok(BigInt::from(self.0.bump(by).map_err(BindErrorString)?))
    }

    #[napi(js_name = "bumpAll")]
    pub fn bump_all(&self, by: BigInt64Array) -> BigInt {
        BigInt::from(self.0.bump_all(by.to_vec()))
    }

    #[napi]
    pub fn scale(&mut self, factor: BigInt) -> Result<BigInt> {
        let factor = bigint_to_i64(factor, "factor")?;
        Ok(BigInt::from(self.0.scale(factor)))
    }
}

#[napi]
#[derive(Clone, Copy, PartialEq, Eq)]
pub enum Level {
    Low,
    High,
}

impl ::std::convert::From<::acme::Level> for Level {
    fn from(value: ::acme::Level) -> Self {
        match value {
            ::acme::Level::Low => Level::Low,
            ::acme::Level::High => Level::High,
        }
    }
}

// A mirrored enum has no derived `Clone`; a field getter converts through
// this one instead of cloning an owned copy just to consume it.
impl ::std::convert::From<&::acme::Level> for Level {
    fn from(value: &::acme::Level) -> Self {
        match value {
            ::acme::Level::Low => Level::Low,
            ::acme::Level::High => Level::High,
        }
    }
}

impl ::std::convert::From<Level> for ::acme::Level {
    fn from(value: Level) -> Self {
        match value {
            Level::Low => ::acme::Level::Low,
            Level::High => ::acme::Level::High,
        }
    }
}

#[napi]
pub struct Mode(::acme::Mode);

#[napi]
pub fn counters() -> Vec<Counter> {
    ::acme::counters().into_iter().map(Counter).collect()
}

#[napi]
pub fn describe(label: Option<String>) -> Option<String> {
    ::acme::describe(label.as_deref())
}

#[napi(js_name = "describeOwned")]
pub fn describe_owned(label: Option<String>) -> Option<String> {
    ::acme::describe_owned(label)
}

#[napi]
pub fn digest(data: Buffer) -> Buffer {
    Buffer::from(::acme::digest(data.as_ref()))
}

#[napi]
pub fn fail(message: String) -> Result<BigInt> {
    Ok(BigInt::from(::acme::fail(&message).map_err(BindErrorString)?))
}

#[napi(js_name = "findCounter")]
pub fn find_counter(start: BigInt) -> Result<Option<Counter>> {
    let start = bigint_to_i64(start, "start")?;
    Ok(::acme::find_counter(start).map(Counter))
}

#[napi]
pub fn flags(values: Vec<bool>) -> Vec<bool> {
    ::acme::flags(values)
}

#[napi]
pub fn greet(name: String) -> String {
    ::acme::greet(&name)
}

#[napi(js_name = "invertBits")]
pub fn invert_bits(mut buf: Buffer) -> () {
    ::acme::invert_bits(unsafe { buf.as_mut() })
}

#[napi(js_name = "isHigh")]
pub fn is_high(level: Level) -> bool {
    ::acme::is_high(&level.into())
}

#[napi]
pub fn levels() -> Vec<Level> {
    ::acme::levels().into_iter().map(::std::convert::Into::into).collect()
}

#[napi(js_name = "maybeRatio")]
pub fn maybe_ratio(value: f64) -> Option<f64> {
    ::acme::maybe_ratio(value)
}

#[napi(js_name = "mutateCounter")]
pub fn mutate_counter(mut counter: ClassInstance<'_, Counter>) -> BigInt {
    BigInt::from(::acme::mutate_counter(&mut counter.0))
}

#[napi]
pub fn normalize(input: Float64Array, factor: f64) -> Float64Array {
    Float64Array::from(::acme::normalize(input.to_vec(), factor))
}

#[napi(js_name = "peakLevel")]
pub fn peak_level(values: Float64Array) -> Level {
    ::acme::peak_level(values.as_ref()).into()
}

#[napi]
pub fn peek(counter: Option<ClassInstance<'_, Counter>>) -> bool {
    ::acme::peek(counter.as_deref().map(|v| &v.0))
}

#[napi(js_name = "sampleIds")]
pub fn sample_ids(ids: Vec<BigInt>) -> Result<Vec<BigInt>> {
    let ids = ids.into_iter().map(|v| bigint_to_u64(v, "ids").map(|v| v as usize)).collect::<Result<Vec<_>>>()?;
    Ok(::acme::sample_ids(ids).into_iter().map(|v| BigInt::from(v as u64)).collect())
}

#[napi(js_name = "scaleInto")]
pub fn scale_into(values: Float64Array, factor: f64, mut out: Float64Array) -> () {
    ::acme::scale_into(values.as_ref(), factor, unsafe { out.as_mut() })
}

#[napi(js_name = "scaleOptional")]
pub fn scale_optional(factor: Option<f64>) -> f64 {
    ::acme::scale_optional(factor)
}

#[napi(js_name = "setLevel")]
pub fn set_level(level: Option<Level>) -> bool {
    ::acme::set_level(level.map(::std::convert::Into::into))
}

#[napi]
pub fn split(src: Float64Array, mut lo: Float64Array, mut hi: Float64Array) -> () {
    ::acme::split(src.as_ref(), unsafe { lo.as_mut() }, unsafe { hi.as_mut() })
}

#[napi]
pub fn stamp(handle: BigInt, error: f64, register: Buffer) -> Result<BigInt> {
    let handle = bigint_to_i64(handle, "handle")?;
    Ok(BigInt::from(::acme::stamp(handle, error, register.as_ref())))
}

#[napi(js_name = "sumOptional")]
pub fn sum_optional(values: Option<Float64Array>) -> f64 {
    ::acme::sum_optional(values.map(|v| v.to_vec()))
}

#[napi]
pub fn trim(input: Float64Array) -> Option<Float64Array> {
    ::acme::trim(input.as_ref()).map(Float64Array::from)
}

#[napi]
pub fn version() -> String {
    ::acme::version()
}
