// Code generated by `cargo soothfast bind gen`. DO NOT EDIT.
// A handle class with no methods never reads the value it holds.
#![allow(dead_code)]

use napi::bindgen_prelude::*;
use napi_derive::napi;

fn bigint_to_i64(value: ::napi::bindgen_prelude::BigInt, name: &'static str) -> ::napi::Result<i64> {
    let (value, lossless) = value.get_i64();
    match lossless {
        true => Ok(value),
        false => Err(::napi::Error::from_reason(format!("`{name}` does not fit in a 64-bit signed integer"))),
    }
}

fn bigint_to_u64(value: ::napi::bindgen_prelude::BigInt, name: &'static str) -> ::napi::Result<u64> {
    let (negative, value, lossless) = value.get_u64();
    match negative || !lossless {
        true => Err(::napi::Error::from_reason(format!("`{name}` does not fit in a 64-bit unsigned integer"))),
        false => Ok(value),
    }
}

struct BindErrorString(::std::string::String);

impl ::std::convert::From<BindErrorString> for ::napi::Error {
    fn from(err: BindErrorString) -> ::napi::Error {
        ::napi::Error::from_reason(::std::string::ToString::to_string(&err.0))
    }
}

#[napi]
pub struct Counter(::acme::Counter);

#[napi]
impl Counter {
    #[napi(constructor)]
    pub fn new(start: BigInt) -> Result<Self> {
        let start = bigint_to_i64(start, "start")?;
        Ok(Counter(::acme::Counter::new(start)))
    }

    #[napi(getter)]
    pub fn value(&self) -> BigInt {
        BigInt::from(self.0.value.clone())
    }

    #[napi(setter)]
    pub fn set_value(&mut self, value: BigInt) -> Result<()> {
        let value = bigint_to_i64(value, "value")?;
        self.0.value = value;
        Ok(())
    }

    #[napi]
    pub fn at(&self, level: Level) -> BigInt {
        BigInt::from(self.0.at(level.into()))
    }

    #[napi]
    pub fn bump(&self, by: BigInt) -> Result<BigInt> {
        let by = bigint_to_i64(by, "by")?;
        Ok(BigInt::from(self.0.bump(by).map_err(BindErrorString)?))
    }

    #[napi(js_name = "bumpAll")]
    pub fn bump_all(&self, by: BigInt64Array) -> BigInt {
        BigInt::from(self.0.bump_all(by.to_vec()))
    }
}

#[napi]
#[derive(Clone, Copy, PartialEq, Eq)]
pub enum Level {
    Low,
    High,
}

impl ::std::convert::From<::acme::Level> for Level {
    fn from(value: ::acme::Level) -> Self {
        match value {
            ::acme::Level::Low => Level::Low,
            ::acme::Level::High => Level::High,
        }
    }
}

impl ::std::convert::From<Level> for ::acme::Level {
    fn from(value: Level) -> Self {
        match value {
            Level::Low => ::acme::Level::Low,
            Level::High => ::acme::Level::High,
        }
    }
}

#[napi]
pub struct Mode(::acme::Mode);

#[napi]
pub fn digest(data: Buffer) -> Buffer {
    Buffer::from(::acme::digest(data.as_ref()))
}

#[napi]
pub fn greet(name: String) -> String {
    ::acme::greet(&name)
}

#[napi]
pub fn normalize(input: Float64Array, factor: f64) -> Float64Array {
    Float64Array::from(::acme::normalize(input.to_vec(), factor))
}

#[napi]
pub fn stamp(handle: BigInt, error: f64, register: Buffer) -> Result<BigInt> {
    let handle = bigint_to_i64(handle, "handle")?;
    Ok(BigInt::from(::acme::stamp(handle, error, register.as_ref())))
}

#[napi]
pub fn trim(input: Float64Array) -> Option<Float64Array> {
    ::acme::trim(input.as_ref()).map(Float64Array::from)
}
