//! The glue crate's manifest and the Python package around it.

use std::fmt::Write;

use crate::plan::BindingPlan;
use crate::{BindOptions, GENERATED_TOML};

use super::{DEFAULT_VERSION, asyncrt, py_ident};

/// The glue crate's `Cargo.toml`.
///
/// `cdylib` only: nothing in the workspace links this, and an `rlib`
/// alongside it would build the whole crate a second time.
pub(crate) fn cargo_toml(plan: &BindingPlan, opts: &BindOptions) -> String {
    let version = opts.backend_version.as_deref().unwrap_or(DEFAULT_VERSION);
    let features = match plan.has_async() {
        true => "[\"extension-module\", \"experimental-async\"]",
        false => "[\"extension-module\"]",
    };
    format!(
        "{GENERATED_TOML}
[package]
name = \"{}-glue\"
version = \"{}\"
edition = \"2024\"
publish = false

# Built on its own by the packaging tool, never as a member of whatever
# workspace it is generated inside.
[workspace]

[lib]
name = \"{}\"
crate-type = [\"cdylib\"]

[dependencies]
{} = {{ path = \"{}\" }}
pyo3 = {{ version = \"{version}\", features = {features} }}
{}\n# Built once and shipped, so build time is worth trading for speed.\n# `panic = \"abort\"` is deliberately absent: pyo3 turns a panic into a Python\n# exception through `catch_unwind`, which aborting would kill the interpreter\n# instead.\n[profile.release]\nlto = true\ncodegen-units = 1\n",
        opts.package,
        opts.version,
        opts.module,
        opts.crate_package,
        opts.crate_path,
        asyncrt::dependency(plan),
    )
}

/// The Python package metadata maturin builds against.
pub(crate) fn pyproject(opts: &BindOptions) -> String {
    let mut out = format!(
        "{GENERATED_TOML}
[build-system]
requires = [\"maturin>=1.7,<2.0\"]
build-backend = \"maturin\"

[project]
name = \"{}\"
version = \"{}\"
requires-python = \">=3.9\"
",
        opts.package, opts.version,
    );
    if let Some(description) = &opts.description {
        let _ = writeln!(out, "description = {}", quote(description));
    }
    if let Some(repository) = &opts.repository {
        let _ = writeln!(out, "\n[project.urls]\nRepository = {}", quote(repository));
    }
    let _ = write!(
        out,
        "\n[tool.maturin]\nmodule-name = \"{}\"\nfeatures = [\"pyo3/extension-module\"]\n",
        opts.module,
    );
    out
}

pub(crate) fn readme(plan: &BindingPlan, opts: &BindOptions) -> String {
    let mut out = format!("# {}\n\n", opts.package);
    if let Some(description) = &opts.description {
        let _ = writeln!(out, "{description}\n");
    }
    let _ = write!(
        out,
        "Python bindings for the `{}` crate, generated by \
         [soothfast](https://github.com/Verdenroz/soothfast). Do not edit by hand: \
         run `cargo soothfast bind gen` instead.\n\n## Install\n\n```bash\npip install {}\n```\n\n\
         ## Use\n\n```python\nimport {}\n```\n",
        opts.crate_name, opts.package, opts.module,
    );

    if !plan.classes.is_empty() {
        out.push_str("\n## Classes\n\n");
        for class in &plan.classes {
            let _ = writeln!(out, "### `{}`\n", class.name);
            if let Some(doc) = &class.doc {
                let _ = writeln!(out, "{doc}\n");
            }
            for method in class.methods.iter().chain(class.statics.iter()) {
                let _ = writeln!(out, "- `{}`", py_ident(&method.name));
            }
            out.push('\n');
        }
    }
    if !plan.functions.is_empty() {
        out.push_str("## Functions\n\n");
        for function in &plan.functions {
            let _ = writeln!(out, "- `{}`", py_ident(&function.name));
        }
        out.push('\n');
    }
    if !plan.gaps.is_empty() {
        out.push_str("## Not bound\n\n");
        for gap in &plan.gaps {
            let _ = writeln!(out, "- {}", gap.explain());
        }
    }
    out
}

/// A TOML string. JSON string escaping is a subset of TOML's, so serde_json
/// renders one directly.
fn quote(value: &str) -> String {
    serde_json::Value::String(value.to_string()).to_string()
}
