//! The package's `.pyi` stub: every class, member, function and exception
//! the glue registers, spelled with the Python types the glue exposes, so
//! an editor or type checker sees the surface the wheel ships.

use std::fmt::Write;

use crate::BindOptions;
use crate::model::Ty;
use crate::plan::{Accessor, BindingPlan, Class, Function, Transfer};

use super::buffers::{array_name, arrays, buffered};
use super::errors::Hierarchy;
use super::glue::holds_handle;
use super::{blocking, py_ident, repr, seq};

/// Where a type is spelled, which decides what a buffer becomes.
#[derive(Clone, Copy, PartialEq, Eq)]
enum Slot {
    Param,
    Writable,
    Return,
}

/// The stub text. Imports are added only for the names the body uses.
pub(crate) fn render(plan: &BindingPlan, opts: &BindOptions, hierarchy: &Hierarchy) -> String {
    let mut body = String::new();
    for (name, element) in arrays(plan) {
        body.push_str(&array_class(&name, &element));
    }
    for class in seq::classes(plan) {
        body.push_str(&seq_class(class));
    }
    for class in &plan.classes {
        body.push_str(&match class.is_plain_enum() {
            true => enum_class(class),
            false => handle_class(class, plan, opts),
        });
    }
    for (name, parent, fields) in hierarchy.classes() {
        body.push_str(&exception_class(&name, &parent, &fields));
    }
    for function in &plan.functions {
        body.push_str(&free_fn(function, plan, opts));
    }

    let mut imports: Vec<&str> = Vec::new();
    if body.contains("Iterator[") {
        imports.push("Iterator");
    }
    if body.contains("Sequence[") {
        imports.push("Sequence");
    }
    let header = match imports.is_empty() {
        true => String::new(),
        false => format!("from collections.abc import {}\n\n", imports.join(", ")),
    };
    format!("# Code generated by `cargo soothfast bind gen`. DO NOT EDIT.\n\n{header}{body}")
}

fn array_class(name: &str, element: &str) -> String {
    let item = py_scalar(element);
    format!(
        "class {name}:\n    def __len__(self) -> int: ...\n    def __getitem__(self, index: int) -> {item}: ...\n    def __iter__(self) -> Iterator[{item}]: ...\n    def __repr__(self) -> str: ...\n    def tolist(self) -> list[{item}]: ...\n    def __buffer__(self, flags: int, /) -> memoryview: ...\n\n"
    )
}

fn seq_class(class: &Class) -> String {
    let name = seq::name(&class.name);
    let item = &class.name;
    let mut out = format!(
        "class {name}:\n    def __len__(self) -> int: ...\n    def __getitem__(self, index: int) -> {item}: ...\n    def __iter__(self) -> Iterator[{item}]: ...\n    def __repr__(self) -> str: ...\n    def tolist(self) -> list[{item}]: ...\n"
    );
    for accessor in &class.accessors {
        let ty = match &accessor.ty {
            ty if buffered(ty).is_some() => array_name(&Ty::List(Box::new(ty.clone()))),
            Ty::Optional(inner) if buffered(inner).is_some() => {
                Some(format!("list[{} | None]", spell(inner, Slot::Return)))
            }
            Ty::Str => Some("list[str]".into()),
            _ => None,
        };
        if let Some(ty) = ty {
            let _ = write!(
                out,
                "    @property\n    def {}(self) -> {ty}: ...\n",
                py_ident(&accessor.field)
            );
        }
    }
    out.push('\n');
    out
}

fn enum_class(class: &Class) -> String {
    let name = &class.name;
    let mut out = format!("class {name}:\n{}", docstring(class.doc.as_deref(), "    "));
    for variant in class.variants.iter().flatten() {
        let _ = writeln!(out, "    {}: {name}", variant.name);
    }
    out.push_str(
        "    def __eq__(self, other: object) -> bool: ...\n    def __int__(self) -> int: ...\n\n",
    );
    out
}

fn handle_class(class: &Class, plan: &BindingPlan, opts: &BindOptions) -> String {
    let mut out = format!(
        "class {}:\n{}",
        class.name,
        docstring(class.doc.as_deref(), "    ")
    );
    if let Some(ctor) = &class.ctor {
        let _ = write!(
            out,
            "    def __init__(self{}) -> None:{}",
            params(ctor, plan),
            body(ctor.doc.as_deref(), "        ")
        );
    }
    for accessor in &class.accessors {
        out.push_str(&property(accessor, plan));
    }
    if repr::member(class, plan).is_some() {
        out.push_str("    def __repr__(self) -> str: ...\n");
    }
    for method in &class.methods {
        out.push_str(&def(method, plan, opts, "    ", "self"));
    }
    for function in &class.statics {
        out.push_str(&def(function, plan, opts, "    ", ""));
    }
    if class.ctor.is_none()
        && class.accessors.is_empty()
        && class.methods.is_empty()
        && class.statics.is_empty()
        && repr::member(class, plan).is_none()
    {
        out.push_str("    ...\n");
    }
    out.push('\n');
    out
}

/// A field as a property, with a setter exactly when the glue emits one.
fn property(accessor: &Accessor, plan: &BindingPlan) -> String {
    let name = py_ident(&accessor.field);
    let read = match seq::element(&accessor.ty, plan) {
        Some(class) => seq::name(class),
        None => spell(&accessor.ty, Slot::Return),
    };
    let mut out = format!(
        "    @property\n    def {name}(self) -> {read}:{}",
        body(accessor.doc.as_deref(), "        ")
    );
    if !holds_handle(&accessor.ty, plan) {
        let _ = write!(
            out,
            "    @{name}.setter\n    def {name}(self, value: {}) -> None: ...\n",
            spell(&accessor.ty, Slot::Param)
        );
    }
    out
}

fn exception_class(name: &str, parent: &str, fields: &[(String, Ty)]) -> String {
    let mut out = format!("class {name}({parent}):\n");
    for (field, ty) in fields {
        let _ = writeln!(out, "    {}: {}", py_ident(field), spell(ty, Slot::Return));
    }
    if fields.is_empty() {
        out.push_str("    ...\n");
    }
    out.push('\n');
    out
}

fn free_fn(function: &Function, plan: &BindingPlan, opts: &BindOptions) -> String {
    let mut out = def(function, plan, opts, "", "");
    out.push('\n');
    out
}

/// A method, static or free function, followed by its blocking twin when
/// one is emitted.
fn def(
    function: &Function,
    plan: &BindingPlan,
    opts: &BindOptions,
    indent: &str,
    receiver: &str,
) -> String {
    let inner = format!("{indent}    ");
    let decorator = match (receiver.is_empty(), indent.is_empty()) {
        (true, false) => format!("{indent}@staticmethod\n"),
        _ => String::new(),
    };
    let asyncness = if function.is_async { "async " } else { "" };
    let mut out = format!(
        "{decorator}{indent}{asyncness}def {}({receiver}{}) -> {}:{}",
        py_ident(&function.name),
        params_after(function, plan, receiver),
        spell(&function.ret, Slot::Return),
        body(function.doc.as_deref(), &inner),
    );
    if opts.blocking && function.is_async {
        let _ = writeln!(
            out,
            "{decorator}{indent}def {}({receiver}{}) -> {}: ...",
            blocking::name(function),
            params_after(function, plan, receiver),
            spell(&function.ret, Slot::Return),
        );
    }
    out
}

/// The parameter list after a receiver, with its leading comma when there
/// is a receiver to follow.
fn params_after(function: &Function, plan: &BindingPlan, receiver: &str) -> String {
    let list = params(function, plan);
    match receiver.is_empty() {
        true => list.trim_start_matches(", ").to_string(),
        false => list,
    }
}

/// `, name: T` per parameter.
fn params(function: &Function, plan: &BindingPlan) -> String {
    function
        .params
        .iter()
        .map(|p| {
            let slot = match Transfer::of(p, plan) {
                Transfer::Buffer { writable: true, .. } => Slot::Writable,
                _ => Slot::Param,
            };
            format!(", {}: {}", py_ident(&p.name), spell(&p.ty, slot))
        })
        .collect()
}

/// A type as Python spells it in the given slot.
fn spell(ty: &Ty, slot: Slot) -> String {
    match ty {
        Ty::Unit => "None".into(),
        Ty::Bool => "bool".into(),
        Ty::Str | Ty::Text(_) => "str".into(),
        Ty::Bytes => match slot {
            Slot::Writable => "memoryview".into(),
            _ => "bytes".into(),
        },
        Ty::List(inner) => match buffered(inner) {
            Some(element) => match slot {
                Slot::Param => format!("Sequence[{}] | memoryview", py_scalar(element)),
                Slot::Writable => "memoryview".into(),
                Slot::Return => array_name(ty).unwrap_or_default(),
            },
            None => format!("list[{}]", spell(inner, Slot::Return)),
        },
        Ty::Map(key, value) => format!(
            "dict[{}, {}]",
            spell(key, Slot::Return),
            spell(value, Slot::Return)
        ),
        Ty::Optional(inner) => format!("{} | None", spell(inner, slot)),
        Ty::Tuple(items) => format!(
            "tuple[{}]",
            items
                .iter()
                .map(|t| spell(t, Slot::Return))
                .collect::<Vec<_>>()
                .join(", ")
        ),
        Ty::Class(name) => name.clone(),
        Ty::Opaque(_) => "object".into(),
        Ty::F32 | Ty::F64 => "float".into(),
        _ => "int".into(),
    }
}

fn py_scalar(element: &str) -> &'static str {
    match element {
        "f32" | "f64" => "float",
        _ => "int",
    }
}

/// A def's body after its colon: `...` on the same line, or a docstring
/// and then `...` on lines of their own.
fn body(doc: Option<&str>, indent: &str) -> String {
    match doc {
        Some(_) => format!("\n{}{indent}...\n", docstring(doc, indent)),
        None => " ...\n".into(),
    }
}

fn docstring(doc: Option<&str>, indent: &str) -> String {
    match doc {
        Some(text) => format!(
            "{indent}\"\"\"{}\"\"\"\n",
            text.replace('\\', "\\\\").replace('"', "\\\"")
        ),
        None => String::new(),
    }
}
