// Code generated by `cargo soothfast bind gen`. DO NOT EDIT.

#pragma once

#include "core.h"

#include <cstdint>
#include <memory>
#include <optional>
#include <span>
#include <stdexcept>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

namespace acme::core {

class Error : public std::runtime_error {
public:
    explicit Error(const std::string &message) : std::runtime_error(message) {}
};

inline std::string take_string(char *raw) {
    std::string value(raw);
    core_string_free(raw);
    return value;
}

inline std::vector<double> to_vector_f64(core_f64_array arr) {
    std::vector<double> out(arr.data, arr.data + arr.len);
    core_f64_array_free(arr);
    return out;
}

inline std::vector<uint8_t> to_vector_u8(core_u8_array arr) {
    std::vector<uint8_t> out(arr.data, arr.data + arr.len);
    core_u8_array_free(arr);
    return out;
}

enum class Level {
    Low,
    High,
};

class Counter {
public:
    explicit Counter(int64_t start) : handle_(core_counter_new(start)) {}

    // Adopts a pointer another bound call already returned; C++ has no package-private tier to hide this behind.
    explicit Counter(core_counter *raw) : handle_(raw) {}

    core_counter *get() const noexcept { return handle_.get(); }

    int64_t value() const {
        auto raw_result = core_counter_value(handle_.get());
        return raw_result;
    }

    int64_t at(Level level) const {
        auto raw_result = core_counter_at(handle_.get(), static_cast<core_level>(level));
        return raw_result;
    }

    int64_t bump(int64_t by) const {
        char *error = nullptr;
        auto raw_result = core_counter_bump(handle_.get(), by, &error);
        if (error != nullptr) {
            std::string message(error);
            core_string_free(error);
            throw Error(message);
        }
        return raw_result;
    }

    int64_t bump_all(std::span<const int64_t> by) const {
        auto raw_result = core_counter_bump_all(handle_.get(), by.data(), by.size());
        return raw_result;
    }

private:
    struct Deleter {
        void operator()(core_counter *p) const noexcept { core_counter_free(p); }
    };

    std::unique_ptr<core_counter, Deleter> handle_;
};

class Mode {
public:
    // Adopts a pointer another bound call already returned; C++ has no package-private tier to hide this behind.
    explicit Mode(core_mode *raw) : handle_(raw) {}

    core_mode *get() const noexcept { return handle_.get(); }

private:
    struct Deleter {
        void operator()(core_mode *p) const noexcept { core_mode_free(p); }
    };

    std::unique_ptr<core_mode, Deleter> handle_;
};

inline std::optional<std::string> describe(std::optional<std::string_view> label) {
    std::optional<std::string> label_owned;
    if (label) { label_owned.emplace(*label); }
    auto raw_result = core_describe(label_owned ? label_owned->c_str() : nullptr);
    return raw_result != nullptr ? std::optional<std::string>(take_string(raw_result)) : std::nullopt;
}

inline std::optional<std::string> describe_owned(std::optional<std::string_view> label) {
    std::optional<std::string> label_owned;
    if (label) { label_owned.emplace(*label); }
    auto raw_result = core_describe_owned(label_owned ? label_owned->c_str() : nullptr);
    return raw_result != nullptr ? std::optional<std::string>(take_string(raw_result)) : std::nullopt;
}

inline std::vector<uint8_t> digest(std::span<const uint8_t> data) {
    auto raw_result = core_digest(data.data(), data.size());
    return to_vector_u8(raw_result);
}

inline int64_t fail(std::string_view message) {
    std::string message_owned(message);
    char *error = nullptr;
    auto raw_result = core_fail(message_owned.c_str(), &error);
    if (error != nullptr) {
        std::string message(error);
        core_string_free(error);
        throw Error(message);
    }
    return raw_result;
}

inline std::optional<Counter> find_counter(int64_t start) {
    auto raw_result = core_find_counter(start);
    return raw_result != nullptr ? std::optional<Counter>(Counter(raw_result)) : std::nullopt;
}

inline std::string greet(std::string_view name) {
    std::string name_owned(name);
    auto raw_result = core_greet(name_owned.c_str());
    return take_string(raw_result);
}

inline std::vector<double> normalize(std::span<const double> input, double factor) {
    auto raw_result = core_normalize(input.data(), input.size(), factor);
    return to_vector_f64(raw_result);
}

inline Level peak_level(std::span<const double> values) {
    auto raw_result = core_peak_level(values.data(), values.size());
    return static_cast<Level>(raw_result);
}

inline void scale_into(std::span<const double> values, double factor, std::span<double> out) {
    core_scale_into(values.data(), values.size(), factor, out.data(), out.size());
}

inline void split(std::span<const double> src, std::span<double> lo, std::span<double> hi) {
    core_split(src.data(), src.size(), lo.data(), lo.size(), hi.data(), hi.size());
}

inline uint64_t stamp(int64_t handle, double error_, std::span<const uint8_t> register_) {
    auto raw_result = core_stamp(handle, error_, register_.data(), register_.size());
    return raw_result;
}

} // namespace acme::core
