// Code generated by `cargo soothfast bind gen`. DO NOT EDIT.
@file:JvmName("Core")

package acme.core

private val loadNatives: Unit = Natives.load()
private external fun nativeDigest(data: ByteArray): ByteArray
private external fun nativeGreet(name: String): String
private external fun nativeNormalize(input: DoubleArray, factor: Double): DoubleArray
private external fun nativeScaleInto(values: DoubleArray, factor: Double, out: DoubleArray): Unit
private external fun nativeStamp(handle: Long, error: Double, register: ByteArray): Long

fun digest(data: ByteArray): ByteArray {
    return nativeDigest(data)
}

fun greet(name: String): String {
    return nativeGreet(name)
}

fun normalize(input: DoubleArray, factor: Double): DoubleArray {
    return nativeNormalize(input, factor)
}

fun scaleInto(values: DoubleArray, factor: Double, out: DoubleArray) {
    nativeScaleInto(values, factor, out)
}

fun stamp(handle: Long, error: Double, register: ByteArray): Long {
    return nativeStamp(handle, error, register)
}
