// Code generated by `cargo soothfast bind gen`. DO NOT EDIT.
@file:JvmName("Core")

package acme.core

private val loadNatives: Unit = Natives.load()
private external fun nativeDescribe(label: String?): String?
private external fun nativeDigest(data: ByteArray): ByteArray
private external fun nativeFindCounter(start: Long): Long
private external fun nativeGreet(name: String): String
private external fun nativeNormalize(input: DoubleArray, factor: Double): DoubleArray
private external fun nativePeakLevel(values: DoubleArray): Int
private external fun nativeScaleInto(values: DoubleArray, factor: Double, out: DoubleArray): Unit
private external fun nativeStamp(handle: Long, error: Double, register: ByteArray): Long

fun describe(label: String?): String? {
    return nativeDescribe(label)
}

fun digest(data: ByteArray): ByteArray {
    return nativeDigest(data)
}

fun findCounter(start: Long): Counter? {
    val ptr_ = nativeFindCounter(start)
    return if (ptr_ == 0L) null else Counter(ptr_, Counter.Raw)
}

fun greet(name: String): String {
    return nativeGreet(name)
}

fun normalize(input: DoubleArray, factor: Double): DoubleArray {
    return nativeNormalize(input, factor)
}

fun peakLevel(values: DoubleArray): Level {
    return Level.entries[nativePeakLevel(values)]
}

fun scaleInto(values: DoubleArray, factor: Double, out: DoubleArray) {
    nativeScaleInto(values, factor, out)
}

fun stamp(handle: Long, error: Double, register: ByteArray): Long {
    return nativeStamp(handle, error, register)
}
