// Code generated by `cargo soothfast bind gen`. DO NOT EDIT.
package acme.core

import java.lang.ref.Cleaner

class Counter private constructor(private val ptr: Long, marker: Raw) : AutoCloseable {
    companion object {
        init {
            Natives.load()
        }

        @JvmStatic
        private external fun nativeNew(start: Long): Long

        @JvmStatic
        private external fun nativeValue(ptr: Long): Long

        @JvmStatic
        private external fun nativeAt(ptr: Long, level: Int): Long

        @JvmStatic
        private external fun nativeBump(ptr: Long, by: Long): Long

        @JvmStatic
        private external fun nativeBumpAll(ptr: Long, by: LongArray): Long

        @JvmStatic
        private external fun nativeScale(ptr: Long, factor: Long): Long

        @JvmStatic
        private external fun nativeFree(ptr: Long)
    }

    private object Raw

    private val cleanable: Cleaner.Cleanable = Natives.CLEANER.register(this, State(ptr))

    private var closed = false

    internal fun nativePtr(): Long {
        check(!closed) { "Counter is closed" }
        return ptr
    }

    private class State(private val ptr: Long) : Runnable {
        override fun run() {
            nativeFree(ptr)
        }
    }

    constructor(start: Long) : this(nativeNew(start), Raw)

    val value: Long
        get() {
            return nativeValue(nativePtr())
        }

    fun at(level: Level): Long {
        return nativeAt(nativePtr(), level.ordinal)
    }

    fun bump(by: Long): Long {
        return nativeBump(nativePtr(), by)
    }

    fun bumpAll(by: LongArray): Long {
        return nativeBumpAll(nativePtr(), by)
    }

    fun scale(factor: Long): Long {
        return nativeScale(nativePtr(), factor)
    }

    override fun close() {
        closed = true
        cleanable.clean()
    }
}
