// Code generated by `cargo soothfast bind gen`. DO NOT EDIT.
package acme.core

import java.lang.ref.Cleaner

class Mode internal constructor(private val ptr: Long) : AutoCloseable {
    companion object {
        init {
            Natives.load()
        }

        @JvmStatic
        private external fun nativeFree(ptr: Long)
    }

    private val cleanable: Cleaner.Cleanable = Natives.CLEANER.register(this, State(ptr))

    private var closed = false

    internal fun nativePtr(): Long {
        check(!closed) { "Mode is closed" }
        return ptr
    }

    private class State(private val ptr: Long) : Runnable {
        override fun run() {
            nativeFree(ptr)
        }
    }

    override fun close() {
        closed = true
        cleanable.clean()
    }
}
