// Code generated by `cargo soothfast bind gen`. DO NOT EDIT.

#[allow(dead_code)]
fn __throw_unless_pending(env: &mut ::jni::JNIEnv, pending: bool, message: String) {
    if !pending {
        let _ = env.throw_new("java/lang/RuntimeException", message);
    }
}

#[allow(dead_code)]
fn level_to_ordinal(value: ::acme::Level) -> i32 {
    match value {
        ::acme::Level::Low => 0,
        ::acme::Level::High => 1,
    }
}

#[allow(dead_code)]
fn level_from_ordinal(value: i32) -> ::acme::Level {
    match value {
        0 => ::acme::Level::Low,
        1 => ::acme::Level::High,
        _ => unreachable!("Java only ever sends back one of this enum's own ordinals"),
    }
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_acme_core_Counter_nativeNew<'local>(
    _env: ::jni::JNIEnv<'local>,
    _class: ::jni::objects::JClass<'local>,
    start: i64
) -> i64 {
    let __out = ::acme::Counter::new(start);
    Box::into_raw(Box::new(__out)) as i64
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_acme_core_Counter_nativeValue<'local>(
    _env: ::jni::JNIEnv<'local>,
    _class: ::jni::objects::JClass<'local>,
    ptr: i64,
) -> i64 {
    let __out = (unsafe { &*(ptr as *const ::acme::Counter) }).value.clone();
    __out
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_acme_core_Counter_nativeAt<'local>(
    _env: ::jni::JNIEnv<'local>,
    _class: ::jni::objects::JClass<'local>,
    ptr: i64,
    level: i32
) -> i64 {
    let this = unsafe { &*(ptr as *const ::acme::Counter) };
    let level = level_from_ordinal(level);
    let __out = this.at(level);
    __out
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_acme_core_Counter_nativeBump<'local>(
    mut env: ::jni::JNIEnv<'local>,
    _class: ::jni::objects::JClass<'local>,
    ptr: i64,
    by: i64
) -> i64 {
    let this = unsafe { &*(ptr as *const ::acme::Counter) };
    let __out = this.bump(by);
    match __out {
        Ok(value) => {
            value
        }
        Err(reason) => {
            let _ = env.throw_new("acme/core/CoreException", ::std::string::ToString::to_string(&reason));
            0
        }
    }
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_acme_core_Counter_nativeBumpAll<'local>(
    mut env: ::jni::JNIEnv<'local>,
    _class: ::jni::objects::JClass<'local>,
    ptr: i64,
    by: ::jni::objects::JLongArray<'local>
) -> i64 {
    let this = unsafe { &*(ptr as *const ::acme::Counter) };
    let __len = match env.get_array_length(&by) {
        Ok(v) => v as usize,
        Err(e) => {
            let pending = matches!(e, ::jni::errors::Error::JavaException);
            __throw_unless_pending(&mut env, pending, e.to_string());
            return 0;
        }
    };
    let mut __raw = vec![0; __len];
    match env.get_long_array_region(&by, 0, &mut __raw) {
        Ok(()) => {}
        Err(e) => {
            let pending = matches!(e, ::jni::errors::Error::JavaException);
            __throw_unless_pending(&mut env, pending, e.to_string());
            return 0;
        }
    }
    let by: Vec<i64> = __raw;
    let __out = this.bump_all(by);
    __out
}

/// Release a `Counter` this library returned. Releasing one twice, or one
/// this library did not return, is undefined.
#[unsafe(no_mangle)]
pub extern "system" fn Java_acme_core_Counter_nativeFree<'local>(
    _env: ::jni::JNIEnv<'local>,
    _class: ::jni::objects::JClass<'local>,
    ptr: i64,
) {
    drop(unsafe { Box::from_raw(ptr as *mut ::acme::Counter) });
}

/// Release a `Mode` this library returned. Releasing one twice, or one
/// this library did not return, is undefined.
#[unsafe(no_mangle)]
pub extern "system" fn Java_acme_core_Mode_nativeFree<'local>(
    _env: ::jni::JNIEnv<'local>,
    _class: ::jni::objects::JClass<'local>,
    ptr: i64,
) {
    drop(unsafe { Box::from_raw(ptr as *mut ::acme::Mode) });
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_acme_core_Core_nativeDigest<'local>(
    mut env: ::jni::JNIEnv<'local>,
    _class: ::jni::objects::JClass<'local>,
    data: ::jni::objects::JByteArray<'local>
) -> ::jni::sys::jbyteArray {
    let result = unsafe { env.get_array_elements_critical(&data, ::jni::objects::ReleaseMode::NoCopyBack) };
    if let Err(ref e) = result {
        let pending = matches!(e, ::jni::errors::Error::JavaException);
        let message = e.to_string();
        drop(result);
        __throw_unless_pending(&mut env, pending, message);
        return ::std::ptr::null_mut();
    }
    let data_pin = result.unwrap();
    let __out = ::acme::digest(unsafe { ::std::slice::from_raw_parts(data_pin.as_ptr() as *const u8, data_pin.len()) });
    drop(data_pin);
    {
            let __values: Vec<i8> = __out.into_iter().map(|v| v as i8).collect();
            let __arr = match env.new_byte_array(__values.len() as i32) {
                Ok(v) => v,
                Err(e) => {
            let pending = matches!(e, ::jni::errors::Error::JavaException);
            __throw_unless_pending(&mut env, pending, e.to_string());
            return ::std::ptr::null_mut();
        }
            };
            match env.set_byte_array_region(&__arr, 0, &__values) {
                Ok(()) => {}
                Err(e) => {
            let pending = matches!(e, ::jni::errors::Error::JavaException);
            __throw_unless_pending(&mut env, pending, e.to_string());
            return ::std::ptr::null_mut();
        }
            }
            __arr.into_raw()
        }
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_acme_core_Core_nativeGreet<'local>(
    mut env: ::jni::JNIEnv<'local>,
    _class: ::jni::objects::JClass<'local>,
    name: ::jni::objects::JString<'local>
) -> ::jni::sys::jstring {
    let name: String = match env.get_string(&name) {
        Ok(v) => v.into(),
        Err(e) => {
            let pending = matches!(e, ::jni::errors::Error::JavaException);
            __throw_unless_pending(&mut env, pending, e.to_string());
            return ::std::ptr::null_mut();
        }
    };
    let __out = ::acme::greet(&name);
    match env.new_string(__out) {
        Ok(v) => v.into_raw(),
        Err(e) => {
            let pending = matches!(e, ::jni::errors::Error::JavaException);
            __throw_unless_pending(&mut env, pending, e.to_string());
            return ::std::ptr::null_mut();
        }
    }
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_acme_core_Core_nativeNormalize<'local>(
    mut env: ::jni::JNIEnv<'local>,
    _class: ::jni::objects::JClass<'local>,
    input: ::jni::objects::JDoubleArray<'local>,
    factor: f64
) -> ::jni::sys::jdoubleArray {
    let __len = match env.get_array_length(&input) {
        Ok(v) => v as usize,
        Err(e) => {
            let pending = matches!(e, ::jni::errors::Error::JavaException);
            __throw_unless_pending(&mut env, pending, e.to_string());
            return ::std::ptr::null_mut();
        }
    };
    let mut __raw = vec![0.0; __len];
    match env.get_double_array_region(&input, 0, &mut __raw) {
        Ok(()) => {}
        Err(e) => {
            let pending = matches!(e, ::jni::errors::Error::JavaException);
            __throw_unless_pending(&mut env, pending, e.to_string());
            return ::std::ptr::null_mut();
        }
    }
    let input: Vec<f64> = __raw;
    let __out = ::acme::normalize(input, factor);
    {
            let __values: Vec<f64> = __out;
            let __arr = match env.new_double_array(__values.len() as i32) {
                Ok(v) => v,
                Err(e) => {
            let pending = matches!(e, ::jni::errors::Error::JavaException);
            __throw_unless_pending(&mut env, pending, e.to_string());
            return ::std::ptr::null_mut();
        }
            };
            match env.set_double_array_region(&__arr, 0, &__values) {
                Ok(()) => {}
                Err(e) => {
            let pending = matches!(e, ::jni::errors::Error::JavaException);
            __throw_unless_pending(&mut env, pending, e.to_string());
            return ::std::ptr::null_mut();
        }
            }
            __arr.into_raw()
        }
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_acme_core_Core_nativeScaleInto<'local>(
    mut env: ::jni::JNIEnv<'local>,
    _class: ::jni::objects::JClass<'local>,
    values: ::jni::objects::JDoubleArray<'local>,
    factor: f64,
    out: ::jni::objects::JDoubleArray<'local>
) {
    let values: Vec<f64> = {
        let result = unsafe { env.get_array_elements_critical(&values, ::jni::objects::ReleaseMode::NoCopyBack) };
        if let Err(ref e) = result {
        let pending = matches!(e, ::jni::errors::Error::JavaException);
        let message = e.to_string();
        drop(result);
        __throw_unless_pending(&mut env, pending, message);
        return ;
    }
        let guard = result.unwrap();
        guard.to_vec()
    };
    let result = unsafe { env.get_array_elements_critical(&out, ::jni::objects::ReleaseMode::CopyBack) };
    if let Err(ref e) = result {
        let pending = matches!(e, ::jni::errors::Error::JavaException);
        let message = e.to_string();
        drop(result);
        __throw_unless_pending(&mut env, pending, message);
        return ;
    }
    let mut out_pin = result.unwrap();
    ::acme::scale_into(&values, factor, &mut out_pin);
    drop(out_pin);
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_acme_core_Core_nativeStamp<'local>(
    mut env: ::jni::JNIEnv<'local>,
    _class: ::jni::objects::JClass<'local>,
    handle: i64,
    error: f64,
    register: ::jni::objects::JByteArray<'local>
) -> i64 {
    let result = unsafe { env.get_array_elements_critical(&register, ::jni::objects::ReleaseMode::NoCopyBack) };
    if let Err(ref e) = result {
        let pending = matches!(e, ::jni::errors::Error::JavaException);
        let message = e.to_string();
        drop(result);
        __throw_unless_pending(&mut env, pending, message);
        return 0;
    }
    let register_pin = result.unwrap();
    let __out = ::acme::stamp(handle, error, unsafe { ::std::slice::from_raw_parts(register_pin.as_ptr() as *const u8, register_pin.len()) });
    drop(register_pin);
    __out as i64
}
