// Code generated by `cargo soothfast bind gen`. DO NOT EDIT.
// A handle class with no methods never reads the value it holds.
#![allow(dead_code)]

use pyo3::prelude::*;

/// An `f64` sequence read through the buffer protocol when the caller
/// passes a buffer (`array.array`, `memoryview`, numpy), and unboxed element
/// by element only when it is some other sequence.
enum BorrowedF64 {
    Buffer(::pyo3::buffer::PyBuffer<f64>),
    Owned(Vec<f64>),
}

impl<'py> ::pyo3::FromPyObject<'py> for BorrowedF64 {
    fn extract_bound(obj: &::pyo3::Bound<'py, ::pyo3::PyAny>) -> ::pyo3::PyResult<Self> {
        if let Ok(buf) = ::pyo3::buffer::PyBuffer::<f64>::get(obj)
            && buf.is_c_contiguous()
        {
            return Ok(BorrowedF64::Buffer(buf));
        }
        Ok(BorrowedF64::Owned(obj.extract()?))
    }
}

impl BorrowedF64 {
    fn as_slice(&self) -> &[f64] {
        match self {
            // Item type and contiguity were both checked at extraction, so
            // the pointer addresses exactly `item_count` items.
            BorrowedF64::Buffer(b) => unsafe {
                ::std::slice::from_raw_parts(b.buf_ptr() as *const f64, b.item_count())
            },
            BorrowedF64::Owned(v) => v,
        }
    }

    fn into_vec(self) -> Vec<f64> {
        match self {
            BorrowedF64::Buffer(_) => self.as_slice().to_vec(),
            BorrowedF64::Owned(v) => v,
        }
    }
}

/// A borrowed mutable `f64` sequence. Writing back in place needs a
/// real writable buffer, so unlike the read side there is no fallback.
struct BorrowedMutF64(::pyo3::buffer::PyBuffer<f64>);

impl<'py> ::pyo3::FromPyObject<'py> for BorrowedMutF64 {
    fn extract_bound(obj: &::pyo3::Bound<'py, ::pyo3::PyAny>) -> ::pyo3::PyResult<Self> {
        let buf = ::pyo3::buffer::PyBuffer::<f64>::get(obj)?;
        if buf.readonly() {
            return Err(::pyo3::exceptions::PyTypeError::new_err(
                "expected a writable buffer",
            ));
        }
        if !buf.is_c_contiguous() {
            return Err(::pyo3::exceptions::PyTypeError::new_err(
                "expected a contiguous buffer",
            ));
        }
        Ok(BorrowedMutF64(buf))
    }
}

impl BorrowedMutF64 {
    fn as_mut_slice(&mut self) -> &mut [f64] {
        // Writability and contiguity were both checked at extraction, so the
        // pointer addresses exactly `item_count` items and nothing aliases it.
        unsafe {
            ::std::slice::from_raw_parts_mut(self.0.buf_ptr() as *mut f64, self.0.item_count())
        }
    }
}

/// An `u8` sequence read through the buffer protocol when the caller
/// passes a buffer (`array.array`, `memoryview`, numpy), and unboxed element
/// by element only when it is some other sequence.
enum BorrowedU8 {
    Buffer(::pyo3::buffer::PyBuffer<u8>),
    Owned(Vec<u8>),
}

impl<'py> ::pyo3::FromPyObject<'py> for BorrowedU8 {
    fn extract_bound(obj: &::pyo3::Bound<'py, ::pyo3::PyAny>) -> ::pyo3::PyResult<Self> {
        if let Ok(buf) = ::pyo3::buffer::PyBuffer::<u8>::get(obj)
            && buf.is_c_contiguous()
        {
            return Ok(BorrowedU8::Buffer(buf));
        }
        Ok(BorrowedU8::Owned(obj.extract()?))
    }
}

impl BorrowedU8 {
    fn as_slice(&self) -> &[u8] {
        match self {
            // Item type and contiguity were both checked at extraction, so
            // the pointer addresses exactly `item_count` items.
            BorrowedU8::Buffer(b) => unsafe {
                ::std::slice::from_raw_parts(b.buf_ptr() as *const u8, b.item_count())
            },
            BorrowedU8::Owned(v) => v,
        }
    }

    fn into_vec(self) -> Vec<u8> {
        match self {
            BorrowedU8::Buffer(_) => self.as_slice().to_vec(),
            BorrowedU8::Owned(v) => v,
        }
    }
}

/// An owned `f64` sequence. `memoryview(x)` and `numpy.asarray(x)` read
/// it without copying; `x.tolist()` copies it into a plain list.
#[pyclass(name = "F64Array")]
pub struct F64Array(Vec<f64>);

impl F64Array {
    fn new(values: Vec<f64>) -> Self {
        F64Array(values)
    }
}

#[pymethods]
impl F64Array {
    fn __len__(&self) -> usize {
        self.0.len()
    }

    fn __getitem__(&self, index: isize) -> ::pyo3::PyResult<f64> {
        let at = match index < 0 {
            true => index + self.0.len() as isize,
            false => index,
        };
        usize::try_from(at)
            .ok()
            .and_then(|at| self.0.get(at))
            .copied()
            .ok_or_else(|| ::pyo3::exceptions::PyIndexError::new_err("index out of range"))
    }

    fn __iter__<'py>(
        &self,
        py: ::pyo3::Python<'py>,
    ) -> ::pyo3::PyResult<::pyo3::Bound<'py, ::pyo3::PyAny>> {
        use ::pyo3::types::PyAnyMethods;
        Ok(::pyo3::types::PyList::new(py, &self.0)?.try_iter()?.into_any())
    }

    fn __repr__(&self) -> String {
        format!("F64Array({:?})", self.0)
    }

    /// The same values as a plain Python list.
    fn tolist(&self) -> Vec<f64> {
        self.0.clone()
    }

    unsafe fn __getbuffer__(
        slf: ::pyo3::Bound<'_, Self>,
        view: *mut ::pyo3::ffi::Py_buffer,
        flags: ::std::os::raw::c_int,
    ) -> ::pyo3::PyResult<()> {
        if view.is_null() {
            return Err(::pyo3::exceptions::PyBufferError::new_err("view is null"));
        }
        if (flags & ::pyo3::ffi::PyBUF_WRITABLE) == ::pyo3::ffi::PyBUF_WRITABLE {
            return Err(::pyo3::exceptions::PyBufferError::new_err(
                "F64Array is read-only",
            ));
        }
        let size = ::std::mem::size_of::<f64>() as isize;
        let (buf, count) = {
            let values = &slf.borrow().0;
            (values.as_ptr() as *mut ::std::ffi::c_void, values.len() as isize)
        };
        let meta = Box::into_raw(Box::new([count, size]));
        unsafe {
            (*view).obj = slf.into_ptr();
            (*view).buf = buf;
            (*view).len = count * size;
            (*view).readonly = 1;
            (*view).itemsize = size;
            (*view).ndim = 1;
            (*view).format = match (flags & ::pyo3::ffi::PyBUF_FORMAT) == ::pyo3::ffi::PyBUF_FORMAT
            {
                true => c"d".as_ptr() as *mut ::std::os::raw::c_char,
                false => ::std::ptr::null_mut(),
            };
            (*view).shape = match (flags & ::pyo3::ffi::PyBUF_ND) == ::pyo3::ffi::PyBUF_ND {
                true => meta as *mut isize,
                false => ::std::ptr::null_mut(),
            };
            (*view).strides = match (flags & ::pyo3::ffi::PyBUF_STRIDES)
                == ::pyo3::ffi::PyBUF_STRIDES
            {
                true => (meta as *mut isize).add(1),
                false => ::std::ptr::null_mut(),
            };
            (*view).suboffsets = ::std::ptr::null_mut();
            (*view).internal = meta as *mut ::std::ffi::c_void;
        }
        Ok(())
    }

    unsafe fn __releasebuffer__(&self, view: *mut ::pyo3::ffi::Py_buffer) {
        // Paired with the `Box::into_raw` every filled view carries out.
        unsafe { drop(Box::from_raw((*view).internal as *mut [isize; 2])) };
    }
}

struct BindErrorString(::std::string::String);

impl ::std::convert::From<BindErrorString> for ::pyo3::PyErr {
    fn from(err: BindErrorString) -> ::pyo3::PyErr {
        ::pyo3::exceptions::PyRuntimeError::new_err(::std::string::ToString::to_string(&err.0))
    }
}

/// Which statistic a comparison reads.
#[pyclass(name = "Metric", eq, eq_int)]
#[derive(Clone, Copy, PartialEq, Eq)]
pub enum Metric {
    Median,
    Mad,
    Min,
    Max,
}

impl ::std::convert::From<::soothfast_demo::Metric> for Metric {
    fn from(value: ::soothfast_demo::Metric) -> Self {
        match value {
            ::soothfast_demo::Metric::Median => Metric::Median,
            ::soothfast_demo::Metric::Mad => Metric::Mad,
            ::soothfast_demo::Metric::Min => Metric::Min,
            ::soothfast_demo::Metric::Max => Metric::Max,
        }
    }
}

impl ::std::convert::From<Metric> for ::soothfast_demo::Metric {
    fn from(value: Metric) -> Self {
        match value {
            Metric::Median => ::soothfast_demo::Metric::Median,
            Metric::Mad => ::soothfast_demo::Metric::Mad,
            Metric::Min => ::soothfast_demo::Metric::Min,
            Metric::Max => ::soothfast_demo::Metric::Max,
        }
    }
}

/// A robust summary of one sample set.
#[pyclass(name = "Summary")]
pub struct Summary(::soothfast_demo::Summary);

#[pymethods]
impl Summary {
    /// Summarize a sample set. Fails on an empty one, which has no median.
    #[new]
    fn new(py: Python<'_>, samples: BorrowedF64) -> PyResult<Self> {
        let out = py.detach(|| ::soothfast_demo::Summary::new(samples.into_vec()));
        Ok(Summary(out.map_err(BindErrorString)?))
    }

    #[getter]
    fn median(&self) -> f64 {
        self.0.median.clone()
    }

    #[setter]
    fn set_median(&mut self, value: f64) {
        self.0.median = value;
    }

    /// Median absolute deviation, unscaled.
    #[getter]
    fn mad(&self) -> f64 {
        self.0.mad.clone()
    }

    #[setter]
    fn set_mad(&mut self, value: f64) {
        self.0.mad = value;
    }

    #[getter]
    fn min(&self) -> f64 {
        self.0.min.clone()
    }

    #[setter]
    fn set_min(&mut self, value: f64) {
        self.0.min = value;
    }

    #[getter]
    fn max(&self) -> f64 {
        self.0.max.clone()
    }

    #[setter]
    fn set_max(&mut self, value: f64) {
        self.0.max = value;
    }

    /// How far `value` sits from the median, in MAD units.
    fn deviations(&self, value: f64) -> f64 {
        self.0.deviations(value)
    }

    /// How far each of `values` sits from the median, in MAD units.
    fn deviations_all(&self, py: Python<'_>, values: BorrowedF64) -> F64Array {
        let out = py.detach(|| self.0.deviations_all(values.as_slice()));
        F64Array::new(out)
    }

    /// [`Summary::deviations_all`], writing into a caller-owned buffer.
    fn deviations_into(&self, py: Python<'_>, values: BorrowedF64, mut out: BorrowedMutF64) -> () {
        py.detach(|| self.0.deviations_into(values.as_slice(), out.as_mut_slice()))
    }

    /// Read one statistic by name.
    fn get(&self, metric: Metric) -> f64 {
        self.0.get(metric.into())
    }

    /// A one-line rendering of the whole summary.
    fn label(&self) -> String {
        self.0.label()
    }

    /// Scale every statistic by `factor`.
    fn rescale(&mut self, factor: f64) -> () {
        self.0.rescale(factor)
    }

    /// Parse a comma-separated sample set.
    #[staticmethod]
    fn parse(text: &str) -> PyResult<Summary> {
        Ok(Summary(::soothfast_demo::Summary::parse(text).map_err(BindErrorString)?))
    }
}

/// FNV-1a fingerprint of some bytes.
#[pyfunction]
fn fingerprint(py: Python<'_>, bytes: BorrowedU8) -> u64 {
    py.detach(|| ::soothfast_demo::fingerprint(bytes.into_vec()))
}

#[pymodule]
fn soothfast_stats(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_class::<F64Array>()?;
    m.add_class::<Metric>()?;
    m.add_class::<Summary>()?;
    m.add_function(wrap_pyfunction!(fingerprint, m)?)?;
    Ok(())
}
