/* Code generated by `cargo soothfast bind gen`. DO NOT EDIT. */

#ifndef CORE_H
#define CORE_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct core_counter core_counter;

typedef enum core_level {
    CORE_LEVEL_LOW = 0,
    CORE_LEVEL_HIGH = 1,
} core_level;

typedef struct core_mode core_mode;

/* An owned `f64` sequence. Release it with core_f64_array_free. */
typedef struct core_f64_array {
    double *data;
    size_t len;
} core_f64_array;

void core_f64_array_free(core_f64_array array);

/* An owned `u8` sequence. Release it with core_u8_array_free. */
typedef struct core_u8_array {
    uint8_t *data;
    size_t len;
} core_u8_array;

void core_u8_array_free(core_u8_array array);

/* Release a string this library returned. */
void core_string_free(char *text);

/* Release a Counter this library returned. */
void core_counter_free(core_counter *handle);
core_counter * core_counter_new(int64_t start);
int64_t core_counter_value(const core_counter *handle);
int64_t core_counter_at(const core_counter *handle, core_level level);
int64_t core_counter_bump(const core_counter *handle, int64_t by, char **error);
int64_t core_counter_bump_all(const core_counter *handle, const int64_t *by, size_t by_len);

/* Release a Mode this library returned. */
void core_mode_free(core_mode *handle);

core_u8_array core_digest(const uint8_t *data, size_t data_len);
core_f64_array core_normalize(const double *input, size_t input_len, double factor);
uint64_t core_stamp(int64_t handle_, double error_, const uint8_t *register_, size_t register__len);

#ifdef __cplusplus
}
#endif

#endif /* CORE_H */
