// Code generated by `cargo soothfast bind gen`. DO NOT EDIT.

package core

/*
#cgo CFLAGS: -I${SRCDIR}
#cgo LDFLAGS: -L${SRCDIR}/target/release -lcore -Wl,-rpath,${SRCDIR}/target/release
#include "core.h"
#include <stdlib.h>
*/
import "C"

import (
	"errors"
	"runtime"
	"unsafe"
)

// goString copies a string this library returned and releases it.
func goString(s *C.char) string {
	defer C.core_string_free(s)
	return C.GoString(s)
}

// bufPtr returns a pointer to a slice's backing array, or nil for an empty
// one: taking the address of an empty slice's element panics.
func bufPtr[T any](s []T) *T {
	if len(s) == 0 {
		return nil
	}
	return &s[0]
}

// boolSlice copies a `bool` sequence this library returned and
// releases it.
func boolSlice(arr C.core_bool_array) []bool {
	defer C.core_bool_array_free(arr)
	if arr.len == 0 {
		return nil
	}
	out := make([]bool, arr.len)
	copy(out, unsafe.Slice((*bool)(unsafe.Pointer(arr.data)), arr.len))
	return out
}

// float64Slice copies a `f64` sequence this library returned and
// releases it.
func float64Slice(arr C.core_f64_array) []float64 {
	defer C.core_f64_array_free(arr)
	if arr.len == 0 {
		return nil
	}
	out := make([]float64, arr.len)
	copy(out, unsafe.Slice((*float64)(unsafe.Pointer(arr.data)), arr.len))
	return out
}

// byteSlice copies a `u8` sequence this library returned and
// releases it.
func byteSlice(arr C.core_u8_array) []byte {
	defer C.core_u8_array_free(arr)
	if arr.len == 0 {
		return nil
	}
	out := make([]byte, arr.len)
	copy(out, unsafe.Slice((*byte)(unsafe.Pointer(arr.data)), arr.len))
	return out
}

// Counter wraps a native core_counter.
type Counter struct {
	ptr *C.core_counter
}

func wrapCounter(ptr *C.core_counter) *Counter {
	h := &Counter{ptr: ptr}
	runtime.SetFinalizer(h, (*Counter).Close)
	return h
}

// Close releases the native handle. Calling it twice, or on a
// Counter that was never open, is a no-op.
func (recv *Counter) Close() error {
	if recv.ptr == nil {
		return nil
	}
	C.core_counter_free(recv.ptr)
	recv.ptr = nil
	runtime.SetFinalizer(recv, nil)
	return nil
}

func NewCounter(start int64) *Counter {
	return wrapCounter(C.core_counter_new(C.int64_t(start)))
}

func (recv *Counter) Value() int64 {
	if recv.ptr == nil {
		panic("Counter is closed")
	}
	return int64(C.core_counter_value(recv.ptr))
}

func (recv *Counter) Absorb(other *Counter) {
	if recv.ptr == nil {
		panic("Counter is closed")
	}
	C.core_counter_absorb(recv.ptr, other.ptr)
}

func (recv *Counter) At(level Level) int64 {
	if recv.ptr == nil {
		panic("Counter is closed")
	}
	return int64(C.core_counter_at(recv.ptr, level.c()))
}

func (recv *Counter) Bump(by int64) (int64, error) {
	if recv.ptr == nil {
		panic("Counter is closed")
	}
	var errPtr *C.char
	ret := C.core_counter_bump(recv.ptr, C.int64_t(by), &errPtr)
	if errPtr != nil {
		err := errors.New(goString(errPtr))
		return 0, err
	}
	return int64(ret), nil
}

func (recv *Counter) BumpAll(by []int64) int64 {
	if recv.ptr == nil {
		panic("Counter is closed")
	}
	return int64(C.core_counter_bump_all(recv.ptr, (*C.int64_t)(unsafe.Pointer(bufPtr(by))), C.size_t(len(by))))
}

func (recv *Counter) Scale(factor int64) int64 {
	if recv.ptr == nil {
		panic("Counter is closed")
	}
	return int64(C.core_counter_scale(recv.ptr, C.int64_t(factor)))
}

type Level int32

const (
	LevelLow  Level = 0
	LevelHigh Level = 1
)

// c converts a Level to the native core_level it mirrors.
func (recv Level) c() C.core_level {
	return C.core_level(recv)
}

// Mode wraps a native core_mode.
type Mode struct {
	ptr *C.core_mode
}

func wrapMode(ptr *C.core_mode) *Mode {
	h := &Mode{ptr: ptr}
	runtime.SetFinalizer(h, (*Mode).Close)
	return h
}

// Close releases the native handle. Calling it twice, or on a
// Mode that was never open, is a no-op.
func (recv *Mode) Close() error {
	if recv.ptr == nil {
		return nil
	}
	C.core_mode_free(recv.ptr)
	recv.ptr = nil
	runtime.SetFinalizer(recv, nil)
	return nil
}

func Describe(label *string) *string {
	var cLabel *C.char
	if label != nil {
		cLabel = C.CString(*label)
		defer C.free(unsafe.Pointer(cLabel))
	}
	return func() *string {
		if p := C.core_describe(cLabel); p != nil {
			v := goString(p)
			return &v
		}
		return nil
	}()
}

func DescribeOwned(label *string) *string {
	var cLabel *C.char
	if label != nil {
		cLabel = C.CString(*label)
		defer C.free(unsafe.Pointer(cLabel))
	}
	return func() *string {
		if p := C.core_describe_owned(cLabel); p != nil {
			v := goString(p)
			return &v
		}
		return nil
	}()
}

func Digest(data []byte) []byte {
	return byteSlice(C.core_digest((*C.uint8_t)(unsafe.Pointer(bufPtr(data))), C.size_t(len(data))))
}

func Fail(message string) (int64, error) {
	cMessage := C.CString(message)
	defer C.free(unsafe.Pointer(cMessage))
	var errPtr *C.char
	ret := C.core_fail(cMessage, &errPtr)
	if errPtr != nil {
		err := errors.New(goString(errPtr))
		return 0, err
	}
	return int64(ret), nil
}

func FindCounter(start int64) *Counter {
	return func() *Counter {
		if p := C.core_find_counter(C.int64_t(start)); p != nil {
			return wrapCounter(p)
		}
		return nil
	}()
}

func Flags(values []bool) []bool {
	return boolSlice(C.core_flags((*C.bool)(unsafe.Pointer(bufPtr(values))), C.size_t(len(values))))
}

func Greet(name string) string {
	cName := C.CString(name)
	defer C.free(unsafe.Pointer(cName))
	return goString(C.core_greet(cName))
}

func IsHigh(level Level) bool {
	return bool(C.core_is_high(level.c()))
}

func MutateCounter(counter *Counter) int64 {
	return int64(C.core_mutate_counter(counter.ptr))
}

func Normalize(input []float64, factor float64) []float64 {
	return float64Slice(C.core_normalize((*C.double)(unsafe.Pointer(bufPtr(input))), C.size_t(len(input)), C.double(factor)))
}

func PeakLevel(values []float64) Level {
	return Level(C.core_peak_level((*C.double)(unsafe.Pointer(bufPtr(values))), C.size_t(len(values))))
}

func ScaleInto(values []float64, factor float64, out []float64) {
	C.core_scale_into((*C.double)(unsafe.Pointer(bufPtr(values))), C.size_t(len(values)), C.double(factor), (*C.double)(unsafe.Pointer(bufPtr(out))), C.size_t(len(out)))
}

func Split(src []float64, lo []float64, hi []float64) {
	C.core_split((*C.double)(unsafe.Pointer(bufPtr(src))), C.size_t(len(src)), (*C.double)(unsafe.Pointer(bufPtr(lo))), C.size_t(len(lo)), (*C.double)(unsafe.Pointer(bufPtr(hi))), C.size_t(len(hi)))
}

func Stamp(handle int64, error_ float64, register []byte) uint64 {
	return uint64(C.core_stamp(C.int64_t(handle), C.double(error_), (*C.uint8_t)(unsafe.Pointer(bufPtr(register))), C.size_t(len(register))))
}
