// Code generated by `cargo soothfast bind gen`. DO NOT EDIT.
// A handle class with no methods never reads the value it holds.
#![allow(dead_code)]

use wasm_bindgen::prelude::*;

struct BindErrorString(::std::string::String);

impl ::std::convert::From<BindErrorString> for ::wasm_bindgen::JsValue {
    fn from(err: BindErrorString) -> ::wasm_bindgen::JsValue {
        ::wasm_bindgen::JsValue::from_str(&::std::string::ToString::to_string(&err.0))
    }
}

/// Which statistic a comparison reads.
#[wasm_bindgen]
#[derive(Clone, Copy, PartialEq, Eq)]
pub enum Metric {
    Median,
    Mad,
    Min,
    Max,
}

impl ::std::convert::From<::soothfast_demo::Metric> for Metric {
    fn from(value: ::soothfast_demo::Metric) -> Self {
        match value {
            ::soothfast_demo::Metric::Median => Metric::Median,
            ::soothfast_demo::Metric::Mad => Metric::Mad,
            ::soothfast_demo::Metric::Min => Metric::Min,
            ::soothfast_demo::Metric::Max => Metric::Max,
        }
    }
}

impl ::std::convert::From<Metric> for ::soothfast_demo::Metric {
    fn from(value: Metric) -> Self {
        match value {
            Metric::Median => ::soothfast_demo::Metric::Median,
            Metric::Mad => ::soothfast_demo::Metric::Mad,
            Metric::Min => ::soothfast_demo::Metric::Min,
            Metric::Max => ::soothfast_demo::Metric::Max,
        }
    }
}

/// A robust summary of one sample set.
#[wasm_bindgen]
pub struct Summary(::soothfast_demo::Summary);

#[wasm_bindgen]
impl Summary {
    /// Summarize a sample set. Fails on an empty one, which has no median.
    #[wasm_bindgen(constructor)]
    pub fn new(samples: Vec<f64>) -> Result<Self, JsValue> {
        Ok(Summary(::soothfast_demo::Summary::new(samples).map_err(BindErrorString)?))
    }

    #[wasm_bindgen(getter)]
    pub fn median(&self) -> f64 {
        self.0.median.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_median(&mut self, value: f64) {
        self.0.median = value;
    }

    /// Median absolute deviation, unscaled.
    #[wasm_bindgen(getter)]
    pub fn mad(&self) -> f64 {
        self.0.mad.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_mad(&mut self, value: f64) {
        self.0.mad = value;
    }

    #[wasm_bindgen(getter)]
    pub fn min(&self) -> f64 {
        self.0.min.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_min(&mut self, value: f64) {
        self.0.min = value;
    }

    #[wasm_bindgen(getter)]
    pub fn max(&self) -> f64 {
        self.0.max.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_max(&mut self, value: f64) {
        self.0.max = value;
    }

    /// How far `value` sits from the median, in MAD units.
    pub fn deviations(&self, value: f64) -> f64 {
        self.0.deviations(value)
    }

    /// How far each of `values` sits from the median, in MAD units.
    #[wasm_bindgen(js_name = deviationsAll)]
    pub fn deviations_all(&self, values: &[f64]) -> Vec<f64> {
        self.0.deviations_all(values)
    }

    /// [`Summary::deviations_all`], writing into a caller-owned buffer.
    #[wasm_bindgen(js_name = deviationsInto)]
    pub fn deviations_into(&self, values: &[f64], out: &mut [f64]) -> () {
        self.0.deviations_into(values, out)
    }

    /// Read one statistic by name.
    pub fn get(&self, metric: Metric) -> f64 {
        self.0.get(metric.into())
    }

    /// A one-line rendering of the whole summary.
    pub fn label(&self) -> String {
        self.0.label()
    }

    /// Scale every statistic by `factor`.
    pub fn rescale(&mut self, factor: f64) -> () {
        self.0.rescale(factor)
    }

    /// Parse a comma-separated sample set.
    pub fn parse(text: &str) -> Result<Summary, JsValue> {
        Ok(Summary(::soothfast_demo::Summary::parse(text).map_err(BindErrorString)?))
    }
}

/// FNV-1a fingerprint of some bytes.
#[wasm_bindgen]
pub fn fingerprint(bytes: Vec<u8>) -> u64 {
    ::soothfast_demo::fingerprint(bytes)
}
