//! The public header.
//!
//! Declares exactly what the glue crate exports, in the order a reader wants
//! it: the types first, then the calls that release them, then the surface.
//! Both files take every spelling from [`super::types`], so neither can
//! describe an ABI the other does not.

use std::fmt::Write;

use crate::BindOptions;
use crate::model::{Param, Receiver, Ty};
use crate::plan::{Accessor, BindingPlan, Class, Function, Transfer};

use super::glue::{arrays, returns_text};
use super::types::{self, array_c, handle_c};

/// Render the header.
pub(crate) fn render(plan: &BindingPlan, opts: &BindOptions) -> String {
    let module = &opts.module;
    let guard = module.to_uppercase();
    let mut out = format!(
        "/* Code generated by `cargo soothfast bind gen`. DO NOT EDIT. */\n\n\
         #ifndef {guard}_H\n#define {guard}_H\n\n\
         #include <stdbool.h>\n#include <stddef.h>\n#include <stdint.h>\n\n\
         #ifdef __cplusplus\nextern \"C\" {{\n#endif\n"
    );

    for class in &plan.classes {
        out.push_str(&declare_type(class, module));
    }
    for (ty, element) in arrays(plan) {
        out.push_str(&declare_array(&ty, &element, module));
    }
    if returns_text(plan) {
        let _ = write!(
            out,
            "\n/* Release a string this library returned. */\nvoid {module}_string_free(char *text);\n"
        );
    }
    for class in &plan.classes {
        out.push_str(&class_block(class, plan, module));
    }
    if !plan.functions.is_empty() {
        out.push('\n');
        for function in &plan.functions {
            out.push_str(&declare(function, None, plan, module));
        }
    }

    let _ = write!(
        out,
        "\n#ifdef __cplusplus\n}}\n#endif\n\n#endif /* {guard}_H */\n"
    );
    out
}

/// An exported type: a C enumeration when it mirrors, an opaque struct
/// otherwise.
fn declare_type(class: &Class, module: &str) -> String {
    let name = handle_c(&class.name, module);
    if !class.is_plain_enum() {
        return format!(
            "\n{}typedef struct {name} {name};\n",
            comment(class.doc.as_deref(), "")
        );
    }
    let variants: String = class
        .variants
        .iter()
        .flatten()
        .enumerate()
        .map(|(i, v)| {
            format!(
                "    {}_{} = {i},\n",
                name.to_uppercase(),
                types::snake(&v.name).to_uppercase()
            )
        })
        .collect();
    format!(
        "\n{}typedef enum {name} {{\n{variants}}} {name};\n",
        comment(class.doc.as_deref(), "")
    )
}

/// The struct a returned sequence comes back in, and the call releasing it.
fn declare_array(ty: &Ty, element: &str, module: &str) -> String {
    let name = array_c(ty, module);
    let c = types::element(ty).map(|s| s.c).unwrap_or_default();
    format!(
        "\n/* An owned `{element}` sequence. Release it with {name}_free. */\n\
         typedef struct {name} {{\n    {c} *data;\n    size_t len;\n}} {name};\n\n\
         void {name}_free({name} array);\n"
    )
}

fn class_block(class: &Class, plan: &BindingPlan, module: &str) -> String {
    if class.is_plain_enum() {
        return String::new();
    }
    let name = handle_c(&class.name, module);
    let mut out = format!(
        "\n/* Release a {} this library returned. */\nvoid {name}_free({name} *handle);\n",
        class.name
    );
    if let Some(ctor) = &class.ctor {
        out.push_str(&declare(ctor, Some(class), plan, module));
    }
    for accessor in &class.accessors {
        out.push_str(&declare_getter(accessor, class, plan, module));
    }
    for function in class.methods.iter().chain(class.statics.iter()) {
        out.push_str(&declare(function, Some(class), plan, module));
    }
    out
}

fn declare_getter(accessor: &Accessor, class: &Class, plan: &BindingPlan, module: &str) -> String {
    let handle = handle_c(&class.name, module);
    format!(
        "{}{} {handle}_{}(const {handle} *handle);\n",
        comment(accessor.doc.as_deref(), ""),
        returned_c(&accessor.ty, plan, module),
        types::snake(&accessor.field),
    )
}

/// One call, as C declares it.
fn declare(function: &Function, owner: Option<&Class>, plan: &BindingPlan, module: &str) -> String {
    let args = match arguments(function, owner, plan, module) {
        args if args.is_empty() => "void".to_string(),
        args => args.join(", "),
    };
    format!(
        "{}{} {}({args});\n",
        comment(function.doc.as_deref(), ""),
        returned_c(&function.ret, plan, module),
        function.symbol,
    )
}

fn arguments(
    function: &Function,
    owner: Option<&Class>,
    plan: &BindingPlan,
    module: &str,
) -> Vec<String> {
    let mut out: Vec<String> = Vec::new();
    if let (Some(class), receiver) = (owner, function.receiver)
        && receiver != Receiver::None
    {
        let handle = handle_c(&class.name, module);
        out.push(match receiver {
            Receiver::Exclusive => format!("{handle} *handle"),
            _ => format!("const {handle} *handle"),
        });
    }
    for param in &function.params {
        out.extend(param_decl(param, plan, module));
    }
    if function.throws.is_some() {
        out.push("char **error".to_string());
    }
    out
}

/// One parameter, as the one or two C arguments it takes.
fn param_decl(param: &Param, plan: &BindingPlan, module: &str) -> Vec<String> {
    let name = super::c_ident(&param.name);
    match Transfer::of(param, plan) {
        Transfer::Buffer {
            ref element,
            writable,
            ..
        } => {
            let c = types::scalar(element).map(|s| s.c).unwrap_or_default();
            let head = match writable {
                true => format!("{c} *{name}"),
                false => format!("const {c} *{name}"),
            };
            vec![head, format!("size_t {name}_len")]
        }
        Transfer::Text { .. } => vec![format!("const char *{name}")],
        Transfer::Handle { mirrored: true, .. } => {
            vec![format!("{} {name}", class_name(&param.ty, module))]
        }
        Transfer::Handle { writable, .. } => {
            let handle = class_name(&param.ty, module);
            match writable {
                true => vec![format!("{handle} *{name}")],
                false => vec![format!("const {handle} *{name}")],
            }
        }
        _ => vec![format!(
            "{} {name}",
            types::scalar(&param.ty).map(|s| s.c).unwrap_or_default()
        )],
    }
}

/// A returned type, as C declares it.
fn returned_c(ty: &Ty, plan: &BindingPlan, module: &str) -> String {
    match ty {
        Ty::Unit => "void".into(),
        Ty::Str => "char *".into(),
        Ty::Class(name) if plan.is_mirrored(name) => handle_c(name, module),
        Ty::Class(name) => format!("{} *", handle_c(name, module)),
        Ty::Optional(inner) => match &**inner {
            Ty::Class(name) => format!("{} *", handle_c(name, module)),
            _ => "void".into(),
        },
        ty if types::element(ty).is_some() => array_c(ty, module),
        ty => types::scalar(ty).map(|s| s.c).unwrap_or_default(),
    }
}

/// The C name of an exported type, reached directly or through an `Option`.
fn class_name(ty: &Ty, module: &str) -> String {
    match ty {
        Ty::Class(name) => handle_c(name, module),
        Ty::Optional(inner) => class_name(inner, module),
        _ => String::new(),
    }
}

fn comment(doc: Option<&str>, indent: &str) -> String {
    match doc {
        Some(text) => format!("{indent}/* {text} */\n"),
        None => String::new(),
    }
}
