//! The glue crate's manifest and the files a C consumer builds against.

use std::fmt::Write;

use crate::plan::BindingPlan;
use crate::{BindOptions, GENERATED_TOML};

/// The glue crate's `Cargo.toml`.
///
/// Both library kinds are built: a `cdylib` for anything that loads a shared
/// object at runtime, a `staticlib` for anything that links it in.
pub(crate) fn cargo_toml(opts: &BindOptions) -> String {
    format!(
        "{GENERATED_TOML}
[package]
name = \"{}-cabi\"
version = \"{}\"
edition = \"2024\"
publish = false

# Built on its own by the packaging tool, never as a member of whatever
# workspace it is generated inside.
[workspace]

[lib]
name = \"{}\"
crate-type = [\"cdylib\", \"staticlib\"]

[dependencies]
{} = {{ path = \"{}\" }}

# Built once and shipped, so build time is worth trading for speed. Unwinding
# past an `extern \"C\"` boundary is undefined, so a panic aborts instead.
[profile.release]
lto = true
codegen-units = 1
panic = \"abort\"
",
        opts.package, opts.version, opts.module, opts.crate_package, opts.crate_path,
    )
}

/// A pkg-config file, so a consumer's build finds the header and the library
/// without hardcoding either path.
pub(crate) fn pkg_config(opts: &BindOptions) -> String {
    let mut out = String::from("# Code generated by `cargo soothfast bind gen`. DO NOT EDIT.\n");
    let _ = write!(
        out,
        "prefix=/usr/local\nexec_prefix=${{prefix}}\nlibdir=${{exec_prefix}}/lib\n\
         includedir=${{prefix}}/include\n\nName: {}\nVersion: {}\n",
        opts.package, opts.version,
    );
    let _ = writeln!(
        out,
        "Description: {}",
        opts.description.as_deref().unwrap_or("Native bindings")
    );
    let _ = write!(
        out,
        "Cflags: -I${{includedir}}\nLibs: -L${{libdir}} -l{}\n",
        opts.module,
    );
    out
}

pub(crate) fn readme(plan: &BindingPlan, opts: &BindOptions) -> String {
    let module = &opts.module;
    let mut out = format!("# {}\n\n", opts.package);
    if let Some(description) = &opts.description {
        let _ = writeln!(out, "{description}\n");
    }
    let _ = write!(
        out,
        "C bindings for the `{}` crate, generated by \
         [soothfast](https://github.com/Verdenroz/soothfast). Do not edit by hand: \
         run `cargo soothfast bind gen` instead.\n\n\
         ## Build\n\n```bash\ncargo build --release\n```\n\n\
         That writes `target/release/lib{module}.so` (`.dylib` on macOS, `.dll` on \
         Windows) and `target/release/lib{module}.a`. The header is `{module}.h`.\n\n\
         ## Use\n\n```c\n#include \"{module}.h\"\n```\n\n\
         ## Ownership\n\n\
         Anything this library returns by pointer is yours to release:\n\n\
         - a handle, with its `*_free`\n\
         - a sequence, with its `*_array_free`\n",
        opts.crate_name,
    );
    let _ = write!(
        out,
        "- a string, with `{module}_string_free`\n\n\
         A call that can fail takes a trailing `char **error`. On failure it \
         writes a message there and returns a zero value you must not read; on \
         success it writes `NULL`. Passing `NULL` for `error` discards the \
         message. Every message is a string you release the same way.\n"
    );

    if !plan.classes.is_empty() {
        out.push_str("\n## Types\n\n");
        for class in &plan.classes {
            let _ = writeln!(
                out,
                "### `{}`\n",
                super::types::handle_c(&class.name, module)
            );
            if let Some(doc) = &class.doc {
                let _ = writeln!(out, "{doc}\n");
            }
            for function in class
                .ctor
                .iter()
                .chain(class.methods.iter())
                .chain(class.statics.iter())
            {
                let _ = writeln!(out, "- `{}`", function.symbol);
            }
            out.push('\n');
        }
    }
    if !plan.functions.is_empty() {
        out.push_str("## Functions\n\n");
        for function in &plan.functions {
            let _ = writeln!(out, "- `{}`", function.symbol);
        }
        out.push('\n');
    }
    if !plan.gaps.is_empty() {
        out.push_str("## Not bound\n\n");
        for gap in &plan.gaps {
            let _ = writeln!(out, "- {}", gap.explain());
        }
    }
    out
}
