//! The glue crate's manifest and the npm package around it.

use std::fmt::Write;

use crate::plan::BindingPlan;
use crate::{BindOptions, GENERATED_RS, GENERATED_TOML};

use super::{DEFAULT_BUILD_VERSION, DEFAULT_VERSION, js_ident};

/// The glue crate's `Cargo.toml`.
///
/// `cdylib` only: `napi build` links it straight into the `.node` file, and
/// an `rlib` alongside it would build the whole crate a second time.
pub(crate) fn cargo_toml(opts: &BindOptions) -> String {
    let version = opts.backend_version.as_deref().unwrap_or(DEFAULT_VERSION);
    format!(
        "{GENERATED_TOML}
[package]
name = \"{}\"
version = \"{}\"
edition = \"2024\"
publish = false

# Built on its own by the packaging tool, never as a member of whatever
# workspace it is generated inside.
[workspace]

[lib]
crate-type = [\"cdylib\"]

[dependencies]
{} = {{ path = \"{}\" }}
# napi6 is what `BigInt` and the 64-bit typed arrays need; every Node
# release still supported carries it.
napi = {{ version = \"{version}\", features = [\"napi6\"] }}
napi-derive = \"{version}\"

[build-dependencies]
napi-build = \"{DEFAULT_BUILD_VERSION}\"

# Built once and shipped, so build time is worth trading for a smaller,
# faster artifact.
[profile.release]
lto = true
strip = \"symbols\"
",
        crate_name(&opts.package),
        opts.version,
        opts.crate_package,
        opts.crate_path,
    )
}

/// `napi build` runs this to link against the Node headers for whichever
/// runtime and target the build was invoked for.
pub(crate) fn build_rs() -> String {
    format!("{GENERATED_RS}\nfn main() {{\n    napi_build::setup();\n}}\n")
}

/// A cargo package name from a distribution name. An npm scope has no cargo
/// equivalent, so it flattens into the name `napi build` publishes under.
fn crate_name(package: &str) -> String {
    let flattened: String = package
        .chars()
        .map(|c| match c {
            '@' => '-',
            '/' => '-',
            c if c.is_ascii_alphanumeric() || c == '-' || c == '_' => c,
            _ => '-',
        })
        .collect();
    flattened.trim_matches('-').to_string()
}

/// `package.json` is plain JSON — no comment can mark it generated, so the
/// staleness check in `bind gen --check` is what keeps it honest.
pub(crate) fn package_json(opts: &BindOptions) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "{{");
    let _ = writeln!(out, "  \"name\": {},", quote(&opts.package));
    let _ = writeln!(out, "  \"version\": {},", quote(&opts.version));
    if let Some(description) = &opts.description {
        let _ = writeln!(out, "  \"description\": {},", quote(description));
    }
    let _ = writeln!(out, "  \"main\": \"index.js\",");
    let _ = writeln!(out, "  \"types\": \"index.d.ts\",");
    let _ = writeln!(out, "  \"napi\": {{");
    let _ = writeln!(out, "    \"binaryName\": {}", quote(&opts.module));
    let _ = writeln!(out, "  }},");
    let _ = writeln!(out, "  \"scripts\": {{");
    // `--platform` is what makes `napi build` emit the JS loader `main`
    // points at; without it the build leaves only the raw `.node` file.
    let _ = writeln!(out, "    \"build\": \"napi build --platform --release\",");
    let _ = writeln!(out, "    \"test\": \"node --test\"");
    let _ = writeln!(out, "  }},");
    let _ = writeln!(out, "  \"devDependencies\": {{");
    let _ = writeln!(out, "    \"@napi-rs/cli\": \"^3\"");
    let _ = writeln!(out, "  }}");
    let _ = writeln!(out, "}}");
    out
}

/// A JSON string. JSON escaping is a subset of TOML's, so serde_json renders
/// one directly.
fn quote(value: &str) -> String {
    serde_json::Value::String(value.to_string()).to_string()
}

pub(crate) fn readme(plan: &BindingPlan, opts: &BindOptions) -> String {
    let mut out = format!("# {}\n\n", opts.package);
    if let Some(description) = &opts.description {
        let _ = writeln!(out, "{description}\n");
    }
    let _ = write!(
        out,
        "Node.js bindings for the `{}` crate, generated by \
         [soothfast](https://github.com/Verdenroz/soothfast). Do not edit by hand: \
         run `cargo soothfast bind gen` instead.\n\n\
         ## Install\n\n```bash\nnpm install {}\n```\n\n\
         ## Use\n\n```js\nconst {{ {} }} = require(\"{}\");\n```\n",
        opts.crate_name,
        opts.package,
        exported_names(plan).join(", "),
        opts.package,
    );

    if !plan.classes.is_empty() {
        out.push_str("\n## Classes\n\n");
        for class in &plan.classes {
            let _ = writeln!(out, "### `{}`\n", class.name);
            if let Some(doc) = &class.doc {
                let _ = writeln!(out, "{doc}\n");
            }
            for method in class.methods.iter().chain(class.statics.iter()) {
                let _ = writeln!(out, "- `{}`", js_ident(&method.name));
            }
            out.push('\n');
        }
    }
    if !plan.functions.is_empty() {
        out.push_str("## Functions\n\n");
        for function in &plan.functions {
            let _ = writeln!(out, "- `{}`", js_ident(&function.name));
        }
        out.push('\n');
    }
    if !plan.gaps.is_empty() {
        out.push_str("## Not bound\n\n");
        for gap in &plan.gaps {
            let _ = writeln!(out, "- {}", gap.explain());
        }
    }
    out
}

fn exported_names(plan: &BindingPlan) -> Vec<String> {
    let mut names: Vec<String> = plan.classes.iter().map(|c| c.name.clone()).collect();
    names.extend(plan.functions.iter().map(|f| js_ident(&f.name)));
    names
}
