// @generated by `cargo soothfast docs gen-tests`
// source: docs/measuring.md line 58
fn main() {
    let mut samples = vec![9.0, 1.0, 5.0, 3.0, 7.0];
    let s = soothfast_measure::stats::summarize(&mut samples);
    println!("median={} mad={}", s.median, s.mad);
    println!("min={} max={}", s.min, s.max);
}
