-- Code generated by `cargo soothfast bind gen`. DO NOT EDIT.
local ffi = require("ffi")

ffi.cdef[[

typedef struct core_counter core_counter;

typedef enum core_level {
    CORE_LEVEL_LOW = 0,
    CORE_LEVEL_HIGH = 1,
} core_level;

typedef struct core_mode core_mode;

/* An owned `f64` sequence. Release it with core_f64_array_free. */
typedef struct core_f64_array {
    double *data;
    size_t len;
} core_f64_array;

void core_f64_array_free(core_f64_array array);

/* An owned `u8` sequence. Release it with core_u8_array_free. */
typedef struct core_u8_array {
    uint8_t *data;
    size_t len;
} core_u8_array;

void core_u8_array_free(core_u8_array array);

/* Release a string this library returned. A returned string is never NULL; an interior NUL byte is replaced with U+FFFD. */
void core_string_free(char *text);

/* Release a Counter this library returned. */
void core_counter_free(core_counter *handle);
core_counter * core_counter_new(int64_t start);
int64_t core_counter_value(const core_counter *handle);
int64_t core_counter_at(const core_counter *handle, core_level level);
int64_t core_counter_bump(const core_counter *handle, int64_t by, char **error);
int64_t core_counter_bump_all(const core_counter *handle, const int64_t *by, size_t by_len);
int64_t core_counter_scale(core_counter *handle, int64_t factor);

/* Release a Mode this library returned. */
void core_mode_free(core_mode *handle);

/* `label` may be NULL. May return NULL. */
char * core_describe(const char *label);
/* `label` may be NULL. May return NULL. */
char * core_describe_owned(const char *label);
core_u8_array core_digest(const uint8_t *data, size_t data_len);
int64_t core_fail(const char *message, char **error);
core_counter * core_find_counter(int64_t start);
char * core_greet(const char *name);
core_f64_array core_normalize(const double *input, size_t input_len, double factor);
core_level core_peak_level(const double *values, size_t values_len);
void core_scale_into(const double *values, size_t values_len, double factor, double *out, size_t out_len);
void core_split(const double *src, size_t src_len, double *lo, size_t lo_len, double *hi, size_t hi_len);
uint64_t core_stamp(int64_t handle_, double error_, const uint8_t *register_, size_t register_len);
]]

local lib = ffi.load("core")

local function lua_string(s)
	local text = ffi.string(s)
	lib.core_string_free(s)
	return text
end

local function f64_buf(value)
	-- a VLA cdata array carries no `#`; its instance size does.
	if ffi.istype("double[?]", value) then
		return value, ffi.sizeof(value) / ffi.sizeof("double")
	end
	if ffi.istype("core_f64_array", value) then
		return value.data, tonumber(value.len)
	end
	local n = #value
	local arr = ffi.new("double[?]", n)
	for i = 1, n do
		arr[i - 1] = value[i]
	end
	return arr, n
end

local function i64_buf(value)
	-- a VLA cdata array carries no `#`; its instance size does.
	if ffi.istype("int64_t[?]", value) then
		return value, ffi.sizeof(value) / ffi.sizeof("int64_t")
	end
	local n = #value
	local arr = ffi.new("int64_t[?]", n)
	for i = 1, n do
		arr[i - 1] = value[i]
	end
	return arr, n
end

local function u8_buf(value)
	-- a VLA cdata array carries no `#`; its instance size does.
	if ffi.istype("uint8_t[?]", value) then
		return value, ffi.sizeof(value) / ffi.sizeof("uint8_t")
	end
	if ffi.istype("core_u8_array", value) then
		return value.data, tonumber(value.len)
	end
	local n = #value
	local arr = ffi.new("uint8_t[?]", n)
	for i = 1, n do
		arr[i - 1] = value[i]
	end
	return arr, n
end

-- Copies a `f64` array into a plain table.
local function core_f64_array_totable(self)
	local n = tonumber(self.len)
	local out = {}
	for i = 1, n do
		out[i] = self.data[i - 1]
	end
	return out
end

local function core_f64_array_close(self)
	if self.data == nil then
		return
	end
	ffi.gc(self, nil)
	lib.core_f64_array_free(self)
	self.len = 0
	self.data = nil
end

ffi.metatype("core_f64_array", {
	__len = function(self) return tonumber(self.len) end,
	__index = function(self, key)
		if key == "totable" then
			return core_f64_array_totable
		end
		if key == "close" then
			return core_f64_array_close
		end
		if type(key) == "number" then
			if key % 1 ~= 0 or key < 1 or key > tonumber(self.len) then
				error("core_f64_array index out of range: " .. tostring(key))
			end
			return self.data[key - 1]
		end
	end,
})

-- Copies a `u8` array into a plain table.
local function core_u8_array_totable(self)
	local n = tonumber(self.len)
	local out = {}
	for i = 1, n do
		out[i] = self.data[i - 1]
	end
	return out
end

local function core_u8_array_close(self)
	if self.data == nil then
		return
	end
	ffi.gc(self, nil)
	lib.core_u8_array_free(self)
	self.len = 0
	self.data = nil
end

ffi.metatype("core_u8_array", {
	__len = function(self) return tonumber(self.len) end,
	__index = function(self, key)
		if key == "totable" then
			return core_u8_array_totable
		end
		if key == "close" then
			return core_u8_array_close
		end
		if type(key) == "number" then
			if key % 1 ~= 0 or key < 1 or key > tonumber(self.len) then
				error("core_u8_array index out of range: " .. tostring(key))
			end
			return self.data[key - 1]
		end
	end,
})

local M = {}

local Counter = {}
Counter.__index = Counter
M.Counter = Counter

local function wrap_counter(ptr)
	return setmetatable({ ptr = ffi.gc(ptr, lib.core_counter_free) }, Counter)
end

function Counter:close()
	if self.ptr == nil then
		return
	end
	ffi.gc(self.ptr, nil)
	lib.core_counter_free(self.ptr)
	self.ptr = nil
end

local LEVEL_TO_C = { low = 0, high = 1 }
local LEVEL_FROM_C = { [0] = "low", [1] = "high" }

local function level_to_c(name)
	local v = LEVEL_TO_C[name]
	if v == nil then
		error("invalid Level: " .. tostring(name))
	end
	return v
end

local function level_from_c(value)
	return LEVEL_FROM_C[tonumber(value)]
end

local Mode = {}
Mode.__index = Mode
M.Mode = Mode

local function wrap_mode(ptr)
	return setmetatable({ ptr = ffi.gc(ptr, lib.core_mode_free) }, Mode)
end

function Mode:close()
	if self.ptr == nil then
		return
	end
	ffi.gc(self.ptr, nil)
	lib.core_mode_free(self.ptr)
	self.ptr = nil
end

function Counter.new(start)
	local ret = lib.core_counter_new(start)
	return wrap_counter(ret)
end

function Counter:value()
	return lib.core_counter_value(self.ptr)
end

function Counter:at(level)
	local ret = lib.core_counter_at(self.ptr, level_to_c(level))
	return ret
end

function Counter:bump(by)
	local err = ffi.new("char*[1]")
	local ret = lib.core_counter_bump(self.ptr, by, err)
	if err[0] ~= nil then
		error(lua_string(err[0]))
	end
	return ret
end

function Counter:bump_all(by)
	local by_ptr, by_len = i64_buf(by)
	local ret = lib.core_counter_bump_all(self.ptr, by_ptr, by_len)
	return ret
end

function Counter:scale(factor)
	local ret = lib.core_counter_scale(self.ptr, factor)
	return ret
end

function M.describe(label)
	local ret = lib.core_describe(label)
	return (function() local p = ret; if p == nil then return nil end; return lua_string(p) end)()
end

function M.describe_owned(label)
	local ret = lib.core_describe_owned(label)
	return (function() local p = ret; if p == nil then return nil end; return lua_string(p) end)()
end

function M.digest(data)
	local data_ptr, data_len = u8_buf(data)
	local ret = lib.core_digest(data_ptr, data_len)
	return ffi.gc(ret, lib.core_u8_array_free)
end

function M.fail(message)
	local err = ffi.new("char*[1]")
	local ret = lib.core_fail(message, err)
	if err[0] ~= nil then
		error(lua_string(err[0]))
	end
	return ret
end

function M.find_counter(start)
	local ret = lib.core_find_counter(start)
	return (function() local p = ret; if p == nil then return nil end; return wrap_counter(p) end)()
end

function M.greet(name)
	local ret = lib.core_greet(name)
	return lua_string(ret)
end

function M.normalize(input, factor)
	local input_ptr, input_len = f64_buf(input)
	local ret = lib.core_normalize(input_ptr, input_len, factor)
	return ffi.gc(ret, lib.core_f64_array_free)
end

function M.peak_level(values)
	local values_ptr, values_len = f64_buf(values)
	local ret = lib.core_peak_level(values_ptr, values_len)
	return level_from_c(ret)
end

function M.scale_into(values, factor, out)
	local values_ptr, values_len = f64_buf(values)
	local out_ptr, out_len = f64_buf(out)
	lib.core_scale_into(values_ptr, values_len, factor, out_ptr, out_len)
	if type(out) == "table" then
		for i = 1, out_len do
			out[i] = out_ptr[i - 1]
		end
	end
end

function M.split(src, lo, hi)
	local src_ptr, src_len = f64_buf(src)
	local lo_ptr, lo_len = f64_buf(lo)
	local hi_ptr, hi_len = f64_buf(hi)
	lib.core_split(src_ptr, src_len, lo_ptr, lo_len, hi_ptr, hi_len)
	if type(lo) == "table" then
		for i = 1, lo_len do
			lo[i] = lo_ptr[i - 1]
		end
	end
	if type(hi) == "table" then
		for i = 1, hi_len do
			hi[i] = hi_ptr[i - 1]
		end
	end
end

function M.stamp(handle, error_, register)
	local register_ptr, register_len = u8_buf(register)
	local ret = lib.core_stamp(handle, error_, register_ptr, register_len)
	return ret
end

return M
