/* Code generated by `cargo soothfast bind gen`. DO NOT EDIT. */

#ifndef CORE_H
#define CORE_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct core_counter core_counter;

typedef enum core_level {
    CORE_LEVEL_LOW = 0,
    CORE_LEVEL_HIGH = 1,
} core_level;

typedef struct core_mode core_mode;

/* An owned `f64` sequence. Release it with core_f64_array_free. */
typedef struct core_f64_array {
    double *data;
    size_t len;
} core_f64_array;

void core_f64_array_free(core_f64_array array);

/* An owned `u8` sequence. Release it with core_u8_array_free. */
typedef struct core_u8_array {
    uint8_t *data;
    size_t len;
} core_u8_array;

void core_u8_array_free(core_u8_array array);

/* Release a string this library returned. A returned string is never NULL; an interior NUL byte is replaced with U+FFFD. */
void core_string_free(char *text);

/* Release a Counter this library returned. */
void core_counter_free(core_counter *handle);
core_counter * core_counter_new(int64_t start);
int64_t core_counter_value(const core_counter *handle);
void core_counter_absorb(core_counter *handle, const core_counter *other);
int64_t core_counter_at(const core_counter *handle, core_level level);
int64_t core_counter_bump(const core_counter *handle, int64_t by, char **error);
int64_t core_counter_bump_all(const core_counter *handle, const int64_t *by, size_t by_len);
int64_t core_counter_scale(core_counter *handle, int64_t factor);

/* Release a Mode this library returned. */
void core_mode_free(core_mode *handle);

/* `label` may be NULL. May return NULL. */
char * core_describe(const char *label);
/* `label` may be NULL. May return NULL. */
char * core_describe_owned(const char *label);
core_u8_array core_digest(const uint8_t *data, size_t data_len);
int64_t core_fail(const char *message, char **error);
core_counter * core_find_counter(int64_t start);
char * core_greet(const char *name);
int64_t core_mutate_counter(core_counter *counter);
core_f64_array core_normalize(const double *input, size_t input_len, double factor);
core_level core_peak_level(const double *values, size_t values_len);
void core_scale_into(const double *values, size_t values_len, double factor, double *out, size_t out_len);
void core_split(const double *src, size_t src_len, double *lo, size_t lo_len, double *hi, size_t hi_len);
uint64_t core_stamp(int64_t handle_, double error_, const uint8_t *register_, size_t register_len);

#ifdef __cplusplus
}
#endif

#endif /* CORE_H */
