// Code generated by `cargo soothfast bind gen`. DO NOT EDIT.
// A handle class with no methods never reads the value it holds.
#![allow(dead_code)]

use ::magnus::prelude::*;

static ERROR: ::magnus::value::Lazy<::magnus::ExceptionClass> = ::magnus::value::Lazy::new(|ruby| {
    ruby.define_module("AcmeCore")
        .and_then(|m| m.define_error("Error", ruby.exception_standard_error()))
        .unwrap_or_else(|e| panic!("defines AcmeCore::Error: {e}"))
});

fn level_from_symbol(
    ruby: &::magnus::Ruby,
    value: ::magnus::Symbol,
) -> Result<::acme::Level, ::magnus::Error> {
    match value.name()?.as_ref() {
        "low" => Ok(::acme::Level::Low),
        "high" => Ok(::acme::Level::High),
        other => Err(::magnus::Error::new(
            ruby.exception_arg_error(),
            format!("invalid Level: :{other}"),
        )),
    }
}

fn level_to_symbol(ruby: &::magnus::Ruby, value: ::acme::Level) -> ::magnus::Symbol {
    match value {
        ::acme::Level::Low => ruby.to_symbol("low"),
        ::acme::Level::High => ruby.to_symbol("high"),
    }
}

#[::magnus::wrap(class = "AcmeCore::Counter", free_immediately)]
pub struct Counter(::std::cell::RefCell<::acme::Counter>);

impl Counter {
    fn new(start: i64) -> Self {
        Counter(::std::cell::RefCell::new(::acme::Counter::new(start)))
    }

    fn value(ruby: &::magnus::Ruby, rb_self: &Self) -> Result<i64, ::magnus::Error> {
        let __recv = rb_self.0.try_borrow().map_err(|_| ::magnus::Error::new(ruby.get_inner(&ERROR), "already borrowed".to_string()))?;
        Ok(__recv.value.clone())
    }

    fn set_value(ruby: &::magnus::Ruby, rb_self: &Self, value: i64) -> Result<(), ::magnus::Error> {
        let mut __recv = rb_self.0.try_borrow_mut().map_err(|_| ::magnus::Error::new(ruby.get_inner(&ERROR), "already borrowed".to_string()))?;
        __recv.value = value;
        Ok(())
    }

    fn at(ruby: &::magnus::Ruby, rb_self: &Self, level: ::magnus::Symbol) -> Result<i64, ::magnus::Error> {
        let __recv = rb_self.0.try_borrow().map_err(|_| ::magnus::Error::new(ruby.get_inner(&ERROR), "already borrowed".to_string()))?;
        let level = level_from_symbol(ruby, level)?;
        Ok(__recv.at(level))
    }

    fn bump(ruby: &::magnus::Ruby, rb_self: &Self, by: i64) -> Result<i64, ::magnus::Error> {
        let __recv = rb_self.0.try_borrow().map_err(|_| ::magnus::Error::new(ruby.get_inner(&ERROR), "already borrowed".to_string()))?;
        Ok(__recv.bump(by).map_err(|reason| ::magnus::Error::new(ruby.get_inner(&ERROR), ::std::string::ToString::to_string(&reason)))?)
    }

    fn bump_all(ruby: &::magnus::Ruby, rb_self: &Self, by: Vec<i64>) -> Result<i64, ::magnus::Error> {
        let __recv = rb_self.0.try_borrow().map_err(|_| ::magnus::Error::new(ruby.get_inner(&ERROR), "already borrowed".to_string()))?;
        Ok(__recv.bump_all(by))
    }

    fn scale(ruby: &::magnus::Ruby, rb_self: &Self, factor: i64) -> Result<i64, ::magnus::Error> {
        let mut __recv = rb_self.0.try_borrow_mut().map_err(|_| ::magnus::Error::new(ruby.get_inner(&ERROR), "already borrowed".to_string()))?;
        Ok(__recv.scale(factor))
    }
}

#[::magnus::wrap(class = "AcmeCore::Mode", free_immediately)]
pub struct Mode(::std::cell::RefCell<::acme::Mode>);

fn describe(label: Option<String>) -> Option<String> {
    ::acme::describe(label.as_deref())
}

fn describe_owned(label: Option<String>) -> Option<String> {
    ::acme::describe_owned(label)
}

fn digest(data: ::magnus::RString) -> ::magnus::RString {
    let data = unsafe { data.as_slice() }.to_vec();
    ::magnus::RString::from_slice(&::acme::digest(&data))
}

fn fail(ruby: &::magnus::Ruby, message: String) -> Result<i64, ::magnus::Error> {
    Ok(::acme::fail(&message).map_err(|reason| ::magnus::Error::new(ruby.get_inner(&ERROR), ::std::string::ToString::to_string(&reason)))?)
}

fn find_counter(start: i64) -> Option<Counter> {
    (::acme::find_counter(start)).map(|value| Counter(::std::cell::RefCell::new(value)))
}

fn greet(name: String) -> String {
    ::acme::greet(&name)
}

fn index_all() -> ::std::collections::HashMap<String, u32> {
    ::acme::index_all()
}

fn maybe_ratio(value: f64) -> Option<f64> {
    ::acme::maybe_ratio(value)
}

fn normalize(input: Vec<f64>, factor: f64) -> Vec<f64> {
    ::acme::normalize(input, factor)
}

fn peak_level(ruby: &::magnus::Ruby, values: Vec<f64>) -> ::magnus::Symbol {
    level_to_symbol(ruby, ::acme::peak_level(&values))
}

fn scale_into(values: Vec<f64>, factor: f64, out: ::magnus::RArray) -> Result<(), ::magnus::Error> {
    let mut out_vec = out.to_vec::<f64>()?;
    let __out = ::acme::scale_into(&values, factor, &mut out_vec);
    out_vec.iter().enumerate().try_for_each(|(i, value)| out.store(i as isize, *value))?;
    Ok(__out)
}

fn split(src: Vec<f64>, lo: ::magnus::RArray, hi: ::magnus::RArray) -> Result<(), ::magnus::Error> {
    let mut lo_vec = lo.to_vec::<f64>()?;
    let mut hi_vec = hi.to_vec::<f64>()?;
    let __out = ::acme::split(&src, &mut lo_vec, &mut hi_vec);
    lo_vec.iter().enumerate().try_for_each(|(i, value)| lo.store(i as isize, *value))?;
    hi_vec.iter().enumerate().try_for_each(|(i, value)| hi.store(i as isize, *value))?;
    Ok(__out)
}

fn stamp(handle: i64, error: f64, register: ::magnus::RString) -> u64 {
    let register = unsafe { register.as_slice() }.to_vec();
    ::acme::stamp(handle, error, &register)
}

fn trim(input: Vec<f64>) -> Option<Vec<f64>> {
    ::acme::trim(&input)
}

#[::magnus::init]
fn init(ruby: &::magnus::Ruby) -> Result<(), ::magnus::Error> {
    let module = ruby.define_module("AcmeCore")?;
    ::magnus::value::Lazy::force(&ERROR, ruby);
    let class = module.define_class("Counter", ruby.class_object())?;
    class.define_singleton_method("new", ::magnus::function!(Counter::new, 1))?;
    class.define_method("value", ::magnus::method!(Counter::value, 0))?;
    class.define_method("value=", ::magnus::method!(Counter::set_value, 1))?;
    class.define_method("at", ::magnus::method!(Counter::at, 1))?;
    class.define_method("bump", ::magnus::method!(Counter::bump, 1))?;
    class.define_method("bump_all", ::magnus::method!(Counter::bump_all, 1))?;
    class.define_method("scale", ::magnus::method!(Counter::scale, 1))?;
    module.define_class("Mode", ruby.class_object())?;
    module.define_module_function("describe", ::magnus::function!(describe, 1))?;
    module.define_module_function("describe_owned", ::magnus::function!(describe_owned, 1))?;
    module.define_module_function("digest", ::magnus::function!(digest, 1))?;
    module.define_module_function("fail", ::magnus::function!(fail, 1))?;
    module.define_module_function("find_counter", ::magnus::function!(find_counter, 1))?;
    module.define_module_function("greet", ::magnus::function!(greet, 1))?;
    module.define_module_function("index_all", ::magnus::function!(index_all, 0))?;
    module.define_module_function("maybe_ratio", ::magnus::function!(maybe_ratio, 1))?;
    module.define_module_function("normalize", ::magnus::function!(normalize, 2))?;
    module.define_module_function("peak_level", ::magnus::function!(peak_level, 1))?;
    module.define_module_function("scale_into", ::magnus::function!(scale_into, 3))?;
    module.define_module_function("split", ::magnus::function!(split, 3))?;
    module.define_module_function("stamp", ::magnus::function!(stamp, 3))?;
    module.define_module_function("trim", ::magnus::function!(trim, 1))?;
    Ok(())
}
