// Code generated by `cargo soothfast bind gen`. DO NOT EDIT.
// A handle class with no methods never reads the value it holds.
#![allow(dead_code)]

use pyo3::prelude::*;

/// The runtime an exported `async fn` is polled inside.
fn runtime() -> &'static ::tokio::runtime::Runtime {
    static RUNTIME: ::std::sync::OnceLock<::tokio::runtime::Runtime> =
        ::std::sync::OnceLock::new();
    RUNTIME.get_or_init(|| {
        ::tokio::runtime::Runtime::new().expect("start the binding runtime")
    })
}

/// A future polled inside [`runtime`]'s context.
///
/// The guard is taken per poll rather than held across awaits: it restores a
/// thread-local on drop, and a suspended future would leave that thread
/// carrying a context it never entered.
struct OnRuntime<F>(F);

impl<F: ::std::future::Future> ::std::future::Future for OnRuntime<F> {
    type Output = F::Output;

    fn poll(
        self: ::std::pin::Pin<&mut Self>,
        cx: &mut ::std::task::Context<'_>,
    ) -> ::std::task::Poll<F::Output> {
        let _guard = runtime().enter();
        // The wrapper is a newtype with no fields of its own, so the inner
        // future is pinned exactly as far as the wrapper is.
        unsafe { self.map_unchecked_mut(|it| &mut it.0) }.poll(cx)
    }
}

/// An `f64` sequence read through the buffer protocol when the caller
/// passes a buffer (`array.array`, `memoryview`, numpy), and unboxed element
/// by element only when it is some other sequence.
enum BorrowedF64 {
    Buffer(::pyo3::buffer::PyBuffer<f64>),
    Owned(Vec<f64>),
}

impl<'py> ::pyo3::FromPyObject<'py> for BorrowedF64 {
    fn extract_bound(obj: &::pyo3::Bound<'py, ::pyo3::PyAny>) -> ::pyo3::PyResult<Self> {
        if let Ok(buf) = ::pyo3::buffer::PyBuffer::<f64>::get(obj)
            && buf.is_c_contiguous()
        {
            return Ok(BorrowedF64::Buffer(buf));
        }
        Ok(BorrowedF64::Owned(obj.extract()?))
    }
}

impl BorrowedF64 {
    fn as_slice(&self) -> &[f64] {
        match self {
            // Item type and contiguity were both checked at extraction, so
            // the pointer addresses exactly `item_count` items.
            BorrowedF64::Buffer(b) => unsafe {
                ::std::slice::from_raw_parts(b.buf_ptr() as *const f64, b.item_count())
            },
            BorrowedF64::Owned(v) => v,
        }
    }

    fn into_vec(self) -> Vec<f64> {
        match self {
            BorrowedF64::Buffer(_) => self.as_slice().to_vec(),
            BorrowedF64::Owned(v) => v,
        }
    }
}

/// An `i64` sequence read through the buffer protocol when the caller
/// passes a buffer (`array.array`, `memoryview`, numpy), and unboxed element
/// by element only when it is some other sequence.
enum BorrowedI64 {
    Buffer(::pyo3::buffer::PyBuffer<i64>),
    Owned(Vec<i64>),
}

impl<'py> ::pyo3::FromPyObject<'py> for BorrowedI64 {
    fn extract_bound(obj: &::pyo3::Bound<'py, ::pyo3::PyAny>) -> ::pyo3::PyResult<Self> {
        if let Ok(buf) = ::pyo3::buffer::PyBuffer::<i64>::get(obj)
            && buf.is_c_contiguous()
        {
            return Ok(BorrowedI64::Buffer(buf));
        }
        Ok(BorrowedI64::Owned(obj.extract()?))
    }
}

impl BorrowedI64 {
    fn as_slice(&self) -> &[i64] {
        match self {
            // Item type and contiguity were both checked at extraction, so
            // the pointer addresses exactly `item_count` items.
            BorrowedI64::Buffer(b) => unsafe {
                ::std::slice::from_raw_parts(b.buf_ptr() as *const i64, b.item_count())
            },
            BorrowedI64::Owned(v) => v,
        }
    }

    fn into_vec(self) -> Vec<i64> {
        match self {
            BorrowedI64::Buffer(_) => self.as_slice().to_vec(),
            BorrowedI64::Owned(v) => v,
        }
    }
}

/// An `u8` sequence read through the buffer protocol when the caller
/// passes a buffer (`array.array`, `memoryview`, numpy), and unboxed element
/// by element only when it is some other sequence.
enum BorrowedU8 {
    Buffer(::pyo3::buffer::PyBuffer<u8>),
    Owned(Vec<u8>),
}

impl<'py> ::pyo3::FromPyObject<'py> for BorrowedU8 {
    fn extract_bound(obj: &::pyo3::Bound<'py, ::pyo3::PyAny>) -> ::pyo3::PyResult<Self> {
        if let Ok(buf) = ::pyo3::buffer::PyBuffer::<u8>::get(obj)
            && buf.is_c_contiguous()
        {
            return Ok(BorrowedU8::Buffer(buf));
        }
        Ok(BorrowedU8::Owned(obj.extract()?))
    }
}

impl BorrowedU8 {
    fn as_slice(&self) -> &[u8] {
        match self {
            // Item type and contiguity were both checked at extraction, so
            // the pointer addresses exactly `item_count` items.
            BorrowedU8::Buffer(b) => unsafe {
                ::std::slice::from_raw_parts(b.buf_ptr() as *const u8, b.item_count())
            },
            BorrowedU8::Owned(v) => v,
        }
    }

    fn into_vec(self) -> Vec<u8> {
        match self {
            BorrowedU8::Buffer(_) => self.as_slice().to_vec(),
            BorrowedU8::Owned(v) => v,
        }
    }
}

/// An owned `f64` sequence. `memoryview(x)` and `numpy.asarray(x)` read
/// it without copying; `x.tolist()` copies it into a plain list.
#[pyclass(name = "F64Array")]
pub struct F64Array(Vec<f64>);

impl F64Array {
    fn new(values: Vec<f64>) -> Self {
        F64Array(values)
    }
}

#[pymethods]
impl F64Array {
    fn __len__(&self) -> usize {
        self.0.len()
    }

    fn __getitem__(&self, index: isize) -> ::pyo3::PyResult<f64> {
        let at = match index < 0 {
            true => index + self.0.len() as isize,
            false => index,
        };
        usize::try_from(at)
            .ok()
            .and_then(|at| self.0.get(at))
            .copied()
            .ok_or_else(|| ::pyo3::exceptions::PyIndexError::new_err("index out of range"))
    }

    fn __iter__<'py>(
        &self,
        py: ::pyo3::Python<'py>,
    ) -> ::pyo3::PyResult<::pyo3::Bound<'py, ::pyo3::PyAny>> {
        use ::pyo3::types::PyAnyMethods;
        Ok(::pyo3::types::PyList::new(py, &self.0)?.try_iter()?.into_any())
    }

    fn __repr__(&self) -> String {
        format!("F64Array({:?})", self.0)
    }

    /// The same values as a plain Python list.
    fn tolist(&self) -> Vec<f64> {
        self.0.clone()
    }

    unsafe fn __getbuffer__(
        slf: ::pyo3::Bound<'_, Self>,
        view: *mut ::pyo3::ffi::Py_buffer,
        flags: ::std::os::raw::c_int,
    ) -> ::pyo3::PyResult<()> {
        if view.is_null() {
            return Err(::pyo3::exceptions::PyBufferError::new_err("view is null"));
        }
        if (flags & ::pyo3::ffi::PyBUF_WRITABLE) == ::pyo3::ffi::PyBUF_WRITABLE {
            return Err(::pyo3::exceptions::PyBufferError::new_err(
                "F64Array is read-only",
            ));
        }
        let size = ::std::mem::size_of::<f64>() as isize;
        let (buf, count) = {
            let values = &slf.borrow().0;
            (values.as_ptr() as *mut ::std::ffi::c_void, values.len() as isize)
        };
        let meta = Box::into_raw(Box::new([count, size]));
        unsafe {
            (*view).obj = slf.into_ptr();
            (*view).buf = buf;
            (*view).len = count * size;
            (*view).readonly = 1;
            (*view).itemsize = size;
            (*view).ndim = 1;
            (*view).format = match (flags & ::pyo3::ffi::PyBUF_FORMAT) == ::pyo3::ffi::PyBUF_FORMAT
            {
                true => c"d".as_ptr() as *mut ::std::os::raw::c_char,
                false => ::std::ptr::null_mut(),
            };
            (*view).shape = match (flags & ::pyo3::ffi::PyBUF_ND) == ::pyo3::ffi::PyBUF_ND {
                true => meta as *mut isize,
                false => ::std::ptr::null_mut(),
            };
            (*view).strides = match (flags & ::pyo3::ffi::PyBUF_STRIDES)
                == ::pyo3::ffi::PyBUF_STRIDES
            {
                true => (meta as *mut isize).add(1),
                false => ::std::ptr::null_mut(),
            };
            (*view).suboffsets = ::std::ptr::null_mut();
            (*view).internal = meta as *mut ::std::ffi::c_void;
        }
        Ok(())
    }

    unsafe fn __releasebuffer__(&self, view: *mut ::pyo3::ffi::Py_buffer) {
        // Paired with the `Box::into_raw` every filled view carries out.
        unsafe { drop(Box::from_raw((*view).internal as *mut [isize; 2])) };
    }
}

struct BindErrorString(::std::string::String);

impl ::std::convert::From<BindErrorString> for ::pyo3::PyErr {
    fn from(err: BindErrorString) -> ::pyo3::PyErr {
        ::pyo3::exceptions::PyRuntimeError::new_err(::std::string::ToString::to_string(&err.0))
    }
}

#[pyclass(name = "Counter")]
pub struct Counter(::acme::Counter);

#[pymethods]
impl Counter {
    #[new]
    fn new(start: i64) -> Self {
        Counter(::acme::Counter::new(start))
    }

    #[getter]
    fn value(&self) -> i64 {
        self.0.value.clone()
    }

    #[setter]
    fn set_value(&mut self, value: i64) {
        self.0.value = value;
    }

    fn at(&self, level: Level) -> i64 {
        self.0.at(level.into())
    }

    fn bump(&self, by: i64) -> PyResult<i64> {
        Ok(self.0.bump(by).map_err(BindErrorString)?)
    }

    fn bump_all(&self, py: Python<'_>, by: BorrowedI64) -> i64 {
        py.detach(|| self.0.bump_all(by.into_vec()))
    }

    async fn refresh(&self) -> u32 {
        OnRuntime(self.0.refresh()).await
    }
}

#[pyclass(name = "Level", eq, eq_int)]
#[derive(Clone, Copy, PartialEq, Eq)]
pub enum Level {
    Low,
    High,
}

impl ::std::convert::From<::acme::Level> for Level {
    fn from(value: ::acme::Level) -> Self {
        match value {
            ::acme::Level::Low => Level::Low,
            ::acme::Level::High => Level::High,
        }
    }
}

impl ::std::convert::From<Level> for ::acme::Level {
    fn from(value: Level) -> Self {
        match value {
            Level::Low => ::acme::Level::Low,
            Level::High => ::acme::Level::High,
        }
    }
}

#[pyclass(name = "Mode")]
pub struct Mode(::acme::Mode);

#[pyfunction]
fn digest(py: Python<'_>, data: BorrowedU8) -> Vec<u8> {
    py.detach(|| ::acme::digest(data.as_slice()))
}

#[pyfunction]
fn index_all() -> ::std::collections::HashMap<String, u32> {
    ::acme::index_all()
}

#[pyfunction]
fn normalize(py: Python<'_>, input: BorrowedF64, factor: f64) -> F64Array {
    let out = py.detach(|| ::acme::normalize(input.into_vec(), factor));
    F64Array::new(out)
}

#[pyfunction]
fn stamp(py: Python<'_>, handle: i64, error: f64, register: BorrowedU8) -> u64 {
    py.detach(|| ::acme::stamp(handle, error, register.as_slice()))
}

#[pyfunction]
fn trim(py: Python<'_>, input: BorrowedF64) -> Option<F64Array> {
    let out = py.detach(|| ::acme::trim(input.as_slice()));
    out.map(F64Array::new)
}

#[pymodule]
fn acme_core(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_class::<F64Array>()?;
    m.add_class::<Counter>()?;
    m.add_class::<Level>()?;
    m.add_class::<Mode>()?;
    m.add_function(wrap_pyfunction!(digest, m)?)?;
    m.add_function(wrap_pyfunction!(index_all, m)?)?;
    m.add_function(wrap_pyfunction!(normalize, m)?)?;
    m.add_function(wrap_pyfunction!(stamp, m)?)?;
    m.add_function(wrap_pyfunction!(trim, m)?)?;
    Ok(())
}
