// Code generated by `cargo soothfast bind gen`. DO NOT EDIT.
// A handle class with no methods never reads the value it holds.
#![allow(dead_code)]

use napi::bindgen_prelude::*;
use napi_derive::napi;

struct BindErrorString(::std::string::String);

impl ::std::convert::From<BindErrorString> for ::napi::Error {
    fn from(err: BindErrorString) -> ::napi::Error {
        ::napi::Error::from_reason(::std::string::ToString::to_string(&err.0))
    }
}

/// Which statistic a comparison reads.
#[napi]
#[derive(Clone, Copy, PartialEq, Eq)]
pub enum Metric {
    Median,
    Mad,
    Min,
    Max,
}

impl ::std::convert::From<::soothfast_demo::Metric> for Metric {
    fn from(value: ::soothfast_demo::Metric) -> Self {
        match value {
            ::soothfast_demo::Metric::Median => Metric::Median,
            ::soothfast_demo::Metric::Mad => Metric::Mad,
            ::soothfast_demo::Metric::Min => Metric::Min,
            ::soothfast_demo::Metric::Max => Metric::Max,
        }
    }
}

impl ::std::convert::From<Metric> for ::soothfast_demo::Metric {
    fn from(value: Metric) -> Self {
        match value {
            Metric::Median => ::soothfast_demo::Metric::Median,
            Metric::Mad => ::soothfast_demo::Metric::Mad,
            Metric::Min => ::soothfast_demo::Metric::Min,
            Metric::Max => ::soothfast_demo::Metric::Max,
        }
    }
}

/// A robust summary of one sample set.
#[napi]
pub struct Summary(::soothfast_demo::Summary);

#[napi]
impl Summary {
    /// Summarize a sample set. Fails on an empty one, which has no median.
    #[napi(constructor)]
    pub fn new(samples: Float64Array) -> Result<Self> {
        Ok(Summary(::soothfast_demo::Summary::new(samples.to_vec()).map_err(BindErrorString)?))
    }

    #[napi(getter)]
    pub fn median(&self) -> f64 {
        self.0.median.clone()
    }

    #[napi(setter)]
    pub fn set_median(&mut self, value: f64) {
        self.0.median = value;
    }

    /// Median absolute deviation, unscaled.
    #[napi(getter)]
    pub fn mad(&self) -> f64 {
        self.0.mad.clone()
    }

    #[napi(setter)]
    pub fn set_mad(&mut self, value: f64) {
        self.0.mad = value;
    }

    #[napi(getter)]
    pub fn min(&self) -> f64 {
        self.0.min.clone()
    }

    #[napi(setter)]
    pub fn set_min(&mut self, value: f64) {
        self.0.min = value;
    }

    #[napi(getter)]
    pub fn max(&self) -> f64 {
        self.0.max.clone()
    }

    #[napi(setter)]
    pub fn set_max(&mut self, value: f64) {
        self.0.max = value;
    }

    /// How far `value` sits from the median, in MAD units.
    #[napi]
    pub fn deviations(&self, value: f64) -> f64 {
        self.0.deviations(value)
    }

    /// How far each of `values` sits from the median, in MAD units.
    #[napi(js_name = "deviationsAll")]
    pub fn deviations_all(&self, values: Float64Array) -> Float64Array {
        Float64Array::from(self.0.deviations_all(values.as_ref()))
    }

    /// [`Summary::deviations_all`], writing into a caller-owned buffer.
    #[napi(js_name = "deviationsInto")]
    pub fn deviations_into(&self, values: Float64Array, mut out: Float64Array) -> () {
        self.0.deviations_into(values.as_ref(), unsafe { out.as_mut() })
    }

    /// Read one statistic by name.
    #[napi]
    pub fn get(&self, metric: Metric) -> f64 {
        self.0.get(metric.into())
    }

    /// A one-line rendering of the whole summary.
    #[napi]
    pub fn label(&self) -> String {
        self.0.label()
    }

    /// Scale every statistic by `factor`.
    #[napi]
    pub fn rescale(&mut self, factor: f64) -> () {
        self.0.rescale(factor)
    }

    /// Parse a comma-separated sample set.
    #[napi]
    pub fn parse(text: String) -> Result<Summary> {
        Ok(Summary(::soothfast_demo::Summary::parse(&text).map_err(BindErrorString)?))
    }
}

/// FNV-1a fingerprint of some bytes.
#[napi]
pub fn fingerprint(bytes: Buffer) -> BigInt {
    BigInt::from(::soothfast_demo::fingerprint(bytes.to_vec()))
}
