//! The glue crate's manifest and the README wasm-pack copies into the
//! published package.

use std::fmt::Write;

use crate::plan::BindingPlan;
use crate::{BindOptions, GENERATED_TOML};

use super::{DEFAULT_VERSION, js_ident};

/// The glue crate's `Cargo.toml`.
///
/// wasm-pack reads the npm package name off this crate's name, and there is
/// no target matrix: one `.wasm` runs everywhere.
pub(crate) fn cargo_toml(plan: &BindingPlan, opts: &BindOptions) -> String {
    let version = opts.backend_version.as_deref().unwrap_or(DEFAULT_VERSION);
    format!(
        "{GENERATED_TOML}
[package]
name = \"{}\"
version = \"{}\"
edition = \"2024\"
publish = false

# Built on its own by the packaging tool, never as a member of whatever
# workspace it is generated inside.
[workspace]

[lib]
crate-type = [\"cdylib\", \"rlib\"]

[dependencies]
{} = {{ path = \"{}\" }}
wasm-bindgen = \"{version}\"
{}\n# Built once and shipped, so build time is worth trading for a smaller,\n# faster artifact. wasm32 has no unwinding, so aborting costs nothing.\n[profile.release]\nlto = true\ncodegen-units = 1\npanic = \"abort\"\n",
        crate_name(&opts.package),
        opts.version,
        opts.crate_package,
        opts.crate_path,
        futures_dep(plan),
    )
}

/// wasm-bindgen expands an exported `async fn` into code that names
/// `wasm_bindgen_futures`, so the glue depends on it exactly when one is
/// bound.
fn futures_dep(plan: &BindingPlan) -> String {
    match plan.has_async() {
        true => "wasm-bindgen-futures = \"0.4\"\n".to_string(),
        false => String::new(),
    }
}

/// A cargo package name from a distribution name. An npm scope has no cargo
/// equivalent, so it flattens into the name wasm-pack publishes under.
fn crate_name(package: &str) -> String {
    let flattened: String = package
        .chars()
        .map(|c| match c {
            '@' => '-',
            '/' => '-',
            c if c.is_ascii_alphanumeric() || c == '-' || c == '_' => c,
            _ => '-',
        })
        .collect();
    flattened.trim_matches('-').to_string()
}

pub(crate) fn readme(plan: &BindingPlan, opts: &BindOptions) -> String {
    let mut out = format!("# {}\n\n", opts.package);
    if let Some(description) = &opts.description {
        let _ = writeln!(out, "{description}\n");
    }
    let _ = write!(
        out,
        "JavaScript bindings for the `{}` crate, generated by \
         [soothfast](https://github.com/Verdenroz/soothfast). Do not edit by hand: \
         run `cargo soothfast bind gen` instead.\n\n\
         ## Use\n\n```js\nimport init, {{ {} }} from \"./pkg/{}.js\";\n\n\
         await init();\n```\n",
        opts.crate_name,
        exported_names(plan).join(", "),
        crate_name(&opts.package),
    );

    if !plan.classes.is_empty() {
        out.push_str("\n## Classes\n\n");
        for class in &plan.classes {
            let _ = writeln!(out, "### `{}`\n", class.name);
            if let Some(doc) = &class.doc {
                let _ = writeln!(out, "{doc}\n");
            }
            for method in class.methods.iter().chain(class.statics.iter()) {
                let _ = writeln!(out, "- `{}`", js_ident(&method.name));
            }
            out.push('\n');
        }
    }
    if !plan.functions.is_empty() {
        out.push_str("## Functions\n\n");
        for function in &plan.functions {
            let _ = writeln!(out, "- `{}`", js_ident(&function.name));
        }
        out.push('\n');
    }
    if !plan.gaps.is_empty() {
        out.push_str("## Not bound\n\n");
        for gap in &plan.gaps {
            let _ = writeln!(out, "- {}", gap.explain());
        }
    }
    out
}

fn exported_names(plan: &BindingPlan) -> Vec<String> {
    let mut names: Vec<String> = plan.classes.iter().map(|c| c.name.clone()).collect();
    names.extend(plan.functions.iter().map(|f| js_ident(&f.name)));
    names
}
