-- Code generated by `cargo soothfast bind gen`. DO NOT EDIT.
local ffi = require("ffi")

ffi.cdef[[

/* Which statistic a comparison reads. */
typedef enum stats_metric {
    STATS_METRIC_MEDIAN = 0,
    STATS_METRIC_MAD = 1,
    STATS_METRIC_MIN = 2,
    STATS_METRIC_MAX = 3,
} stats_metric;

/* A robust summary of one sample set. */
typedef struct stats_summary stats_summary;

/* An owned `f64` sequence. Release it with stats_f64_array_free. */
typedef struct stats_f64_array {
    double *data;
    size_t len;
} stats_f64_array;

void stats_f64_array_free(stats_f64_array array);

/* Release a string this library returned. */
void stats_string_free(char *text);

/* Release a Summary this library returned. */
void stats_summary_free(stats_summary *handle);
/* Summarize a sample set. Fails on an empty one, which has no median. */
stats_summary * stats_summary_new(const double *samples, size_t samples_len, char **error);
double stats_summary_median(const stats_summary *handle);
/* Median absolute deviation, unscaled. */
double stats_summary_mad(const stats_summary *handle);
double stats_summary_min(const stats_summary *handle);
double stats_summary_max(const stats_summary *handle);
/* How far `value` sits from the median, in MAD units. */
double stats_summary_deviations(const stats_summary *handle, double value);
/* How far each of `values` sits from the median, in MAD units. */
stats_f64_array stats_summary_deviations_all(const stats_summary *handle, const double *values, size_t values_len);
/* [`Summary::deviations_all`], writing into a caller-owned buffer. */
void stats_summary_deviations_into(const stats_summary *handle, const double *values, size_t values_len, double *out, size_t out_len);
/* Read one statistic by name. */
double stats_summary_get(const stats_summary *handle, stats_metric metric);
/* A one-line rendering of the whole summary. */
char * stats_summary_label(const stats_summary *handle);
/* Scale every statistic by `factor`. */
void stats_summary_rescale(stats_summary *handle, double factor);
/* Parse a comma-separated sample set. */
stats_summary * stats_summary_parse(const char *text, char **error);

/* FNV-1a fingerprint of some bytes. */
uint64_t stats_fingerprint(const uint8_t *bytes, size_t bytes_len);
]]

local lib = ffi.load("stats")

local function lua_string(s)
	local text = ffi.string(s)
	lib.stats_string_free(s)
	return text
end

local function f64_buf(value)
	-- a VLA cdata array carries no `#`; its instance size does.
	if ffi.istype("double[?]", value) then
		return value, ffi.sizeof(value) / ffi.sizeof("double")
	end
	local n = #value
	local arr = ffi.new("double[?]", n)
	for i = 1, n do
		arr[i - 1] = value[i]
	end
	return arr, n
end

local function u8_buf(value)
	-- a VLA cdata array carries no `#`; its instance size does.
	if ffi.istype("uint8_t[?]", value) then
		return value, ffi.sizeof(value) / ffi.sizeof("uint8_t")
	end
	local n = #value
	local arr = ffi.new("uint8_t[?]", n)
	for i = 1, n do
		arr[i - 1] = value[i]
	end
	return arr, n
end

-- stats_f64_array_to_table copies a `f64` sequence this library returned and
-- releases it.
local function stats_f64_array_to_table(arr)
	local n = tonumber(arr.len)
	local out = {}
	for i = 1, n do
		out[i] = arr.data[i - 1]
	end
	lib.stats_f64_array_free(arr)
	return out
end

local M = {}

local METRIC_TO_C = { median = 0, mad = 1, min = 2, max = 3 }
local METRIC_FROM_C = { [0] = "median", [1] = "mad", [2] = "min", [3] = "max" }

local function metric_to_c(name)
	local v = METRIC_TO_C[name]
	if v == nil then
		error("invalid Metric: " .. tostring(name))
	end
	return v
end

local function metric_from_c(value)
	return METRIC_FROM_C[tonumber(value)]
end

local Summary = {}
Summary.__index = Summary
M.Summary = Summary

local function wrap_summary(ptr)
	return setmetatable({ ptr = ffi.gc(ptr, lib.stats_summary_free) }, Summary)
end

function Summary:close()
	if self.ptr == nil then
		return
	end
	ffi.gc(self.ptr, nil)
	lib.stats_summary_free(self.ptr)
	self.ptr = nil
end

function Summary.new(samples)
	local samples_ptr, samples_len = f64_buf(samples)
	local err = ffi.new("char*[1]")
	local ret = lib.stats_summary_new(samples_ptr, samples_len, err)
	if err[0] ~= nil then
		error(lua_string(err[0]))
	end
	return wrap_summary(ret)
end

function Summary:median()
	return lib.stats_summary_median(self.ptr)
end

function Summary:mad()
	return lib.stats_summary_mad(self.ptr)
end

function Summary:min()
	return lib.stats_summary_min(self.ptr)
end

function Summary:max()
	return lib.stats_summary_max(self.ptr)
end

function Summary:deviations(value)
	local ret = lib.stats_summary_deviations(self.ptr, value)
	return ret
end

function Summary:deviations_all(values)
	local values_ptr, values_len = f64_buf(values)
	local ret = lib.stats_summary_deviations_all(self.ptr, values_ptr, values_len)
	return stats_f64_array_to_table(ret)
end

function Summary:deviations_into(values, out)
	local values_ptr, values_len = f64_buf(values)
	local out_ptr, out_len = f64_buf(out)
	lib.stats_summary_deviations_into(self.ptr, values_ptr, values_len, out_ptr, out_len)
	if type(out) == "table" then
		for i = 1, out_len do
			out[i] = out_ptr[i - 1]
		end
	end
end

function Summary:get(metric)
	local ret = lib.stats_summary_get(self.ptr, metric_to_c(metric))
	return ret
end

function Summary:label()
	local ret = lib.stats_summary_label(self.ptr)
	return lua_string(ret)
end

function Summary:rescale(factor)
	lib.stats_summary_rescale(self.ptr, factor)
end

function Summary.parse(text)
	local err = ffi.new("char*[1]")
	local ret = lib.stats_summary_parse(text, err)
	if err[0] ~= nil then
		error(lua_string(err[0]))
	end
	return wrap_summary(ret)
end

function M.fingerprint(bytes)
	local bytes_ptr, bytes_len = u8_buf(bytes)
	local ret = lib.stats_fingerprint(bytes_ptr, bytes_len)
	return ret
end

return M
