// @generated by `cargo soothfast docs gen-tests`
// source: docs/measuring.md
#![allow(unused)]

// line 11: compile-only (no_run)
#[rustfmt::skip]
#[allow(dead_code)]
fn doc_block_line_11() {
    use soothfast::{bench, fixture, keep};

    soothfast::bench_main!();

    #[fixture]
    fn samples_n(n: usize) -> Vec<f64> {
        let mut x: u64 = 42;
        (0..n)
            .map(|_| {
                x = x.wrapping_mul(6364136223846793005).wrapping_add(1442695040888963407);
                (x >> 11) as f64 / (1u64 << 53) as f64
            })
            .collect()
    }

    // Checked claims: complexity verified by size sweep, allocations exact.
    #[bench(group = "stats", setup_sized = samples_n, sizes(1024, 4096, 16384),
            complexity = "n log n", alloc = 8,
            covers = "soothfast_measure::stats::summarize")]
    fn bench_summarize(input: &[f64]) {
        let mut v = input.to_vec();
        keep(soothfast_measure::stats::summarize(keep(&mut v)));
    }
}
