// Code generated by `cargo soothfast bind gen`. DO NOT EDIT.
package io.soothfast.statskt

import java.io.IOException
import java.lang.ref.Cleaner
import java.nio.file.Files
import java.nio.file.StandardCopyOption

internal object Natives {
    val CLEANER: Cleaner = Cleaner.create()

    init {
        val libName = System.mapLibraryName("io_soothfast_statskt")
        val resource = "/natives/" + nativeDir() + "/" + libName
        try {
            val input = Natives::class.java.getResourceAsStream(resource)
            if (input == null) {
                System.loadLibrary("io_soothfast_statskt")
            } else {
                input.use { stream ->
                    val suffix = if (libName.contains('.')) {
                        libName.substring(libName.lastIndexOf('.'))
                    } else {
                        ""
                    }
                    val temp = Files.createTempFile("io_soothfast_statskt", suffix)
                    temp.toFile().deleteOnExit()
                    Files.copy(stream, temp, StandardCopyOption.REPLACE_EXISTING)
                    System.load(temp.toAbsolutePath().toString())
                }
            }
        } catch (e: IOException) {
            throw RuntimeException("failed to load io_soothfast_statskt", e)
        }
    }

    /** Touching this forces the block above to run. */
    fun load() {
    }

    private fun nativeDir(): String {
        val osName = System.getProperty("os.name").lowercase()
        val os = when {
            osName.contains("mac") -> "macos"
            osName.contains("win") -> "windows"
            else -> "linux"
        }
        val archName = System.getProperty("os.arch").lowercase()
        val arch = if (archName == "amd64") "x86_64" else archName
        return "$os-$arch"
    }
}
