// Code generated by `cargo soothfast bind gen`. DO NOT EDIT.
package io.soothfast.statskt

/** Thrown for every Statskt call that returns an error. */
class StatsktException(message: String) : RuntimeException(message)
