// Code generated by `cargo soothfast bind gen`. DO NOT EDIT.
@file:JvmName("Statskt")

package io.soothfast.statskt

private val loadNatives: Unit = Natives.load()
private external fun nativeFingerprint(bytes: ByteArray): Long

/** FNV-1a fingerprint of some bytes. */
fun fingerprint(bytes: ByteArray): Long {
    return nativeFingerprint(bytes)
}
