// Code generated by `cargo soothfast bind gen`. DO NOT EDIT.
package io.soothfast.statskt

import java.lang.ref.Cleaner

/** A robust summary of one sample set. */
class Summary private constructor(private val ptr: Long, marker: Raw) : AutoCloseable {
    companion object {
        init {
            Natives.load()
        }

        /** Parse a comma-separated sample set. */
        fun parse(text: String): Summary {
            return Summary(nativeParse(text), Summary.Raw)
        }

        @JvmStatic
        private external fun nativeNew(samples: DoubleArray): Long

        @JvmStatic
        private external fun nativeMedian(ptr: Long): Double

        @JvmStatic
        private external fun nativeMad(ptr: Long): Double

        @JvmStatic
        private external fun nativeMin(ptr: Long): Double

        @JvmStatic
        private external fun nativeMax(ptr: Long): Double

        @JvmStatic
        private external fun nativeDeviations(ptr: Long, value: Double): Double

        @JvmStatic
        private external fun nativeDeviationsAll(ptr: Long, values: DoubleArray): DoubleArray

        @JvmStatic
        private external fun nativeDeviationsInto(ptr: Long, values: DoubleArray, out: DoubleArray): Unit

        @JvmStatic
        private external fun nativeGet(ptr: Long, metric: Int): Double

        @JvmStatic
        private external fun nativeLabel(ptr: Long): String

        @JvmStatic
        private external fun nativeRescale(ptr: Long, factor: Double): Unit

        @JvmStatic
        private external fun nativeParse(text: String): Long

        @JvmStatic
        private external fun nativeFree(ptr: Long)
    }

    private object Raw

    private val cleanable: Cleaner.Cleanable = Natives.CLEANER.register(this, State(ptr))

    internal fun nativePtr(): Long = ptr

    private class State(private val ptr: Long) : Runnable {
        override fun run() {
            nativeFree(ptr)
        }
    }

    /** Summarize a sample set. Fails on an empty one, which has no median. */
    constructor(samples: DoubleArray) : this(nativeNew(samples), Raw)

    val median: Double
        get() {
            return nativeMedian(ptr)
        }

    /** Median absolute deviation, unscaled. */
    val mad: Double
        get() {
            return nativeMad(ptr)
        }

    val min: Double
        get() {
            return nativeMin(ptr)
        }

    val max: Double
        get() {
            return nativeMax(ptr)
        }

    /** How far `value` sits from the median, in MAD units. */
    fun deviations(value: Double): Double {
        return nativeDeviations(ptr, value)
    }

    /** How far each of `values` sits from the median, in MAD units. */
    fun deviationsAll(values: DoubleArray): DoubleArray {
        return nativeDeviationsAll(ptr, values)
    }

    /** [`Summary::deviations_all`], writing into a caller-owned buffer. */
    fun deviationsInto(values: DoubleArray, out: DoubleArray) {
        nativeDeviationsInto(ptr, values, out)
    }

    /** Read one statistic by name. */
    fun get(metric: Metric): Double {
        return nativeGet(ptr, metric.ordinal)
    }

    /** A one-line rendering of the whole summary. */
    fun label(): String {
        return nativeLabel(ptr)
    }

    /** Scale every statistic by `factor`. */
    fun rescale(factor: Double) {
        nativeRescale(ptr, factor)
    }

    override fun close() {
        cleanable.clean()
    }
}
