// Code generated by `cargo soothfast bind gen`. DO NOT EDIT.

#[allow(dead_code)]
fn __throw_unless_pending(env: &mut ::jni::JNIEnv, pending: bool, message: String) {
    if !pending {
        let _ = env.throw_new("java/lang/RuntimeException", message);
    }
}

#[allow(dead_code)]
fn metric_to_ordinal(value: ::soothfast_demo::Metric) -> i32 {
    match value {
        ::soothfast_demo::Metric::Median => 0,
        ::soothfast_demo::Metric::Mad => 1,
        ::soothfast_demo::Metric::Min => 2,
        ::soothfast_demo::Metric::Max => 3,
    }
}

#[allow(dead_code)]
fn metric_from_ordinal(value: i32) -> ::soothfast_demo::Metric {
    match value {
        0 => ::soothfast_demo::Metric::Median,
        1 => ::soothfast_demo::Metric::Mad,
        2 => ::soothfast_demo::Metric::Min,
        3 => ::soothfast_demo::Metric::Max,
        _ => unreachable!("Java only ever sends back one of this enum's own ordinals"),
    }
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_io_soothfast_statskt_Summary_nativeNew<'local>(
    mut env: ::jni::JNIEnv<'local>,
    _class: ::jni::objects::JClass<'local>,
    samples: ::jni::objects::JDoubleArray<'local>
) -> i64 {
    let __len = match env.get_array_length(&samples) {
        Ok(v) => v as usize,
        Err(e) => {
            let pending = matches!(e, ::jni::errors::Error::JavaException);
            __throw_unless_pending(&mut env, pending, e.to_string());
            return 0i64;
        }
    };
    let mut __raw = vec![0.0; __len];
    match env.get_double_array_region(&samples, 0, &mut __raw) {
        Ok(()) => {}
        Err(e) => {
            let pending = matches!(e, ::jni::errors::Error::JavaException);
            __throw_unless_pending(&mut env, pending, e.to_string());
            return 0i64;
        }
    }
    let samples: Vec<f64> = __raw;
    let __out = ::soothfast_demo::Summary::new(samples);
    match __out {
        Ok(value) => {
            Box::into_raw(Box::new(value)) as i64
        }
        Err(reason) => {
            let _ = env.throw_new("io/soothfast/statskt/StatsktException", ::std::string::ToString::to_string(&reason));
            0i64
        }
    }
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_io_soothfast_statskt_Summary_nativeMedian<'local>(
    _env: ::jni::JNIEnv<'local>,
    _class: ::jni::objects::JClass<'local>,
    ptr: i64,
) -> f64 {
    let __out = (unsafe { &*(ptr as *const ::soothfast_demo::Summary) }).median.clone();
    __out
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_io_soothfast_statskt_Summary_nativeMad<'local>(
    _env: ::jni::JNIEnv<'local>,
    _class: ::jni::objects::JClass<'local>,
    ptr: i64,
) -> f64 {
    let __out = (unsafe { &*(ptr as *const ::soothfast_demo::Summary) }).mad.clone();
    __out
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_io_soothfast_statskt_Summary_nativeMin<'local>(
    _env: ::jni::JNIEnv<'local>,
    _class: ::jni::objects::JClass<'local>,
    ptr: i64,
) -> f64 {
    let __out = (unsafe { &*(ptr as *const ::soothfast_demo::Summary) }).min.clone();
    __out
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_io_soothfast_statskt_Summary_nativeMax<'local>(
    _env: ::jni::JNIEnv<'local>,
    _class: ::jni::objects::JClass<'local>,
    ptr: i64,
) -> f64 {
    let __out = (unsafe { &*(ptr as *const ::soothfast_demo::Summary) }).max.clone();
    __out
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_io_soothfast_statskt_Summary_nativeDeviations<'local>(
    _env: ::jni::JNIEnv<'local>,
    _class: ::jni::objects::JClass<'local>,
    ptr: i64,
    value_: f64
) -> f64 {
    let this = unsafe { &*(ptr as *const ::soothfast_demo::Summary) };
    let __out = this.deviations(value_);
    __out
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_io_soothfast_statskt_Summary_nativeDeviationsAll<'local>(
    mut env: ::jni::JNIEnv<'local>,
    _class: ::jni::objects::JClass<'local>,
    ptr: i64,
    values: ::jni::objects::JDoubleArray<'local>
) -> ::jni::sys::jdoubleArray {
    let this = unsafe { &*(ptr as *const ::soothfast_demo::Summary) };
    let result = unsafe { env.get_array_elements_critical(&values, ::jni::objects::ReleaseMode::NoCopyBack) };
    if let Err(ref e) = result {
        let pending = matches!(e, ::jni::errors::Error::JavaException);
        let message = e.to_string();
        drop(result);
        __throw_unless_pending(&mut env, pending, message);
        return ::std::ptr::null_mut();
    }
    let values_pin = result.unwrap();
    let __out = this.deviations_all(&values_pin);
    drop(values_pin);
    {
            let __values: Vec<f64> = __out;
            let __arr = match env.new_double_array(__values.len() as i32) {
                Ok(v) => v,
                Err(e) => {
            let pending = matches!(e, ::jni::errors::Error::JavaException);
            __throw_unless_pending(&mut env, pending, e.to_string());
            return ::std::ptr::null_mut();
        }
            };
            match env.set_double_array_region(&__arr, 0, &__values) {
                Ok(()) => {}
                Err(e) => {
            let pending = matches!(e, ::jni::errors::Error::JavaException);
            __throw_unless_pending(&mut env, pending, e.to_string());
            return ::std::ptr::null_mut();
        }
            }
            __arr.into_raw()
        }
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_io_soothfast_statskt_Summary_nativeDeviationsInto<'local>(
    mut env: ::jni::JNIEnv<'local>,
    _class: ::jni::objects::JClass<'local>,
    ptr: i64,
    values: ::jni::objects::JDoubleArray<'local>,
    out: ::jni::objects::JDoubleArray<'local>
) {
    let this = unsafe { &*(ptr as *const ::soothfast_demo::Summary) };
    let values: Vec<f64> = {
        let result = unsafe { env.get_array_elements_critical(&values, ::jni::objects::ReleaseMode::NoCopyBack) };
        if let Err(ref e) = result {
        let pending = matches!(e, ::jni::errors::Error::JavaException);
        let message = e.to_string();
        drop(result);
        __throw_unless_pending(&mut env, pending, message);
        return ;
    }
        let guard = result.unwrap();
        guard.to_vec()
    };
    let result = unsafe { env.get_array_elements_critical(&out, ::jni::objects::ReleaseMode::CopyBack) };
    if let Err(ref e) = result {
        let pending = matches!(e, ::jni::errors::Error::JavaException);
        let message = e.to_string();
        drop(result);
        __throw_unless_pending(&mut env, pending, message);
        return ;
    }
    let mut out_pin = result.unwrap();
    this.deviations_into(&values, &mut out_pin);
    drop(out_pin);
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_io_soothfast_statskt_Summary_nativeGet<'local>(
    _env: ::jni::JNIEnv<'local>,
    _class: ::jni::objects::JClass<'local>,
    ptr: i64,
    metric: i32
) -> f64 {
    let this = unsafe { &*(ptr as *const ::soothfast_demo::Summary) };
    let metric = metric_from_ordinal(metric);
    let __out = this.get(metric);
    __out
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_io_soothfast_statskt_Summary_nativeLabel<'local>(
    mut env: ::jni::JNIEnv<'local>,
    _class: ::jni::objects::JClass<'local>,
    ptr: i64
) -> ::jni::sys::jstring {
    let this = unsafe { &*(ptr as *const ::soothfast_demo::Summary) };
    let __out = this.label();
    match env.new_string(__out) {
        Ok(v) => v.into_raw(),
        Err(e) => {
            let pending = matches!(e, ::jni::errors::Error::JavaException);
            __throw_unless_pending(&mut env, pending, e.to_string());
            return ::std::ptr::null_mut();
        }
    }
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_io_soothfast_statskt_Summary_nativeRescale<'local>(
    _env: ::jni::JNIEnv<'local>,
    _class: ::jni::objects::JClass<'local>,
    ptr: i64,
    factor: f64
) {
    let this = unsafe { &mut *(ptr as *mut ::soothfast_demo::Summary) };
    this.rescale(factor);
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_io_soothfast_statskt_Summary_nativeParse<'local>(
    mut env: ::jni::JNIEnv<'local>,
    _class: ::jni::objects::JClass<'local>,
    text: ::jni::objects::JString<'local>
) -> i64 {
    let text: String = match env.get_string(&text) {
        Ok(v) => v.into(),
        Err(e) => {
            let pending = matches!(e, ::jni::errors::Error::JavaException);
            __throw_unless_pending(&mut env, pending, e.to_string());
            return 0i64;
        }
    };
    let __out = ::soothfast_demo::Summary::parse(&text);
    match __out {
        Ok(value) => {
            Box::into_raw(Box::new(value)) as i64
        }
        Err(reason) => {
            let _ = env.throw_new("io/soothfast/statskt/StatsktException", ::std::string::ToString::to_string(&reason));
            0i64
        }
    }
}

/// Release a `Summary` this library returned. Releasing one twice, or one
/// this library did not return, is undefined.
#[unsafe(no_mangle)]
pub extern "system" fn Java_io_soothfast_statskt_Summary_nativeFree<'local>(
    _env: ::jni::JNIEnv<'local>,
    _class: ::jni::objects::JClass<'local>,
    ptr: i64,
) {
    drop(unsafe { Box::from_raw(ptr as *mut ::soothfast_demo::Summary) });
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_io_soothfast_statskt_Statskt_nativeFingerprint<'local>(
    mut env: ::jni::JNIEnv<'local>,
    _class: ::jni::objects::JClass<'local>,
    bytes: ::jni::objects::JByteArray<'local>
) -> i64 {
    let __len = match env.get_array_length(&bytes) {
        Ok(v) => v as usize,
        Err(e) => {
            let pending = matches!(e, ::jni::errors::Error::JavaException);
            __throw_unless_pending(&mut env, pending, e.to_string());
            return 0;
        }
    };
    let mut __raw = vec![0; __len];
    match env.get_byte_array_region(&bytes, 0, &mut __raw) {
        Ok(()) => {}
        Err(e) => {
            let pending = matches!(e, ::jni::errors::Error::JavaException);
            __throw_unless_pending(&mut env, pending, e.to_string());
            return 0;
        }
    }
    let bytes: Vec<u8> = __raw.into_iter().map(|v| v as u8).collect();
    let __out = ::soothfast_demo::fingerprint(bytes);
    __out as i64
}
