# Code generated by `cargo soothfast sdk gen`. DO NOT EDIT.
"""Wire models for acme-items."""
from __future__ import annotations

import dataclasses
import typing


@dataclasses.dataclass(frozen=True)
class ApiResponse_Item:
    status: typing.Literal["ok", "error"]
    data: Item | str | None = None
    meta: typing.Any | None = None


@dataclasses.dataclass(frozen=True)
class Item:
    """One item."""

    id: int
    from_: str | None = None
    logo_url: str | None = None
    logo_url_: str | None = None
    note: str | None = None

    _WIRE: typing.ClassVar[dict[str, str]] = {
        "from_": "from",
        "logo_url": "logoUrl",
        "logo_url_": "logo_url",
    }


@dataclasses.dataclass(frozen=True)
class NewItem:
    name: str
